### PR TITLE
Fixes 1280

### LINKED ISSUE #1280: Wrong live_photo_url  after upgrade from 4.4.0 to git master
After upgarde from 4.4.0 release to git master branch my previously imported live photos did not display the video part due to change of live_photo_url json key returned  by /api/Photo::get.

4.4.0
"live_photo_url": "uploads/big/0eca72a047014b57f3cc7a96ca80d26a.mov"

git master
"live_photo_url": "uploads/0eca72a047014b57f3cc7a96ca80d26a.mov"

Photos initially imported from command line with symlinks.
Temporary fixed in database by adding 'big/' prefix to live_photo_short_path column in photos table;

### PR DESCRIPTION
**Pull request by nagmat84**
Since the big refactoring the various columns which store paths store the complete, relative path of files to avoid hard-coding of prefixes in the Lychee source code. The original migration did not update the path for live photos accordingly. This belated migration rectifies the situation.

### CODE REVIEW

**Review by d7415 — APPROVED** [review]
Untested, but makes sense to me.

File: database/migrations/2022_04_18_174417_fix_live_photo_short_path.php [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+	 * Reverse the migrations.
+	 *
+	 * @return void
+	 *
+	 * @throws RuntimeException
+	 */
+	public function down()
+	{
+		// In contrast to all other programming languages, the first character
+		// of a string has index 1 (not 0) in SQL.
```
Comment (kamil4) [inline database/migrations/2022_04_18_174417_fix_live_photo_short_path.php:55]: You've never programmed in Pascal, have you? :wink:

**Review by kamil4 — APPROVED** [review]
LGTM (untested).

File: database/migrations/2022_04_18_174417_fix_live_photo_short_path.php (hunk 1 above)
Comment (nagmat84) [reply database/migrations/2022_04_18_174417_fix_live_photo_short_path.php:55]: I did and forgot. 😂 I had Pascal in middle school.
