### PR TITLE
Completely new front-end & version 5.0.0!

### LINKED ISSUE #12: Shared albums: policy
If an album is shared, do we want to automatically apply it to the children ?
Or is this something that we only do in the sharing panel (click on parent also move children) ?

### LINKED ISSUE #90: Missing UI Elements in Photo View
I see no reason not to have the contectmenu from the album view in the photo view too. Or do I miss something? I would also suggest to add adding tags in the sidebar :-)

image

### LINKED ISSUE #104: Rework Sharing Dialog in Settings
image

### LINKED ISSUE #166: [Enhancement] Show album description between nav and pics
It would be nice to have option to show album description between the nav and the pictures in every album. This would give context to the user if the album name does not cut it. I know that it can be found behind the info button but that is not something regular/never before used user finds.

optionally it would be nice to have it as an admin (for all) and user (by album) setting to change visibility of this description.

### LINKED ISSUE #199: Depreciated dependencies cries for a new frontend.
### Detailed description of the problem

Depreciated dependencies

```
npm WARN deprecated basicmodal@3.3.9: Not maintained anymore
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

### Steps to reproduce the issue

`npm install`

### LINKED ISSUE #383: Allow other users to upload to shared albums
I and some friends are happy to share our pictures about Lychee. When we're together we take all the photos and then it would be nice if we could put all our photos into one album.
The problem with this is that users can only upload photos to their albums. 

So it would be cool if other users could upload to shared albums.

### LINKED ISSUE #725: [Enhancement] Login on direct album url if not logged in and album needs it
It would be nice if we could have something similar to the password prompt that pops up when you visit a password protected album URL directly for when you visit an album URL and that album requires you to be logged in as a user to see it - a pop-over login or a redirect to login with return url to send you back to the album after login.

### LINKED ISSUE #748: [Enhancement] UI/UX: give more information about the capabilities given to new users in the users page
I know that it can feel explanatory for people working on and using Lychee4 daily.
But I personally I'm a tech savvy user, i develop websites for a living and I've been an active user of Lychee for years now BUT : even for me "restricted account" means nothing. It's not documented and there is just a "lock" icon on the "create user" page.

It's a bit distressing to have a screen that could potentially give access to other users to your Lychee and not know what parameter does what... Imagine for end users that are just using it and don't know what's up behind it.

I think that:
1) icons only are not sufficient by themselves, even with a title tag that may or may not allow the end user to have the name of the option. It's generally considered bad practice in UI to only provide an icon as information.
2) the name Restricted is not very self explanatory. 
3) we need to give end users some more "tips" or notice about what they allow their friends/contacts to do by creating them an account with or without the "restricted" or "allow uploads" icons ticked.

This issue is here to start a conversation about possible improvements on the user creation page.

### LINKED ISSUE #828: Album name not correct displayed in confirmation popup when moving a newly created album
### Detailed description of the problem

When you want to move a newly created album into another one, the confirmation popup shown doesn't have the name of the albums, but _Untilted_ instead (note the typo as well 😄).

### Steps to reproduce the issue
**Steps to reproduce the behavior:**

1. Create a new album
2. Go back to parent
3. Create another album
4. Go back to parent
5. Try to move one of the newly created into the other

**Screenshots**
Note the two albums in the screenshot below: _test1_ and _test2_. I just created them, and this is the popup shown when I try to move _test2_ into _test1_.
image

### Output of the diagnostics

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   10.5.8-MariaDB-1:10.5.8+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040008
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   ***
    landing_title:                   ***
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      ***
    site_copyright_enable:           1
    site_copyright_begin:            2017
    site_copyright_end:              2020
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0

### Browser and system
macOS Big Sur 11.0.1
Tested on
- Safari 14.0.1
- Chrome 87.0.4280.88

### LINKED ISSUE #845: [Enhancement] Front-End on Livewire - Tracking advancement.
## TODO

- [ ] layouts (justified etc)
- [x] image view
- [ ] Upload
- [ ] side panel
- [ ] modals for albums (delete, share, new)
- [ ] modals for pictures (delete, share)
- [x] Basic settings view
- [x] Diagnostics view
- [x] Log view
- [x] U2F view
- [x] User view
- [x] Advanced setting view
- [ ] Modules view (improved settings)
- [ ] Context menus
- [ ] Hot keys for shortcuts
- [x] Admin login/password first query on install

## Expectations and Questions

- **Required:** seamless change from current front-end to Livewire = practically invisible to the user (but may induce minor loss of functionality).
- **Question:** Do we leave the JS version still available as a setting and freeze it like for the v3?
- **Question:** ~~Do we release the livewire first as a Beta functionality that is *Opt-in*? That way the refactoring can be propagated through the back-end without stopping new (hypothetical/hopeful :sweat_smile:) development of Lychee.~~ **Yes**.

### LINKED ISSUE #857: [Enhancement] Support for very large uploads by chunking
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

I would like to upload a few videos to Lychee that are gigabytes in size. Although this is documented and can be done in one request, it requires tweaking nginx and PHP configuration. It also prevents Lychee from being hosted behind proxies like Cloudflare which limits request sizes to 100MB on the free plan.

Instead, I think a better solution is to chunk uploads into small pieces. This will mitigate any upload size issues and also potentially speed things up by uploading the chunks in parallel.

As for the implementation details, it could be modeled after [S3's multipart upload](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html).

> Multipart upload is a three-step process: You initiate the upload, you upload the object parts, and after you have uploaded all the parts, you complete the multipart upload. Upon receiving the complete multipart upload request, Amazon S3 constructs the object from the uploaded parts, and you can then access the object just as you would any other object in your bucket.

### LINKED ISSUE #1053: Public album is not and can not be configured to be public
### Detailed description of the problem [REQUIRED]
Despite there being an album named `public`, the album is not actually public. Setting the public albums visibility to public manually results in an album named public, set to be public, but not actually being public. When attempting to save the visibility change, a message appears for a split second in the upper left saying `Server error or API not found`.

The `POST` request body is `function=Album%3A%3AsetPublic&albumID=public&full_photo=1&public=1&nsfw=0&visible=1&downloadable=0&share_button_visible=0`, the server response is a `422 - Unprocessable Entity`

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Error 1:
1. Go to site while having the album `Public` and not being logged in
2. See no album named `Public`
3. Be sad that you can't see the `Public` album

Error 2:
1. Go to album `Public` while being logged in
2. Click on `+` in the upper right
3. Click on `Album visibility`
4. Turn on the `Public` toggle of the `Public` album
5. Click `Save`
6. See error in the upper right
7. Note that when you go to `Album Visibility` again, it will claim to be set to `Public`, but it is not, and after a page refresh, will correctly show the album `Public` not being set to `Public`
8. Go to site and not being logged in
9. Be sad that you can't see the `Public` album

**Screenshots**
A sad image of a lack of a `Public` album
A visual representation of sadness in PNG form

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit

    System Information
    ------------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   10.5.10-MariaDB
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    ------------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Me
    landing_title:                   Myself
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    OpenStreetMap.org
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            0

### Browser and system
All browsers on all systems I would expect, tested with Firefox, Chrome and Edge on Windows 10

### LINKED ISSUE #1189: [Enhancement] Multiline descriptions with markdown support for images and albums
I would be very happy if Lychee would allow multiple lines in descriptions. In the best case additionally the support of Markdown in the description would be perfect.

### LINKED ISSUE #1211: [Enhancement] Date/Time display options
I would like to request a config option for the representation of date/time values, e.g. in the "Photo overlay" when using "Date taken" as:

Current default:
`Jan 7, 2022, 9:38:44 PM UTC+01:00`

I wish at least the option to select 24 hour format for the time and the "European" format for the date:
`7 Jan 2022, 21:38:44 UTC+01:00`

### LINKED ISSUE #1249: [Enhancement] header text for the gallery.
Is it tpossible to make it easy to add text to the header of the gallery?
At the moment what is the way to add some text to it? Thank you community

### LINKED ISSUE #1253: [Enhancement] Change album's Top Right menu behavior when selecting some pictures
I think almost all application change behavior of top right menu when files are selected.
For example, Google Photo will make option to add to album, delete and download options when some pictures selected.

But, Lychee won't change behavior. So I have to right click on selected pictures and select action.

I think changing options when selecting makes more easy to use UI.

Thanks.

### LINKED ISSUE #1462: [Change Proposal] Access Rights management: Users and Albums
Let's move out of the PR and discuss this here. As follows is the log of previous discussions.

### TL;DR: Proposition by @nagmat84 

- move protection settings `grants_full_photo`, `requires_link`, `is_downloadable`, `is_share_button_visible` from `base_albums` to `user_base_album`
- guest user becomes id = `null`
- GUI change:
   single dialog instead of two: A imagine a tabular like dialog with one row per user with whom the album is shared (including the anonymous user) and then a tuple of check boxes in columns for the various attributes. This means it would somewhat look similar to the layout we have for the user setting page.

@nagmat84 
> Let me sketch what I am thinking of:
> 
> I would like to have a unified approach for what is currently called protection settings (i.e. `is_public`, `is_downloadable`, etc.) and sharing photos and albums with authenticated users. It bothers me, that we can set attributes like `is_downloadable` on a per-album level if the album is public, but that we use a globally defined setting for that when the album is shared.
> 
> My idea is to have these settings on a per-share level, too. On a technical level, I would like to move the attributes `grants_full_photo`, `requires_link`, `is_downloadable`, `is_share_button_visible` from `base_albums` to `user_base_album`. In order to model a public album, I would insert a share with the `null` user into `user_base_album`. This makes a lot of sense, if you consider that `Auth::id` also returns `null` for the unauthenticated user. Hence, the boolean attribute `is_public` would be removed completely from `base_album` without replacement. An album is public if and only if it is shared with the `null` user. I assume this would also simplify the SQL queries, because the conditions become more consistent.
> 
> On the GUI level, we would only have a single dialog instead of two: A imagine a tabular like dialog with one row per user with whom the album is shared (including the anonymous user) and then a tuple of check boxes in columns for the various attributes. This means it would somewhat look similar to the layout we have for the user setting page.
> 
> In a second step I imagine the same approach, but for user groups. You can also share albums with groups and have the same options. All users are automatically members of the `null` group which by definition represents the group of authenticated users.
> 
> However, this endeavor is big. I would probably start with the users in one PR and then add groups in another PR. However, if we now make `is_public` tri-state, then we cannot do this in two separate PRs anymore, because this would mean temporarily losing a feature which we must not do.
> 
> This approach would also prevent future questions like the issue #438 which repeatedly pops up and which also caught me by surprise during writing my many authorization tests. I think it is a bad UI experience to "hide" those fundamental settings in the global configuration panel. But I admit it is much easier than implementing a proper UI.
> 
> Recently, we also had a discussion (@kamil4 might remember) that certain boolean attributes of an album (such as `is_downloadable`) are only defined if the album is public, but are otherwise undefined. This makes things unnecessary complex, because we cannot use that attribute when an album is shared. Obviously, this complexity would also be gone with the proposed alternative.

---

@kamil4 
> @nagmat84 I think these are great ideas. I too have been increasingly bothered by the limited applicability of the `base_album` flags and the cryptic global config variables used to augment them (I don't remember anymore but I may be responsible for the `downloadable` one; in retrospect, that was not a good name). In a way, the GUI has already been moving in the direction you outline, what with the "Share this album with users" having been added right next to the album visibility button.
> 
> A couple of points that pop in my head:
> 
> * It would be great to also have an `is_editable` or some such for sharing. Users have been asking us about it for years. It's orthogonal to what you propose and would probably be left as "future work" past the two PRs that you outlined, but at least the path to get there would be a lot more clear.
> * What about password protection? Would that be per-share as well?
> * Come to think of it, what about `requires_link` and `is_share_button_visible`? It feels like some of them make sense primarily for public (unauthenticated) mode although maybe I'm lacking imagination here and we should stay as flexible as possible...

---

@nagmat84 
> > * It would be great to also have an `is_editable` or some such for sharing. Users have been asking us about it for years. It's orthogonal to what you propose and would probably be left as "future work" past the two PRs that you outlined, but at least the path to get there would be a lot more clear.
> 
> Exactly my thoughts. I did not mention write access, because there are a lot of follow-up questions to be solved. For example, let's we have a `is_uploadable` attribute, such that user may upload to other users' albums, what happens with ownership? Currently, we only support single-ownership albums. Does this mean users lose the right to edit the photos they have just uploaded, because ownership gets transferred? If there is a general `is_editable` attribute, does this mean that user are also allowed to delete photos? These are all very interesting questions and I assume that we have to give up the concept of single-ownership albums in the long run.
> 
> But as you said: I would like to start with what we already support now, but re-structure it and if the architecture is clear, then it will be easier to go on from there.
> 
> > * What about password protection? Would that be per-share as well?
> 
> My mental picture was to leave that as the only per-album attribute which only affects unauthenticated users. For me that would be an extra input field in the dialog just below the table of shares which is only editable if the anonymous user is included in the sharing. IMHO, it doesn't make sense to ask authenticated users for an extra password. They have already proven their identity though their own password. If I didn't want those users to access the album, I would not have shared the album with them in the first place.
> 
> Actually, I would like to drop the password-support completely. I don't see any benefit in it, because one can always create a "dummy" user, lock the user such that no one can change its password and then share those user's credentials with the people. That would make the code so much easier in so many ways. In particular, we could drop this inefficient feature of unlocking all albums with the same password at once.
> 
> But probably, I am lacking the imagination of why this password feature is required.
> 
> > * Come to think of it, what about `requires_link` and `is_share_button_visible`? It feels like some of them make sense primarily for public (unauthenticated) mode although maybe I'm lacking imagination here and we should stay as flexible as possible...
> 
> I would keep those attributes on a per-share level.

---

@kamil4 
> This is probably not the best place for this conversation (wasn't there a dedicated issue where you outlined your ideas and that I could never find time to comment on?) but I'll bite...
> 
> > let's we have a `is_uploadable` attribute, such that user may upload to other users' albums, what happens with ownership? Currently, we only support single-ownership albums. Does this mean users lose the right to edit the photos they have just uploaded, because ownership gets transferred? If there is a general `is_editable` attribute, does this mean that user are also allowed to delete photos? These are all very interesting questions and I assume that we have to give up the concept of single-ownership albums in the long run.
> 
> In the long run, sure, everything is possible. In the short run, I would personally keep single-ownership and simply treat the user that an album was shared with in read/write mode as the co-owner of that album (just like the admin is). So the ownership of everything uploaded/copied/moved to that album changes to the owner of the album. What happens when the co-owner creates a sub-album, I have no idea (to be useful, I guess that one would also have to be shared).
> 
> I'm sure there would be users dissatisfied with that though, who would like "upload only" right so that the co-owner can't delete existing photos and such.
> 
> > > * What about password protection? Would that be per-share as well?
> 
> [snip]
> 
> > IMHO, it doesn't make sense to ask authenticated users for an extra password. They have already proven their identity though their own password. If I didn't want those users to access the album, I would not have shared the album with them in the first place.
> 
> Good point. I'm convinced.
> 
> > Actually, I would like to drop the password-support completely. I don't see any benefit in it, because one can always create a "dummy" user, lock the user such that no one can change its password and then share those user's credentials with the people. That would make the code so much easier in so many ways. In particular, we could drop this inefficient feature of unlocking all albums with the same password at once.
> > But probably, I am lacking the imagination of why this password feature is required.
> 
> Well, I happen to be an active user of password protected albums on my production instance, so let me give you my perspective.
> 
> First, I'm pretty sure that the feature dates back to Lychee v3, i.e., before multi-user support was added. So then that was the only option. With v4, you are right that there is an alternative.
> 
> But from users' point of view, that alternative is pretty clunky. With a password-protected album, when my parents in their seventies want to see the pictures of the grandkids, they just click on a single URL to the password-protected album and when they do, a dialog box pops up asking for a password and as soon as they do, pictures show up. With multi-user, that's currently not the case. The URL needs to be to the top-level gallery, where they first need to click on the little arrow in the top-left, provide a login and password, then click on the album that shows up. It's a lot more... friction. No wonder we had this very complaint from a user recently -- that they would like an option to at least go straight to the login/password dialog box.

### LINKED ISSUE #1676: Unable to open sidebar, can't navigate away from log/diagnostic/setting page
### Detailed description of the problem
While trying to get to the bottom of #1674, I stumbled across this curious issue. Normally, closing the sidebar refreshes to the home page. However, following the below steps will close the sidebar without refreshing--and you're unable to open the sidebar again. In order to navigate away, you need to refresh the browser or otherwise alter the URL directly. 

### Steps to reproduce the issue
1. Log in as admin
2. Click settings cog on top left
3. Open an album
4. Click "Settings", "Users", "U2F", "Sharing", "Show Logs", or "Diagnostics" on the left sidebar
5. Click "Close" on the left sidebar (NOT the chevron to the right of the sidebar)
6. Click the chevron on the top left and the sidebar will not open

**Screenshots**
After step 3, an album and the side bar are opened
image

Opened the logs after step 4. Note how the URL has not changed.
image

Following step 5, sidebar is closed, log screen is still open, and the URL has not changed. Clicking the chevron changes the color but otherwise does nothing.
image

### Output of the diagnostics 

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.2

    System Information
    --------------
    Lychee Version (git):                    master (6ca3066) -- 1 commits behind 923bfb4 (11 seconds ago)
    DB Version:                              4.6.5
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.13
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                America/Chicago
    Max uploaded file size:                  500M
    Max post size:                           500M
    Max execution time:                      200
    MySQL Version:                           8.0.31-0ubuntu0.20.04.2
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1690
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.

    Lychee total space:                      37.72 GB
    Upload folder space:                     37.56 GB
    System total space:                      72.50 GB
    System free space:                       22.96 GB (31%)

    Config Information
    --------------
    version:                                 040605
    check_for_updates:                       1
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      date
    default_license:                         CC-BY-NC-SA-4.0
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              [Fname] [Lname]
    landing_title:                           [Name]'s Photos!
    landing_subtitle:                        Pictures and movies of various trips
    sm_facebook_url:                         https://www.facebook.com/[user]
    sm_flickr_url:                           
    sm_twitter_url:                          https://www.twitter.com/[user]
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              [Name]'s Photos
    footer_show_copyright:                   1
    site_copyright_begin:                    2019
    site_copyright_end:                      2022
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             1
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   1
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    1
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       1
    location_decoding_timeout:               30
    location_show:                           0
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            0
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 8
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    allow_username_change:                   1

### Browser and system

- Win 10 Pro 22H2
  - Firefox 102.6.0esr (64-bit)
  - Chrome 108.0.5359.125 (Official Build) (64-bit)
- iPadOS 16.1.1 (20B101)
  - Safari
- Android 13 build TP1A.221105.002
  - Firefox 108.1.0 (Build #2015920443) (had to rotate to landscape)
  - Chrome 108.0.5359.128 (had to rotate to landscape)
- Ubuntu 20.04.5 LTS
  - Firefox 108.0 (64-bit)

### LINKED ISSUE #1704: [Enhancement] Add real links to albums
Go to https://lycheeorg.github.io/demo/ and hover with the mouse over the different albums.
There is no link so you cannot open the album with a middle click in a new tab.
The same problem is with any picture inside an album.

### LINKED ISSUE #1720: Download button is visible and does not support download rights yet. (backend is fine).
### Detailed description of the problem [REQUIRED]
Hi,

yesterday I installed lychee 4.7.0 using the official docker container, so this is basically my docker-compose file:

```
cat <fancy path>/docker-compose.yml
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Laravel-Docker
#-------------------------------------------

version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=<substituted fancy PW>
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=<substituted fancy second PW>
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    dns:
      - <fancy DNS IP>
#    security_opt: ## commented out to proof it's not the cause
#      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 4G
        reservations:
          memory: 500M
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"

  lychee:
    image: lycheeorg/lychee:dev
    container_name: lychee
    ports:
      - 90:80
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
    networks:
      - lychee
      - proxy
    environment:
      - PHP_TZ=Europe/Berlin
      - TIMEZONE=Europe/Berlin
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=<substituted fancy second PW>
      - STARTUP_DELAY=30
    dns:
      - <fancy DNS IP>
#    security_opt: ## commented out to proof it's not the cause
#      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2G
        reservations:
          memory: 250M
    restart: unless-stopped
    depends_on:
      - lychee_db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.lychee.entryPoints=https"
      - "traefik.http.routers.lychee.rule=Host(`<fancy private URL>`)"
      - "traefik.http.routers.lychee.tls=true"
      - "traefik.http.routers.lychee.tls.certResolver=http"
      - "traefik.http.routers.lychee.middlewares= default@file"
      - "traefik.http.routers.lychee.service=lychee"
      - "traefik.http.services.lychee.loadBalancer.server.port=80"
      - "traefik.http.services.lychee.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.lychee.loadbalancer.sticky.cookie.secure=true"

networks:
  lychee:
  proxy:
    external: true

volumes:
  mysql:
```

So with that lychee is perfectly fine reachable via my private URL or locally directly connected to the server (http://\<fancy IP\>:90) and working as authenticated user (either admin or standard user) looks also fine.
As my intention is to use this a way to provide access to specific albums to people without them having an account but still don't want to have the pictures fully publicly exposed to the internet I want to achieve this by the following anonymous settings for my test album:
grafik

Accessing the album without user looks good in the first place:
grafik

Downloading the full album works also as intented (I tried the download and it works):
grafik

Now I want the anon-user also to be able to download only specific pictures in different sizes (as set per user settings above), but selecting a picture does not show the three dots in the right to download a picture:
grafik

Interestingly if I change the anon-settings to a wrong state:
grafik

the anon-user should not be able to see the three dots or to download the picture, but:
grafik

now he sees the three dots and is also able to click on the different sizes:
grafik

luckily the permissions are still fine:
grafik

I checked your demo page and there it seems to be all right. So did I do something wrong in my docker setup or in the configuration?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
See the detailed description above, it contains my steps.

**Screenshots**
See the screenshots above.

### Output of the diagnostics  [REQUIRED]
```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.2
    Warning: git (software) is not available.
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
    Foreign key: user_base_album.user_id        → users.id             : CASCADE




    System Information
    --------------
    Lychee Version (git):                    master (26d9b75) -- 2 commits behind 1dd61c1 (2 seconds ago)
    DB Version:                              4.7.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.12
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Berlin
    Max uploaded file size:                  100M
    Max post size:                           100M
    Max execution time:                      3600
    MySQL Version:                           10.10.2-MariaDB-1:10.10.2+maria~ubu2204
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.




    Config Information
    --------------
    version:                                 040700
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              Wolf Revo
    landing_title:                           Wolf Revo
    landing_subtitle:                        
    sm_facebook_url:                         
    sm_flickr_url:                           
    sm_twitter_url:                          
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              Wolfi's Bilderbude
    footer_show_copyright:                   1
    site_copyright_begin:                    2015
    site_copyright_end:                      2023
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           0
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            0
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
```

### Browser and system
Windows 10, Firefox, Edge, Chrome (tested with them all)

### LINKED ISSUE #1732: [Enhancement] Consistent URLs when Landing Page is disabled
When the Landing Page is enabled, the Gallery and all its URLs are `https://example.com/gallery#xyzzy` and `https://example.com/gallery#xyzzy/aabbcc`.
When the Landing Page is disabled, the URLs are `https://example.com/#xyzzy` and `https://example.com/#xyzzy/aabbcc`, but this is only due to the IndexController also delivering the Gallery in this case. The `gallery#` URLs still seem to be the canonical URLs.

Also, redirects are going to the `gallery#` versions. `https://example.com/r/xyzzy` -> `https://example.com/gallery#xyzzy`
When enabling the Landing Page at a later time, previous URLs like `https://example.com/#xyzzy` do not work anymore.

Wouldn't it be more consistent to have all URLs generated by the frontend include the `gallery` prefix? There are two options:

1. Currently IndexController renders the frontend when Landing Page is disabled. This could be replaced by a `redirect('gallery')`. This would be the "cleanest" way to achieve this, however when using this option, there is not real "homepage" anymore (because `/` redirects to `/gallery`). (The return type of the method also needs to be adjusted)

https://github.com/LycheeOrg/Lychee/blob/dc33883d76a3d76bf961ca29c9cacc108b7fc9d8/app/Http/Controllers/IndexController.php#L68

```diff
- 			return $this->frontend();
+ 			return redirect('gallery');
```

or 2. Change `lychee.goto` so it includes the prefix:

https://github.com/LycheeOrg/Lychee-front/blob/5ade25d897bc04df9cab15bda0dc0fb6c5e0b16a/scripts/main/lychee.js#L756

```diff
- 	url = "#" + (url !== null ? url : "");
+ 	url = "gallery#" + (url !== null ? url : "");
```

I'm not sure if the latter has implications on other URLs generated using `lychee.goto`, however I guess (!) this method is only used to generate album or photo URLs.

### LINKED ISSUE #1744: UX broken on version 4.7.0 for Safari iPhone
### Detailed description of the problem [REQUIRED]
Navigating between pictures of the same album is boken in version 4.7.0 on Safari iPhone 15.4.1
With version 4.7.0 when sliding right, instead of jumping to next picture it show pictures infos and then interface is broken.
See screenshot

I tested the live [demo](https://lycheeorg.github.io/demo/) on the same device, navigation is working fine.

NB : regression concern only safari on iPhone. I tested version 4.7.0 on Firefox Mobile, navigation is working fine.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lychee 4.70
2. Create an album with a least 2 pictures
3. Click on the first picture to open it fullscreen
4. Slide your finger to the right to show next picture
5. BUG! Instead of showing next picture, it show picture info and the interface is broken

**Screenshots**

photo_2023-01-30_23-27-13

photo_2023-01-30_23-25-33

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: /home/yunohost.app/lychee/uploads/ is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/ has permissions 0750, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium has permissions 0750, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/67 is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium/67 has permissions 0770, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/67/4c is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium/67/4c has permissions 0770, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/81 has permissions 0775, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/43 is owned by group www-data, but should be owned by one out of lychee
    Warning: 669 more directories with wrong owner
    Warning: 1314 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.2
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

    System Information
    --------------
    Lychee Version (release):                4.7.0
    DB Version:                              4.7.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.14
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                UTC
    Max uploaded file size:                  512M
    Max post size:                           512M
    Max execution time:                      30
    MySQL Version:                           10.5.18-MariaDB-0+deb11u1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.

    Config Information
    --------------
    version:                                 040700
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Lychee v4
    footer_show_copyright:                   1
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1

### Browser and system

Safara and iPhone 15.4.1

### LINKED ISSUE #1825: [Enhancement] Change accent color
Meanwhile we have an option (or not) to change the accent color, I'd like to share my CSS to change the accent color to orange, but we can set any HEX color value on `--custom-accent-color`.
```
:root {--custom-accent-color: #fcba03;} /* Choose here any color you want */
.settings_view .basicModal__button,.settings_view>div .select::after,.users_view_line .basicModal__button_CREATE,.u2f_view_line .basicModal__button_CREATE,.clear_logs_update .basicModal__button, .logs_diagnostics_view .basicModal__button,input[type=checkbox],.basicModal__button#basicModal__action,div.basicModal__content a.button,.sharing_view .basicModal__button,.users_view_line .basicModal__button_OK{color:var(--custom-accent-color);}
.album:hover .thumbimg, .photo:hover .thumbimg,.album.active .thumbimg, .album:focus .thumbimg, .photo.active .thumbimg, .photo:focus .thumbimg,.toolbar input[type=text].header__search:focus,.settings_view>div textarea:focus{border-color:var(--custom-accent-color);}
.album.selected img, .photo.selected img{outline:var(--custom-accent-color) solid 1px;}
.settings_view .basicModal__button:hover,.users_view_line .basicModal__button_CREATE:hover,.u2f_view_line .basicModal__button_CREATE:hover,div.basicModal__content a.button:hover,.sharing_view .basicModal__button:hover,.basicContext__item:not(.basicContext__item--disabled):hover .basicContext__data,.users_view_line .basicModal__button_OK:hover{background:var(--custom-accent-color);}
.settings_view>div input:checked+.slider,.settings_view>div .slider:before,input[type=checkbox].slider::before,input[type=checkbox].slider:checked{background-color:var(--custom-accent-color);}
.settings_view input:hover,.users_view_line input:hover{border-bottom:1px solid var(--custom-accent-color);}
.users_view_line input.text:focus,input[type=password]:focus, input[type=text]:focus,.settings_view input.text:focus{border-bottom-color:var(--custom-accent-color);}
.clear_logs_update .iconic, .logs_diagnostics_view .iconic,.toolbar .button--info.active .iconic,.sharing_view .blue .iconic,div.basicModal__content a.button .iconic,.users_view_line .choice .checkbox .iconic,.sharing_view .choice .checkbox .iconic{fill:var(--custom-accent-color);}
#lychee_sidebar_header{border-top:1px solid var(--custom-accent-color);}
.sharing_view .borderBlue{border:1px solid var(--custom-accent-color);}
```

### LINKED ISSUE #1891: Login popup appears if no albums created
### Detailed description of the problem [REQUIRED]

When you enter the gallery page, in which no albums have been created (but it is indicated that the albums "last", "marked", "today" are allowed), you are prompted to log in.

This does not happen if at least one album has been created (even with 0 photos)

Looks like a bug.

image

### Steps to reproduce the issue

Lychee installed 5 minutes ago. 

Granted access: 

image

### Output of the diagnostics  [REQUIRED]

```
root@winterskyru:/var/www/wintersky.gallery# php artisan lychee:diagnostics


Diagnostics
-----------
(some warnings skipped)
Foreign key: access_permissions.user_id     → users.id             : CASCADE
Foreign key: albums.parent_id               → albums.id            : RESTRICT
Foreign key: albums.id                      → base_albums.id       : RESTRICT
Foreign key: albums.cover_id                → photos.id            : CASCADE
Foreign key: base_albums.owner_id           → users.id             : RESTRICT
Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
Foreign key: photos.album_id                → albums.id            : RESTRICT
Foreign key: photos.owner_id                → users.id             : RESTRICT
Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT

System Information
------------------
Lychee Version (release):                4.9.2
DB Version:                              4.9.2

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.2.7
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Moscow
Max uploaded file size:                  2M
Max post size:                           8M
Max execution time:                      0
MySQL Version:                           10.5.19-MariaDB-0+deb11u2

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1691
GD Version:                              2.3.3
Number of foreign key:                   11 found.

Config Information
------------------
version:                                 040902
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    ru
layout:                                  1
image_overlay_type:                      desc
default_license:                         CC-BY-NC-SA-4.0
compression_quality:                     80
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              Karel Wintersky
landing_title:                           Karel Wintersky
landing_subtitle:                        My photos
sm_facebook_url:                         
(skipped)
sm_youtube_url:                          
landing_background:                      
site_title:                              Wintersky::Gallery
footer_show_copyright:                   1
site_copyright_begin:                    2023
site_copyright_end:                      2023
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           1
SL_enable:                               0
SL_for_admin:                            0
recent_age:                              1
grants_download:                         0
photos_wraparound:                       1
map_display:                             1
zip64:                                   1
map_display_public:                      1
map_provider:                            OpenStreetMap.org
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              1
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           1
location_show_public:                    1
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
public_photos_hidden:                    1
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
album_decoration:                        layers
album_decoration_orientation:            row
allow_username_change:                   1
auto_fix_orientation:                    1
use_job_queues:                          0
random_album_id:                         starred
use_last_modified_date_when_no_exif_date: 1

```

### Browser and system

Server: Debian 11
Host: chrome / neon kde

### LINKED ISSUE #1948: Internal server error on photo upload (permissions?)
### Detailed description of the problem [REQUIRED]

It is not possible to add new photos. The (gui) upload lychee page shows an internal server error and in the logs there is the following entry: 
App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int

Owner and group of public/uploads and public/sym directories are dedicated docker user and users.
See my docker compose file attached.

### Steps to reproduce the issue
1. Go to any existing folder or create new one.
2. Click on "+" and click on "Upload photo". 
3. See that photo upload failed due to server error.
4. See error in logs: App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int

### Output of the diagnostics  [REQUIRED]

Diagnostics
-----------
Warning: /var/www/html/Lychee/public/uploads/ is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/import is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x/8c is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x/8c/32 is owned by group users, but should be owned by one out of root
Warning: 5166 more directories with wrong owner
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Using 32 bit PHP, recommended upgrade to 64 bit
Warning: git (software) is not available.

System Information
------------------
Lychee Version (git):                    ?? (a52fd8e) -- Could not compare.
DB Version:                              4.9.4

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.2.7
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Warsaw
Max uploaded file size:                  2M
Max post size:                           8M
Max execution time:                      0
MySQL Version:                           10.6.12-MariaDB-log

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1691
GD Version:                              2.3.3
Number of foreign key:                   11 found.

Config Information
------------------
version:                                 040904
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      desc
default_license:                         reserved
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              A. M. Sz. A. G. Hołyszowie
landing_title:                           John Smith
landing_subtitle:                        Cats, Dogs & Humans Photography
sm_facebook_url:                         https://www.facebook.com/JohnSmith
sm_flickr_url:                           https://www.flickr.com/JohnSmith
sm_twitter_url:                          https://www.twitter.com/JohnSmith
sm_instagram_url:                        https://instagram.com/JohnSmith
sm_youtube_url:                          https://www.youtube.com/JohnSmith
landing_background:                      dist/cat.webp
site_title:                              Lychee v4
footer_show_copyright:                   0
site_copyright_begin:                    2019
site_copyright_end:                      2019
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           0
SL_enable:                               0
SL_for_admin:                            0
recent_age:                              1
grants_download:                         0
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            Wikimedia
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              1
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           1
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 1
public_photos_hidden:                    1
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
album_decoration:                        layers
album_decoration_orientation:            row
allow_username_change:                   1
auto_fix_orientation:                    1
use_job_queues:                          0
random_album_id:                         starred
use_last_modified_date_when_no_exif_date: 0

### Browser and system
Firefox 115.0.2 Fedora 38
Chrome 115.0.5790.85 Android 13

[stack.txt](https://github.com/LycheeOrg/Lychee/files/12121784/stack.txt)

### LINKED ISSUE #1973: The CSS tweaks to disable auto zoom in/out no longer work
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

In browsing pictures, when there is no mouse movement for a few seconds, the picture will auto zoom in. At mouse movement, it will auto zoom out again. This back-and-forth flickering causes dizziness for me and I want to disable it. The tweaks in #718 do not work for me.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**

1. Follow tweaks in #718 
2. Auto zoom in/out is still there

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

N/A

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

~~~
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Online updates are disabled by configuration
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.id                      → base_albums.id       : NO ACTION
    Foreign key: base_albums.owner_id           → users.id             : NO ACTION
    Foreign key: jobs_history.owner_id          → users.id             : NO ACTION
    Foreign key: photos.album_id                → albums.id            : NO ACTION
    Foreign key: photos.owner_id                → users.id             : NO ACTION
    Foreign key: size_variants.photo_id         → photos.id            : NO ACTION
    Foreign key: sym_links.size_variant_id      → size_variants.id     : NO ACTION
    Foreign key: tag_albums.id                  → base_albums.id       : NO ACTION
~~~

### Browser and system

Microsoft Edge on Windows 11

### LINKED ISSUE #1989: [Enhancement] Add search / filter for 'Move' destination album list
When moving a photo, a list of possible destination albums appears, with 'New Album' and 'Unsorted' at the top.  As this list can get quite long, containing the entire expanded album tree, and seems to be sorted by modification date, albums can sometimes be difficult to find.  It would be nice to be able to type the first few letters of an album name and have the list filter down to possible matches.  

Or if it is simpler (although I think this would be less useful), add a config to allow the list to be sorted alphabetically.  

Starting the list with the folder lists collapsed to top level and allowing the user to expand as they drill down may help the issue as well.

### LINKED ISSUE #2011: [Enhancement] Album Delete Confirmation
Now I'm definitely the idiot here for accidentally clicking the delete for my entire album rather than a photo within it when spamming to delete multiple, but being able to zoop away possible hundreds of photos without an undo operation feels like it should have an extra `ARE YOU REALLY SURE` confirmation modal for albums with contents 🤔

### LINKED ISSUE #2050: When trying to open a password protected shared album, no password prompt is shown
### Detailed description of the problem [REQUIRED]
When I create an album and try to share it as a password protected link, then there is no password prompt when accessing the link and only an empty window is shown. This happens both with the option "hidden" enabled and disabled.
When I remove the password protection it works fine and I can see the photos. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create a new album and upload some photos
2. Click on 'Visibility" , enable public and select password protected.
3. Open the link to the album as a guest
4. Only an empty window appears without a password prompt and no photos are visible.

**Screenshots**
gallery

### Output of the diagnostics  [REQUIRED]

-----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Warning: APP_URL contains a sub-path. This may impact your WebAuthn authentication.
    Info: Latest version of PHP is 8.2
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT

    System Information
    ------------------
    Lychee Version (release):                4.13.0
    DB Version:                              4.13.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.2-1ubuntu2.14
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Berlin
    Max uploaded file size:                  512M
    Max post size:                           512M
    Max execution time:                      30
    MySQL Version:                           10.6.12-MariaDB-0ubuntu0.22.04.1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.0
    Number of foreign key:                   11 found.

    Config Information
    ------------------
    version:                                 041300
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    image_overlay_type:                      none
    default_license:                         reserved
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Lychee v4
    footer_show_copyright:                   1
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             1
    zip64:                                   1
    map_display_public:                      1
    map_provider:                            RRZE
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              0
    location_decoding:                       1
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        all
    album_decoration_orientation:            row
    allow_username_change:                   1
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0
    ffmpeg_path:                             
    ffprobe_path:                            
    layout:                                  justified `

### Browser and system
Tested both Firefox 119.0 (64-Bit) and Chrome 119.0.6045.105
Windows 10 22H2

The server is running on Ubuntu 22.04 LTS with nginx and the lychee was installed with from the latest release zip.

### LINKED ISSUE #2051: Photo Download not work - UnauthorizedException
When I try to download an image of an album, a dialog opens where I can select the image resolution, it doesn't matter which resolution I choose I always get the error message 403. This problem does not occur for the administrator, but only for the users.

Log files of the docker
```
GET /api/Photo::getArchive?photoIDs=_cLHCxKtQReLW64Slc0RdT6W&kind=ORIGINAL
403
```

Log viewer
```
App\Http\Requests\BaseApiRequest::failedAuthorization:114 Insufficient privileges
```

My lychee docker run behind a proxy, i have set in my `.env` file.
`TRUSTED_PROXIES=*`

### LINKED ISSUE #2058: Insufficient privilieges when opening the "Share album" dialog as a regular user
### Detailed description of the problem

As a regular user, I can no longer open the "Share album with users" dialog on an album I own.
I get the message `error - insufficient privileges` in the notification bar on top of the page, and the dialog opens but never list the users. I can see a 413 in the console when opening the developer tools.

The dialog works fine with the "admin" user.

It must be a recent regression because I've had this instance for several years now and it never did this. I'm using Docker and a script that automatically updates the image when a newer is available so I cannot tell exactly when this bug was introduced.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log in as a regular user
1. Go to any of your albums
1. Click on the "Share album with users" in the top right
1. The dialog opens but never lists the users

**Screenshots**

image

### Output of the diagnostics

```



    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Error: APP_URL does not match the current url. This will break WebAuthn authentication. Please update APP_URL to reflect this change.
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
    Warning: git (software) is not available.




    System Information
    --------------
    Lychee Version (git):                    ?? (a87d2e2) -- Could not compare.
    DB Version:                              4.13.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.7
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                UTC
    Max uploaded file size:                  1G
    Max post size:                           1G
    Max execution time:                      3600
    SQLite Version:                          3.40.1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   9 found.




    Config Information
    --------------
    version:                                 041300
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      title
    sorting_albums_order:                    DESC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    fr
    image_overlay_type:                      desc
    default_license:                         reserved
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              Anaël
    landing_title:                           John Smith
    landing_subtitle:                        
    sm_facebook_url:
    sm_flickr_url:                           
    sm_twitter_url:
    sm_instagram_url:
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              Lychee
    footer_show_copyright:                   0
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0
    ffmpeg_path:                             /usr/bin/ffmpeg
    ffprobe_path:                            /usr/bin/ffprobe
    layout:                                  justified
```

The warning messages are quite disturbing since the `APP_URL` is defined in the `.env` file loaded via docker-compose, and the timezone is set at the same place with `PHP_TZ`.
I can confirm those values are present in the container using the `env` command in a shell.

### Browser and system

Firefox 119.0.1

### LINKED ISSUE #2068: Album allow public upload but disallow deletion
As per title, i can't seems to configure this. 
My goal is to create an public album allow anyone/anonymous to upload photos but disallow delete permission.

### PR DESCRIPTION
**Pull request by ildyria**
# LOOKING FOR BETA-TESTERS & FEEDBACK !

## Setup for testing

```sh
# Fetch the new branches, prune the non-existing ones.
git fetch -p

# Switch to the livewire branch
git checkout livewire

# Update the vendor files.
composer install 

# Update the database, there are new constants being used.
php artisan migrate 

# Set up the JS dependencies.
npm install

# Spawn the Vite server for hot reload pages on changes (recommended for development).
npm run dev
# or compile files (recommended for production).
npm run build
```

Then you can access the front-end at the following url:
`https://yourlychee.example.org/livewire`
Or by setting `LIVEWIRE_ENABLED=false` in your `.env`, in this case, the front-end will switch to Livewire completely.

## Fixes

Fixes #12 &mdash; :heavy_check_mark:
Fixes #383 &mdash; :heavy_check_mark: 
Fixes #725 &mdash; :heavy_check_mark:
Fixes #748 &mdash; :heavy_check_mark: (need localization)
Fixes #828 &mdash; :heavy_check_mark:
Closes #845 &mdash; :heavy_check_mark:
Fixes #857 &mdash; :heavy_check_mark:
Fixes #1053 &mdash; :heavy_check_mark: (no more public smart album)
Fixes #1211 &mdash; :heavy_check_mark:
Fixes #1249 &mdash; :heavy_check_mark:
Fixes #1189 &mdash; :heavy_check_mark:
Fixes #1253 &mdash; :heavy_check_mark:
Fixes #1462 &mdash; :heavy_check_mark:
Fixes #1676 &mdash; :heavy_check_mark:
Fixes #1704  &mdash; :heavy_check_mark:
Fixes #1720 &mdash; :heavy_check_mark:
Fixes #1732 &mdash; :heavy_check_mark:
Fixes #1744 &mdash; :heavy_check_mark:
Fixes #1825 &mdash; :heavy_check_mark:
Fixes #1891 &mdash; :heavy_check_mark:
Fixes #1948 &mdash; :heavy_check_mark:
Fixes #1973 &mdash; :heavy_check_mark:
Fixes #1989 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/199  &mdash; :heavy_check_mark:
Fixes #2011 &mdash; :heavy_check_mark:
Fixes #2050 &mdash; :warning: 
Fixes #2051 &mdash; :heavy_check_mark:
Fixes #2058 &mdash; :heavy_check_mark:
Fixes #2068 &mdash; :heavy_check_mark:

Fixes https://github.com/LycheeOrg/Lychee-front/issues/90 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/104 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/166 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/268 &mdash; :heavy_check_mark: (homebrewed css is gone)
Fixes https://github.com/LycheeOrg/Lychee-front/issues/312 &mdash; :heavy_check_mark: (already fixed actually)
Fixes https://github.com/LycheeOrg/Lychee-front/issues/343 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/344 &mdash; :heavy_check_mark:
Fixes https://github.com/LycheeOrg/Lychee-front/issues/373 &mdash; :heavy_check_mark: 

## Major breaking differences

- Public smart album is gone.
- Making a single pictures public is no longer an option.
- Import from server is gone in favor of command line sync

## From @qwerty287 

<details>
<summary><b>Round 1</b></summary>

- [x] Using the "back" button is extremely slow. It takes ~2 sec to load. Opening a new view (e.g. album) is fast though.
- [x] The layout selector is also shown if there are no photos, I think it would better to hide it.
- [x] Dialogs and right-click menus are still extremely slow.
- [x] Navigating left/right on photos is extremely slow, it would be better to navigate directly and show a loading indicator.
- [x] If you open/close the photo sidebar very often, at some point it does not work anymore and is always hidden.
- [x] Opening the photo sidebar the first time moves the photo left first, then nothing happens for a short time, and then the sidebar opens. This should be synchronously.
- [x] Not a big fan of the big buttons for photos, that gives me the feel this is software for children ;)
- [x] When moving photos, the album list loads very long (it's pretty fast when moving albums though).
- [x] Opening the album detail panel does not animate 100% fluently.
- [x] Text inputs in dialogs have a weird border (e.g. login) Screenshot_20231003_123118

Overall it's working well (except the performance as I wrote above...), thanks for all the work!

</details>

**Round 2** 

- [x] When editing a picture and moving your mouse at the left margin, the half of the action icons appear (e.g. star, delete, turn)
- [x] When editing a picture, I'd expect the "back" button to go back to the image view.
- [x] Same as 2 from the album view: open the editor, go back to album view without saving, open a picture -> editor is opened.
- [x] On empty albums, "Nothing to see here" is not horizontally centered.
- [x] I can't open pictures from the map. On click, nothing happens.
- [x] I can't use the "back" button to leave the map.
- [ ] Still, using dialogs and left-click menus is extremely slow for me and take about a second to appear.
- [x] Opening the album details panel still hasn't a fully fluid animation.

### CODE REVIEW

**Comment by ildyria** [comment]
>  Dialogs and right-click menus are still extremely slow.

I will see what I can do to make this more reactive.

>  Navigating left/right on photos is extremely slow, it would be better to navigate directly and show a loading indicator.

That one is a tough one because the data are no longer just on the front-end.
This would pretty much require to re-implement the photo view to be part JS with the photo data stored in the album view.

What do you mean by navigate directly ? as in put a loading indicator while waiting for the next photo page to load ? 

>  Not a big fan of the big buttons for photos, that gives me the feel this is software for children ;)

Well that can still be changed. :)

>  When moving photos, the album list loads very long (it's pretty fast when moving albums though).

That is pretty much the same as in the full JS front-end though. :/

>  Opening the album detail panel does not animate 100% fluently.
 
I am open to other idea of panels sliding or implementations of the visual. :)

**Comment by qwerty287** [comment]
> What do you mean by navigate directly ? as in put a loading indicator while waiting for the next photo page to load ?

Yes, thats what I mean.

**Comment by qwerty287** [comment]
> > Opening the album detail panel does not animate 100% fluently.
> 
> I am open to other idea of panels sliding or implementations of the visual. :)

I don't mean a different animation, the concept is fine.
However, if you close the panel, it starts doing the animation, but it does not finish it properly: At some point, the panel is just hidden, but the animation did not hide it completely, so it looks a bit like a "jump". Something similar happens on opening.

**Comment by ildyria** [comment]
Failing tests are Livewire faults: https://github.com/livewire/livewire/pull/7057

**Comment by Fensterbank** [comment]
> That one is a tough one because the data are no longer just on the front-end.
> This would pretty much require to re-implement the photo view to be part JS with the photo data stored in the album view.

I did not yet test it, but based on the discussion I saw, it should behave like this:

- Keyboard navigation should indeed just be a JS thing, but the URL is changed and the photo url is changed. There is no need for this to be slow or loading a whole new page. So what we should avoid at all costs is doing something like `onKeyPress={() => window.location = "mypage.net/livewire/3434234324" }` which would result in a complete page load for ever image.
- To increase loading times of images, we could always preload the previous few and the next few images, which would result in no visible loading times. (e.g. instagram preloads around the next 6 posts, nobody wants to wait for the next image)

I have no clue about livewire, but I'm very experienced in JavaScript, so maybe (if my time allows it) I could take a look in some parts of the code and support in such cases.

**Comment by ildyria** [comment]
Hi @Fensterbank 
Thank you for your inputs and you are more than welcome to look at the code.

> Keyboard navigation should indeed just be a JS thing, but the URL is changed and the photo url is changed. There is no need for this to be slow or loading a whole new page. So what we should avoid at all costs is doing something like `onKeyPress={() => window.location = "mypage.net/livewire/3434234324" }` which would result in a complete page load for ever image.

In simplified, Livewire works a bit more like GitHub, meaning that it does an AJAX query to the server, which returns an HTML block and does in-place replacement on the page. We do not use `window.location` at all but more `history.pushState()`, allowing us to manipulate the url without reloading the full page.

The current version (4.13) is using pre-loading on the next and previous image, this is not fully an option (yet).
Currently the page change between pictures is indeed slower and that is something that is bothering me quite a bit. I am considering switching back to JS for the photo navigation (based on https://alpinejs.dev ) and keeping the Livewire components for the rest.

If you have 30 minutes to spare, this video is a good quick start on Livewire: https://www.youtube.com/watch?v=fX1aOWWt2nQ
It is the release of the v1, we are now using livewire v3 which is a full rewrite and has some change but is similar in the concept.

More docs on there: https://lycheeorg.github.io/docs/livewire.html

I believe that with combining Alpine, it should be possible to have vueJS-like experience on the Photo side while retaining the component part on the other pages.

> To increase loading times of images, we could always preload the previous few and the next few images, which would result in no visible loading times. (e.g. instagram preloads around the next 6 posts, nobody wants to wait for the next image)

Switching to a vueJS-like experience on the photo view would most likely allow this. :)
More on a comparison between Vue and Alpine [here](https://medium.com/@wearethreebears/a-comparison-of-a-simple-app-in-vue-js-and-alpine-js-2a8c57f8b0e3)

**Comment by ildyria** [comment]
Converting back to draft. Significant refactoring in the photo display for better usability.

**Comment by qwerty287** [comment]
Nice, and thanks for everything!
Some points I found:
1. When editing a picture and moving your mouse at the left margin, the half of the action icons appear (e.g. star, delete, turn)
2. When editing a picture, I'd expect the "back" button to go back to the image view.
3. Same as 2 from the album view: open the editor, go back to album view without saving, open a picture -> editor is opened.
4. On empty albums, "Nothing to see here" is not horizontally centered.
5. I can't open pictures from the map. On click, nothing happens.
6. I can't use the "back" button to leave the map.
7. Still, using dialogs and left-click menus is extremely slow for me and take about a second to appear.
8. Opening the album details panel still hasn't a fully fluid animation.

**Comment by ildyria** [comment]
>  Still, using dialogs and left-click menus is extremely slow for me and take about a second to appear.

- This is due to the round trip with the server (especially when loading albums lists for move). I don't think there is much we can do on that one aside from pre-computing and loading as a var in the front-end but then we lose some of the filtering power. :|

File: lang/de/lychee.php [hunk 1]
```diff
@@ -7,6 +7,7 @@
 	'PASSWORD' => 'Kennwort',
 	'ENTER' => 'Eingabe',
 	'CANCEL' => 'Abbrechen',
+	'CONFIRM' => 'Confirm',
```
Comment (qwerty287) [inline lang/de/lychee.php]:
```suggestion
	'CONFIRM' => 'Bestätigen',
```

File: lang/de/lychee.php [hunk 2]
```diff
@@ -16,6 +17,7 @@
 	'GALLERY' => 'Gallerie',
 
 	'USERS' => 'Benutzer',
+	'PROFILE' => 'Profile',
```
Comment (qwerty287) [inline lang/de/lychee.php]:
```suggestion
	'PROFILE' => 'Profil',
```

File: lang/de/lychee.php [hunk 3]
```diff
@@ -28,6 +30,7 @@
 	'ABOUT_LYCHEE' => 'Über Lychee',
 	'DIAGNOSTICS' => 'Diagnose',
 	'DIAGNOSTICS_GET_SIZE' => 'Speicherplatz-Nutzung abrufen',
+	'JOBS' => 'Show job history',
```
Comment (qwerty287) [inline lang/de/lychee.php]:
```suggestion
	'JOBS' => 'Job-Verlauf anzeigen',
```

File: lang/de/lychee.php [hunk 4]
```diff
@@ -280,6 +283,7 @@
 	'ERROR_MAP_DEACTIVATED' => 'Karten sind unter Einstellungen deaktiviert worden.',
 	'ERROR_SEARCH_DEACTIVATED' => 'Suchfunktion wurde unter Einstellungen deaktiviert.',
 	'SUCCESS' => 'OK',
+	'CHANGE_SUCCESS' => 'Change successful.',
```
Comment (qwerty287) [inline lang/de/lychee.php]:
```suggestion
	'CHANGE_SUCCESS' => 'Änderung erfolgreich.',
```

File: lang/de/lychee.php [hunk 5]
```diff
@@ -398,6 +402,8 @@
 	'LAYOUT_TYPE' => 'Layout des Fotos:',
 	'LAYOUT_SQUARES' => 'Quadratische Miniaturansichten',
 	'LAYOUT_JUSTIFIED' => 'Seitenverhältnis beibehalten, Blocksatz',
+	'LAYOUT_MASONRY' => 'Seitenverhältnis beibehalten, masonry',
+	'LAYOUT_GRID' => 'Seitenverhältnis beibehalten, grid',
```
Comment (qwerty287) [inline lang/de/lychee.php]:
```suggestion
	'LAYOUT_GRID' => 'Seitenverhältnis beibehalten, Gitter',
```

**Comment by qwerty287** [comment]
Most things are working as expected now, thanks!
However, something is very wrong with changing album covers. If I click the menu entry, an image is displayed fullscreen on the screen, but it's not necessarily the one I wanted to make the album cover. Also, the cover hasn't changed.

**Comment by ildyria** [comment]
You mean album header image ?

Yeah that one is not configurable yet. It is randomly selected on the landscape images in the current album (not considering sub albums).

See code here:
https://github.com/LycheeOrg/Lychee/blob/2ed0a9ae44afbfd697f828969940d6c4c3edd73b/app/Livewire/Components/Pages/Gallery/Album.php#L154-L175

**Comment by ildyria** [comment]
> However, something is very wrong with changing album covers.

Fixed, re-rendering was messing up with the display of images layout.

**Review by qwerty287 — APPROVED** [review]

**Comment by tinohager** [comment]
Thanks for the great Christmas present :)

Is there already a docker container that I can test?
I think i have found the right one `lycheeorg/lychee:nightly`

**Comment by ildyria** [comment]
yeah but it is broken at the moment.

**Comment by tinohager** [comment]
i receive the following error after start

> 500
HttpException
Vite manifest not found, please execute `npm run dev`

**Comment by ildyria** [comment]
We are working on fixing that one. The problem is that npm is not run.

**Comment by ildyria** [comment]
@tinohager 
To fix it temporarily you can add in your `.env`:
```
LIVEWIRE_ENABLED=false
```

**Comment by tinohager** [comment]
@ildyria if the sql root password is not correct the error message in the setup wizard might be a little more telling it sounds like lychee is not creating the database automatically instead of not being able to connect to the server

**Comment by ildyria** [comment]
Lychee is not creating the database no. But it will create the tables once given the database.

**Comment by tinohager** [comment]
> @tinohager To fix it temporarily you can add in your `.env`:
> 
> ```
> LIVEWIRE_ENABLED=false
> ```

unfortunately does not work for me

**Comment by ildyria** [comment]
If you are using the docker compose, it should be in your `lychee/conf/.env` file.

**Comment by ildyria** [comment]
We are working on a fix for the vite part: https://github.com/LycheeOrg/Lychee-Docker/pull/168 .

**Comment by tinohager** [comment]
will try again tomorrow to get it running, thank you very much and Merry Christmas

**Comment by ildyria** [comment]
@tinohager 
> `lycheeorg/lychee:nightly`

You will want to use temporarily `lycheeorg/lychee:v5.0.0-beta` before the build of tonight. Last nightly build is currently broken but `lycheeorg/lychee:v5.0.0-beta` is fine.
