### PR TITLE
Fixes #1342

### LINKED ISSUE #1342: Delete Account Fails:
In the administrative interface, I am trying to delete an account and get an error "Server error or API not found"

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log into the administrative account
2. Select Users
3. Click the "Delete" button on the row of the user you want to delete

**Screenshots**

### Output of the diagnostics  [REQUIRED]
```
Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.1

    System Information
    ------------------
    Lychee Version (git):            master (75aa06d) - Data not in Cache
    DB Version:                      4.5.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        America/Los_Angeles
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    SQLite Version:                  3.38.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1808
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                         040501
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Poole
    landing_title:                   John Poole
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Salemdata Photos
    site_copyright_enable:           1
    site_copyright_begin:            2022
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         1
    legacy_id_redirection:           1
```
### Browser and system
Firefox 100.9.2  on Win7

### PR DESCRIPTION
**Pull request by nagmat84**
If a user is going to be deleted, ownership of photos and albums is re-assigned to the current user who requested the deletetion and all shares with this user are deleted.

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
Untested. Code looks sane.

File: app/Models/User.php [hunk 1]
```diff
@@ -108,4 +124,38 @@ public function name(): string
...
+	{
+		$now = Carbon::now();
+		$newOwnerID = AccessControl::id();
+
+		/** @var HasMany[] $ownershipRelations */
+		$ownershipRelations = [$this->photos(), $this->albums()];
+
+		foreach ($ownershipRelations as $relation) {
+			// We must also update the `updated_at` column of the related
+			// models in case clients have cashed these models.
```
Comment (qwerty287) [inline app/Models/User.php]:
```suggestion
			// models in case clients have cached these models.
```

**Review by qwerty287 — APPROVED** [review]
Untested as well, but looks good so far.
