### PR TITLE
Make VideoHandler support optional

### LINKED ISSUE #1438: Video upload fails with error: FFmpeg is disabled by configuration
### Detailed description of the problem
When I try to upload a video to an album, it fails because FFmpeg is not available.

I'm on a shared host, without FFmpeg available.
From my understanding of [FAQ](https://lycheeorg.github.io/docs/faq.html#why-dont-my-videos-have-thumbnails), video upload is possible without FFmpeg but there will be no thumbnails. 

I also tried to upload https://github.com/LycheeOrg/Lychee/blob/master/tests/Samples/gaming.mp4, same results

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any album
2. Click on upload
3. Select a video file to upload
4. At the end of the upload, see error

**Screenshots**
image

### Output of the diagnostics  [REQUIRED]

```


    Diagnostics
    -------
    Warning: /home/xxxxx/Lychee/public/uploads/ has permissions 0775, but should have 2775
    Warning: /home/xxxxx/Lychee/public/uploads/thumb2x has permissions 0775, but should have 2775
    Warning: /home/xxxxx/Lychee/public/uploads/thumb2x/e3 has permissions 0775, but should have 2775
    Warning: /home/xxxxx/Lychee/public/uploads/thumb2x/e3/7c has permissions 0775, but should have 2775
    Warning: /home/xxxxx/Lychee/public/uploads/thumb2x/e3/ea has permissions 0775, but should have 2775
    Warning: 7586 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.1
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

    System Information
    --------------
    Lychee Version (git):            master (1a31f3c) -- 3 commits behind master cd394af (1 days ago)
    DB Version:                      4.5.2
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.0.21
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        UTC
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.5.16-MariaDB-cll-lve
    
    exec() Available:                yes
    Imagick Available:               1
    Imagick Enabled:                 1
    Imagick Version:                 1808
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040502
    check_for_updates:               0
    sorting_photos_col:              taken_at
    sorting_photos_order:            ASC
    sorting_albums_col:              title
    sorting_albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            fr
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   xxxx
    landing_title:                   
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              
    site_title:                      xxxx
    site_copyright_enable:           1
    site_copyright_begin:            2022
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         2
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1

```

### Browser and system
Firefox 103 on Windows 10

### PR DESCRIPTION
**Pull request by kamil4**
Fixes #1438 

This is a semi-draft PR:
* I fixed only the case of uploading a regular video file but I see that `VideoHandler` is also used for Google Motion Pictures. I left the latter as-is as I don't understand how that part works and what (if anything) we can do about it.
* By catching the exception, we prevent a message about missing FFmpeg from being generated in the logs. It seems like it would be useful to have it there though under these circumstances, but I wasn't sure what the "approved" way of doing it is these days. @nagmat84?

### CODE REVIEW

File: app/Actions/Photo/Strategies/AddStandaloneStrategy.php [hunk 1]
```diff
@@ -94,10 +94,16 @@ public function do(): Photo
...
-				$this->sourceImage = $videoHandler->extractFrame($position);
+				// We try to extract a video frame using FFmpeg; however,
+				// that one's optional, so we need to be able to recover.
+				try {
+					$videoHandler = new VideoHandler();
+					$videoHandler->load($this->sourceFile);
+					$position = is_numeric($this->photo->aperture) ? floatval($this->photo->aperture) / 2 : 0.0;
+					$this->sourceImage = $videoHandler->extractFrame($position);
+				} catch (\Throwable) {
+					$this->sourceImage = null;
```
Comment (nagmat84) [inline app/Actions/Photo/Strategies/AddStandaloneStrategy.php]: You can use `Handler::reportSafely($e)` to log the exception as if it would bubble up the call graph without actually throwing it.

**Review by nagmat84 — APPROVED** [review]
Looks good to me with respect to the reported issue.

Maybe we should wrap the whole if-then-else-branch into the try-block? This would also allow to upload regular photos which are too broken to generate thumbs but maybe still viewable by a browser. But I don't know if that case really exist.

We should also have a test which tries to upload a video with FFMpeg disabled and which asserts that the upload still succeeds, that no thumbnail has been generated and a log entry has been made. But I can also write the test tomorrow independently of this PR.

**Comment by nagmat84** [comment]
With respect to GMP. In

https://github.com/LycheeOrg/Lychee/blob/f39be7a803ea1e30230e30fae0dca246c5f3a8c1/app/Actions/Photo/Strategies/AddStandaloneStrategy.php#L113-L124

the lines 118-121, i.e. the body of the if-branch could be wrapped into a try-block as well and then the catch-block needs to set `$tmpVideoFile` to `null` exactly as it is done in the else-branch as if it was no GMP image at all. Then we would be fine for that, too.

I would do it myself, but here it is 00:30am and I am not in front of a PC.

**Comment by kamil4** [comment]
@nagmat84: I made some changes along the lines you suggested. Logging works now. An existing testcase (`testBrokenGoogleMotionPhotoUpload`) triggers now though -- I decided to leave it up to you to figure out what to do about it.

I also added a testcase for uploading a video file without ffmpeg (or exiftool for that matter, to ensure no video metadata). It works, though maybe it's not as tight as you would like (I don't believe it actually checks if there are no thumbnails?).

File: tests/Feature/PhotosAddHandlerTestAbstract.php [hunk 2]
```diff
@@ -344,4 +345,37 @@ public function testTrickyVideoUpload(): void
...
+			'album_id' => null,
+			'title' => 'gaming',
+			'type' => TestCase::MIME_TYPE_VID_MP4,
+			'size_variants' => [
+				'original' => [
+					'width' => 0,
+					'height' => 0,
+					'filesize' => 66781184,
+				],
+			],
```
Comment (nagmat84) [inline tests/Feature/PhotosAddHandlerTestAbstract.php]: Maybe we should also assert that the other size variants are really `null`?


```suggestion
			'size_variants' => [
				'original' => [
					'width' => 0,
					'height' => 0,
					'filesize' => 66781184,
				],
				'medium2x' => null,
				'medium' => null,
				'small2x' => null,
				'small' => null,
				'thumb2x' => null,
				'thumb' => null,
			],
```

`FFMpeg` is always available to the the test suite. We only mimick a missing FFMpeg by disabling it in the configuration. If that fails (for some unknonwn reason) we might accidentally not test what we want, because FFmeg will be called without complain.

File: tests/Feature/PhotosAddHandlerTestAbstract.php [hunk 3]
```diff
@@ -344,4 +345,37 @@ public function testTrickyVideoUpload(): void
...
+		]);
+
+		Configs::set(self::CONFIG_HAS_FFMPEG, $hasFFMpeg);
+		Configs::set(self::CONFIG_HAS_EXIF_TOOL, $hasExifTool);
+	}
```
Comment (nagmat84) [inline tests/Feature/PhotosAddHandlerTestAbstract.php:430]: Maybe we should additionally assert that the expected error message, e.g. "FFMpeg is disabled by configuration", can be found in the logs?

To this end we could clear the log table at the beginning of the test with `DB::tables('logs)->delete()`. At the end of the test we do a count-query and assert that we found an entry, e.g. something like

```php
$numErrorMsg = DB::tables('logs)->where('message', 'like', '%FFMpeg is disabled by configuration%')->count();
self::assertEquals(1, $numErrorMsg);
```

But maybe this would make the test too strict? I am unsure.

**Review by nagmat84 — COMMENTED** [review]
Just some ideas.

File: tests/Feature/PhotosAddHandlerTestAbstract.php (hunk 2 above)
Comment (kamil4) [reply tests/Feature/PhotosAddHandlerTestAbstract.php]: Yeah, I agree that merely disabling it in the configuration is imperfect, but realistically that's probably all we can do in the testsuite?

File: tests/Feature/PhotosAddHandlerTestAbstract.php (hunk 3 above)
Comment (kamil4) [reply tests/Feature/PhotosAddHandlerTestAbstract.php:430]: I wouldn't do it myself (testing for log messages seems a little overly prescriptive to me) but feel free to add a commit to that effect to this PR if you want.

File: tests/Feature/PhotosAddHandlerTestAbstract.php (hunk 2 above)
Comment (nagmat84) [reply tests/Feature/PhotosAddHandlerTestAbstract.php]: That's is why I considered checking the logs. This way, we can be sure that the exception has been triggered inside the code.
