### PR TITLE
Massive refactoring of backend: v4.2.0 + fixes #843 #846 #858

### LINKED ISSUE #843: Trying to get property 'password' of non-object
### Detailed description of the problem [REQUIRED]
I am getting 500 intenal server error while update from 4.0.8 to 4.1.0

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
as mentioned here [Update manually](https://lycheeorg.github.io/docs/update.html#update-manually )
1. Download the newest Version
2. Replace all existing files, excluding uploads/ and dist/user.css
3. when i accessed page i got ```500 | Server Error```

this is error log

```
[2020-12-31 06:39:15] production.ERROR: Cannot call abstract method App\Locale\LangInterface::code() {"exception":"[object] (Error(code: 0): Cannot call abstract method App\\Locale\\LangInterface::code() at /home/soft/public_html/lych391/app/Locale/Lang.php:48)
[stacktrace]
#0 app/Models/Configs.php(141): App\\Locale\\Lang::get_lang_available()
#1 app/Models/Configs.php(172): App\\Models\\Configs::get()
#2 app/Metadata/GitRequest.php(19): App\\Models\\Configs::get_value('update_check_ev...', '3')
#3 [internal function]: App\\Metadata\\GitRequest->__construct()
#4 vendor/laravel/framework/src/Illuminate/Container/Container.php(870): ReflectionClass->newInstanceArgs(Array)
#5 vendor/laravel/framework/src/Illuminate/Container/Container.php(279): Illuminate\\Container\\Container->build('App\\\\Metadata\\\\Gi...')
#6 vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#7 vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#8 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\Metadata\\\\Gi...', Array, true)
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\Metadata\\\\Gi...', Array)
#10 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\Metadata\\\\Gi...', Array)
#11 vendor/laravel/framework/src/Illuminate/Container/Container.php(980): Illuminate\\Foundation\\Application->make('App\\\\Metadata\\\\Gi...')
#12 vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#13 vendor/laravel/framework/src/Illuminate/Container/Container.php(861): Illuminate\\Container\\Container->resolveDependencies(Array)
#14 vendor/laravel/framework/src/Illuminate/Container/Container.php(279): Illuminate\\Container\\Container->build('App\\\\Metadata\\\\Gi...')
#15 vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#16 vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\Metadata\\\\Gi...', Array, true)
#18 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\Metadata\\\\Gi...', Array)
#19 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\Metadata\\\\Gi...', Array)
#20 vendor/laravel/framework/src/Illuminate/Container/Container.php(980): Illuminate\\Foundation\\Application->make('App\\\\Metadata\\\\Gi...')
#21 vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#22 vendor/laravel/framework/src/Illuminate/Container/Container.php(861): Illuminate\\Container\\Container->resolveDependencies(Array)
#23 vendor/laravel/framework/src/Illuminate/Container/Container.php(279): Illuminate\\Container\\Container->build('App\\\\Metadata\\\\Ly...')
#24 vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#25 vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#26 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\Metadata\\\\Ly...', Array, true)
#27 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\Metadata\\\\Ly...', Array)
#28 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\Metadata\\\\Ly...', Array)
#29 vendor/laravel/framework/src/Illuminate/Container/Container.php(980): Illuminate\\Foundation\\Application->make('App\\\\Metadata\\\\Ly...')
#30 vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#31 vendor/laravel/framework/src/Illuminate/Container/Container.php(861): Illuminate\\Container\\Container->resolveDependencies(Array)
#32 vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#33 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array, true)
#34 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Contro...', Array)
#35 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#36 vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#37 vendor/laravel/framework/src/Illuminate/Routing/Route.php(989): Illuminate\\Routing\\Route->getController()
#38 vendor/laravel/framework/src/Illuminate/Routing/Route.php(950): Illuminate\\Routing\\Route->controllerMiddleware()
#39 vendor/laravel/framework/src/Illuminate/Routing/Router.php(709): Illuminate\\Routing\\Route->gatherMiddleware()
#40 vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#41 vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#61 public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#62 {main}
"} 
```
then i tried again with different step 
1. i didn't replaced all existing files, i deleted all files excluding uploads/ ,dist/user.css and .env and uploaded new files.
2. when i accessed page i got ```500 | Server Error```

but error was different

```
[2020-12-31 07:13:36] production.ERROR: Trying to get property 'password' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'password' of non-object at /home/soft/public_html/lych431/app/ModelFunctions/SessionFunctions.php:116)
[stacktrace]
#0 app/ModelFunctions/SessionFunctions.php(116): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/soft/publ...', 116, Array)
#1 app/Http/Controllers/Administration/UpdateController.php(103): App\\ModelFunctions\\SessionFunctions->noLogin()
#2 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Administration\\UpdateController->force(Object(Illuminate\\Http\\Request))
#3 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('force', Array)
#4 vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Administration\\UpdateController), 'force')
#5 vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#6 vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#7 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 app/Http/Middleware/DBExists.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DBExists->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 app/Http/Middleware/VerifyCsrfToken.php(60): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#31 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 
[2020-12-31 07:14:42] production.ERROR: Trying to get property 'password' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'password' of non-object at app/ModelFunctions/SessionFunctions.php:116)
[stacktrace]
#0 app/ModelFunctions/SessionFunctions.php(116): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/soft/publ...', 116, Array)
#1 app/Http/Controllers/Administration/UpdateController.php(103): App\\ModelFunctions\\SessionFunctions->noLogin()
#2 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Administration\\UpdateController->force(Object(Illuminate\\Http\\Request))
#3 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('force', Array)
#4 vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Administration\\UpdateController), 'force')
#5 vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#6 vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#7 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 app/Http/Middleware/DBExists.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DBExists->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 app/Http/Middleware/VerifyCsrfToken.php(60): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#31 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 
[2020-12-31 07:14:45] production.ERROR: Trying to get property 'password' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'password' of non-object at app/ModelFunctions/SessionFunctions.php:116)
[stacktrace]
#0 app/ModelFunctions/SessionFunctions.php(116): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/home/soft/publ...', 116, Array)
#1 app/Http/Controllers/Administration/UpdateController.php(103): App\\ModelFunctions\\SessionFunctions->noLogin()
#2 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Administration\\UpdateController->force(Object(Illuminate\\Http\\Request))
#3 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('force', Array)
#4 vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Administration\\UpdateController), 'force')
#5 vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#6 vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#7 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 app/Http/Middleware/DBExists.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DBExists->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 app/Http/Middleware/VerifyCsrfToken.php(60): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#31 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 

```

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

in first case

```
In Lang.php line 48:
                                                                
  Cannot call abstract method App\Locale\LangInterface::code()  
                                                                
```

in second case

```



Diagnostics
-----------
Error: Database is behind file versions. Please apply the migration.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
Warning: Dropbox import not working. dropbox_key is empty.

System Information
------------------
Lychee Version (release):        4.1.0
DB Version:                      4.0.8

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          20M
Max post size:                   8M
MySQL Version:                   5.7.29

Imagick:                         -
Imagick Active:                  1
Imagick Version:                 -
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040008
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0

```

### Browser and system

Broswer : Firefox developer 85.0b4 (64-bit)
system : Linux webuzo.web 2.6.32-754.el6.x86_64 ( Centos 6 )

### PR DESCRIPTION
**Pull request by ildyria**
- start using Livewire for the front-end, for now accessible at `example.com/livewire` if enabled via `LIVEWIRE_ENABLED` in `.env`
- use Facade `AccessControl` to access `Session` information (basically home-brewed `Auth`)
- use Facade `Lang` to access `Lang` information (Easier to use through the blade template)
- heavy refactoring of the core, introducing more granularity:
  - Interfaces are Contracts
  - Group Factories
  - use `trait` on album for smaller dedicated operations
  - add Nested Set theory to Album to allow access to all descendants  

Will probably be a bump to version 4.2.0 to be honest given the amount of change applied.

Additionally fixes #843

### CODE REVIEW

File: app/Actions/Album/Archive.php [hunk 1]
```diff
@@ -0,0 +1,208 @@
...
+			// add a file named 'some_image.jpg' from a local file 'path/to/image.jpg'
+			$zip->addFileFromPath($dir_name . '/' . $file, $url);
+		} // foreach ($photos)
+
+		// Recursively compress subalbums
+		if (!$album->smart) {
+			$subDirs = [];
+			foreach ($album->children as $subAlbum) {
+				if ($this->readAccessFunctions->album($subAlbum, true) === 1) {
+					$subSql = Photo::set_order(Photo::where('album_id', '=', $subAlbum->id));
```
Comment (kamil4) [inline app/Actions/Album/Archive.php]: Why are we invoking `set_order` here? We even comment earlier in this file (lines 140-141) that we don't care about order, and indeed we don't seem to be setting any for top-level albums, so why do it for subalbums? I have no strong feeling about it other than the fact that it seems inconsistent; we should either always set order or never...

File: app/Actions/Album/Delete.php [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+		$albums = Album::whereIn('id', explode(',', $albumIDs))->get();
+
+		/**
+		 * @var Album
+		 */
+		$parentAlbum = null;
+		foreach ($albums as $album) {
+			$no_error &= $album->predelete();
+			if ($parentAlbum !== null && $album->parent_id !== null) {
```
Comment (kamil4) [inline app/Actions/Album/Delete.php]: Shouldn't this be `$parentAlbum === null`?

I can't help but wonder how well tested this code path is :wink:.

File: app/Actions/Album/Merge.php [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+	/**
+	 * @param string $albumID
+	 *
+	 * @return bool
+	 */
+	public function do(string $albumID, array $albumIDs): bool
+	{
+		$album_master = $this->albumFactory->make($albumID);
+		if ($album_master->is_smart()) {
+			Logs::error(__METHOD__, __LINE__, 'Merge possible on smart albums');
```
Comment (kamil4) [inline app/Actions/Album/Merge.php]: Shouldn't that be `Merge not possible`?

File: app/Actions/Album/Move.php [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+	public function do(string $albumID, array $albumIDs): bool
+	{
+		$album_master = null;
+		// $albumID = 0 is root
+		// ! check type
+		if ($albumID != 0) {
+			$album_master = $this->albumFactory->make($albumID);
+
+			if ($album_master->is_smart()) {
+				Logs::error(__METHOD__, __LINE__, 'Move possible on smart albums');
```
Comment (kamil4) [inline app/Actions/Album/Move.php]: `Move not possible`?

**Review by kamil4 — COMMENTED** [review]
I only looked through the first ten files so far (up to `app/Actions/Album/Move.php`). I may have some additional comments about that part after I've seen more of the code and after I've ran some tests.

File: app/Actions/Album/Delete.php (hunk 2 above)
Comment (ildyria) [reply app/Actions/Album/Delete.php:38]: oupsie

Comment (ildyria) [reply app/Actions/Album/Delete.php]: oupsie.

File: app/Actions/Album/Archive.php (hunk 1 above)
Comment (ildyria) [reply app/Actions/Album/Archive.php]: To be honest, that part is legacy code. :)

File: app/Actions/Album/Merge.php (hunk 3 above)
Comment (ildyria) [reply app/Actions/Album/Merge.php]: oupsie

File: app/Actions/Album/Move.php (hunk 4 above)
Comment (ildyria) [reply app/Actions/Album/Move.php]: oupsie

File: app/Actions/Album/SetPublic.php [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+		if (!$album->save()) {
+			return false;
+		}
+
+		// Reset permissions for photos
+		if ($album->public == 1) {
+			$album->photos()->update(['public' => '0']);
+		}
+
+		if (isset($values['password'])) {
```
Comment (kamil4) [inline app/Actions/Album/SetPublic.php]: Any idea why this code is below `$album->save()` (line 28)? The way it is, `$album->save()` has to be invoked twice.

File: app/Actions/Album/Setters.php [hunk 6]
```diff
@@ -0,0 +1,15 @@
+<?php
+
+namespace App\Actions\Album;
+
+use App\Models\Album;
+
+class Setters extends Action
```
Comment (kamil4) [inline app/Actions/Album/Setters.php:13]: It is not clear to me what the difference is between `Setters` and `Setter` and when one should use which.  In particular, why does `SetLicense` extend `Setter` but `SetTitle` `Setters`?  Maybe add some explanation in the comments?

File: app/Actions/Album/Unlock.php [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+namespace App\Actions\Album;
+
+use AccessControl;
+use App\Models\Album;
+use Illuminate\Support\Facades\Hash;
+
+class Unlock extends Action
+{
+	/**
+	 * Provided an password and an album, check if the album can be
```
Comment (kamil4) [inline app/Actions/Album/Unlock.php]: **a** password

File: app/Actions/Album/Unlock.php [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+
+				return true;
+			}
+		}
+
+		return false;
+	}
+
+	/**
+	 * Provided an password, add all the albums that the password unlocks.
```
Comment (kamil4) [inline app/Actions/Album/Unlock.php]: **a** password

File: app/Actions/Album/Delete.php [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+		}
+		// We fix the tree :)
+		if (Album::isBroken()) {
+			Album::fixTree();
+		}
+
+		/**
+		 *  We can just do that at the end, because $parentAlbum will
+		 * be the same for all the albums in the case of a sub album.
+		 */
```
Comment (kamil4) [inline app/Actions/Album/Delete.php]: The code you replaced did not make this assumption. I know, because I deliberately coded it to be more generic than what the front end needed, to make it more robust :smiley:.

Now, I get the argument that if the front end does not need it, then why go the extra mile on the server? But this should be explicitly documented as a limitation of this server-side implementation, and maybe even tests should be added to ensure that all the passed albums do indeed share a parent?

File: app/Actions/Album/Move.php [hunk 10]
```diff
@@ -0,0 +1,59 @@
...
+		$no_error = true;
+		$oldParentID = null;
+
+		foreach ($albums as $album) {
+			$oldParentID = $album->parent_id;
+			$album->parent_id = $albumID;
+			$no_error &= $album->save();
+		}
+
+		if ($no_error && $oldParentID !== null) {
```
Comment (kamil4) [inline app/Actions/Album/Move.php]: As in `Delete` earlier, you are now making an assumption here that all the albums will have the same parent. This should be explicitly documented in the comments and maybe tests should be added to ensure that that's the case.

File: app/Actions/Album/UpdateTakestamps.php [hunk 11]
```diff
@@ -0,0 +1,31 @@
...
+		$album->min_takestamp = $album->get_all_photos()->whereNotNull('takestamp')->min('takestamp');
+		$album->max_takestamp = $album->get_all_photos()->whereNotNull('takestamp')->max('takestamp');
+	}
+
+	public function singleAndSave(Album &$album): bool
+	{
+		$this->single($album);
+
+		return $album->save();
+	}
```
Comment (kamil4) [inline app/Actions/Album/UpdateTakestamps.php]: OK, now that I've seen how this code is actually used, I have concerns.

I'll get it off my chest first that I think the old code that handled the takestamp updates had a number of advantages over this new one. I realize that I'm biased in that view, given that I'm the one who wrote the old version :wink:. Yes, that code was fairly complex and could be described as fragile, but that was because it was optimized to perform the minimum necessary amount of database queries and updates.

The new code, instead, takes a brute-force approach of always performing the full min/max queries over the whole album contents, including that of the subalbums. Yes, the new album tree structure allows that to be a single query, but that could be a *very large* query for big, nested albums with possibly thousands of photos inside. Why do it if we can figure out with a few lines of code that it is not necessary at all? E.g., if the album's `min_takestamp` is from 2010 and `max_takestamp` is from 2020, adding or removing a photo taken in 2015 doesn't require any updates; the old code handled such cases gracefully, whereas the new one needlessly recalculates everything. The old code also took advantage of the already calculated takestamp values of the subalbums to avoid rescanning their contents.

And actually, it gets worse. The `singleAndSave` method above is only correct when it's invoked from the `all` method below. Invoking it just once, for a single album, as is done from, e.g., `Delete`, can result in an inconsistent database. Because it's not enough to update the current album; you also may need to update **all** of its ancestors. E.g., if I have album `A` with a subalbum `B` and I add a photo to `B`, this new code will update the takestamps of `B` only, leaving stale values in `A`. The updates need to be percolated up the album tree. The old code did that recursively and its optimized structure allowed it to stop as soon as it was clear that there would be no more updates. I guess the new code will have to do it unconditionally at each level all the way to the root? What was a brute-force approach already will turn into brute-force-squared... :disappointed:

File: app/Actions/Albums/Extensions/PublicIds.php [hunk 12]
```diff
@@ -0,0 +1,138 @@
...
+		$this->initPublicAlbumId();
+	}
+
+	/*------------------------------------------------------------------------------- */
+	/**
+	 * Initialize.
+	 */
+
+	/**
+	 * Build a query that remove all non public albums
```
Comment (kamil4) [inline app/Actions/Albums/Extensions/PublicIds.php]: remove**s**

File: app/Actions/Albums/Extensions/PublicIds.php [hunk 13]
```diff
@@ -0,0 +1,138 @@
...
+use Illuminate\Database\Eloquent\Builder;
+use Illuminate\Support\Collection as BaseCollection;
+use Illuminate\Support\Facades\DB;
+
+class PublicIds
+{
+	/** @var BaseCollection */
+	private $white_list = null;
+	/** @var BaseCollection */
+	private $black_list = null;
```
Comment (kamil4) [inline app/Actions/Albums/Extensions/PublicIds.php]: These terms are not considered politically-correct in the US anymore :smiley:.

**Review by kamil4 — COMMENTED** [review]
OK, here's the next batch. Still long way to go...

File: app/Actions/Albums/Prepare.php [hunk 14]
```diff
@@ -0,0 +1,53 @@
...
+	 * Given a list of albums, generate an array to be returned.
+	 *
+	 * @param Collection[Album] $albums
+	 *
+	 * @return array
+	 */
+	public function do(BaseCollection $albums)
+	{
+		$return = [];
+		foreach ($albums->keys() as $key) {
```
Comment (kamil4) [inline app/Actions/Albums/Prepare.php]: Any reason why we're iterating over keys rather than albums themselves here?

File: app/Actions/Photo/Create.php [hunk 15]
```diff
@@ -0,0 +1,136 @@
...
+		// Set paths
+		$this->tmp_name = $file['tmp_name'];
+		$this->photo_Url = md5(microtime()) . $this->extension;
+		$this->path_prefix = ($this->kind != 'raw') ? 'big/' : 'raw/';
+		$this->path = Storage::path($this->path_prefix . $this->photo_Url);
+
+		// Calculate checksum
+		$this->photo->checksum = $this->checksum($this->tmp_name);
+		$duplicate = $this->get_duplicate($this->photo->checksum);
+		$exists = $duplicate !== null;
```
Comment (kamil4) [inline app/Actions/Photo/Create.php]: Maybe surround `$duplicate !== null` with parentheses?

File: app/Actions/Photo/Create.php [hunk 16]
```diff
@@ -0,0 +1,136 @@
...
+
+		// In case it's a live photo and we've uploaded the video
+		if ($skip_db_entry_creation === true) {
+			$res = $this->livePhotoPartner->id;
+		} else {
+			$res = $this->save($this->photo);
+			$this->updateParentAlbum();
+		}
+
+		if ($delete_imported && !is_uploaded_file($this->tmp_name) && ($exists || Configs::get_value('import_via_symlink', '0') !== '1')) {
```
Comment (kamil4) [inline app/Actions/Photo/Create.php:129]: This line is kind-of ugly. It made sense when I wrote it, given the spaghetti code that we had, but after your refactoring, it looks jarring. Can't it be hidden away within an additional method in a strategy?

File: app/Actions/Photo/Extensions/ImageEditing.php [hunk 17]
```diff
@@ -0,0 +1,176 @@
...
+	/**
+	 * @param Photo $photo
+	 *
+	 * @return string Path of the jpg file
+	 */
+	public function createJpgFromRaw(Photo $photo): string
+	{
+		// we need imagick to do the job
+		if (!Configs::hasImagick()) {
+			Logs::notice(__METHOD__, __LINE__, 'Saving JPG of raw file to failed: Imagick not installed.');
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/ImageEditing.php]: Remove `to`?

File: app/Actions/Photo/Extensions/ImageEditing.php [hunk 18]
```diff
@@ -0,0 +1,176 @@
...
+			Logs::notice(__METHOD__, __LINE__, 'Filetype ' . $ext . ' not supported by Imagick.');
+
+			return '';
+		}
+
+		$tmp_file = tempnam(sys_get_temp_dir(), 'lychee') . '.jpeg';
+		Logs::notice(__METHOD__, __LINE__, 'Saving JPG of raw file to ' . $tmp_file);
+
+		$resWidth = $resHeight = 0;
+		$resWidth = $resHeight = 0;
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/ImageEditing.php]: Duplicate line...

File: app/Actions/Photo/Extensions/ImageEditing.php [hunk 19]
```diff
@@ -0,0 +1,176 @@
...
+		// Both image sizes of the same type are stored in the same folder
+		// ie: medium and medium2x both belong in LYCHEE_UPLOADS_MEDIUM
+		$pathType = strtoupper($type);
+		if (($split = strpos($pathType, '2')) !== false) {
+			$pathType = substr($pathType, 0, $split);
+		}
+
+		$uploadFolder = Storage::path(strtolower($pathType) . '/');
+		if (Helpers::hasPermissions($uploadFolder) === false) {
+			Logs::notice(__METHOD__, __LINE__, 'Skipped creation of medium-photo, because ' . $uploadFolder . ' is missing or not readable and writable.');
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/ImageEditing.php]: This is a generic code so it shouldn't mention `medium`. Either simply remove `medium` or replace with `$type`?

**Review by kamil4 — COMMENTED** [review]
Next batch...

File: app/Actions/Album/SetPublic.php (hunk 5 above)
Comment (ildyria) [reply app/Actions/Album/SetPublic.php]: Fixed.

File: app/Actions/Album/Setters.php (hunk 6 above)
Comment (ildyria) [reply app/Actions/Album/Setters.php:13]: fixed.

File: app/Actions/Album/Unlock.php (hunk 8 above)
Comment (ildyria) [reply app/Actions/Album/Unlock.php]: fixed.

File: app/Actions/Album/Unlock.php (hunk 7 above)
Comment (ildyria) [reply app/Actions/Album/Unlock.php]: fixed.

File: app/Actions/Albums/Extensions/PublicIds.php (hunk 12 above)
Comment (ildyria) [reply app/Actions/Albums/Extensions/PublicIds.php]: fixed.

File: app/Actions/Albums/Extensions/PublicIds.php (hunk 13 above)
Comment (ildyria) [reply app/Actions/Albums/Extensions/PublicIds.php]: Hahahaha I knew this would raise an issue. :laughing:

File: app/Actions/Albums/Prepare.php (hunk 14 above)
Comment (ildyria) [reply app/Actions/Albums/Prepare.php]: Fixed.

File: app/Actions/Album/Delete.php (hunk 9 above)
Comment (ildyria) [reply app/Actions/Album/Delete.php]: I updated the code with respect to your comment. I will sadly have you to go through it again. :sweat_smile:

File: app/Actions/Album/Move.php (hunk 10 above)
Comment (ildyria) [reply app/Actions/Album/Move.php]: I updated the code with respect to your comment. I will sadly have you to go through it again. :sweat_smile:

File: app/Actions/Album/UpdateTakestamps.php (hunk 11 above)
Comment (ildyria) [reply app/Actions/Album/UpdateTakestamps.php]: I updated the code with respect to your comment. I will sadly have you to go through it again. :sweat_smile:

File: app/Actions/Photo/Create.php (hunk 15 above)
Comment (ildyria) [reply app/Actions/Photo/Create.php]: :+1:

File: app/Actions/Photo/Extensions/ImageEditing.php (hunk 17 above)
Comment (ildyria) [reply app/Actions/Photo/Extensions/ImageEditing.php]: fixed.

File: app/Actions/Photo/Extensions/ImageEditing.php (hunk 19 above)
Comment (ildyria) [reply app/Actions/Photo/Extensions/ImageEditing.php]: fixed.

**Comment by ildyria** [comment]
Bug Found: When you query to get all the albums for a "move" operation, you only get the top visible ones and not the tree. This needs to be fixed.

File: app/Actions/Albums/Extensions/PublicIds.php (hunk 13 above)
Comment (ildyria) [reply app/Actions/Albums/Extensions/PublicIds.php]: Fixed.

File: app/Actions/Photo/Create.php (hunk 16 above)
Comment (ildyria) [reply app/Actions/Photo/Create.php:129]: Yeah I know. Left for later to be honest. :disappointed:

**Comment by kamil4** [comment]
> Bug Found: When you query to get all the albums for a "move" operation, you only get the top visible ones and not the tree. This needs to be fixed.

Whoa! I haven't realized until now that you changed `Albums::get` to only return the top-level albums. And nothing else broke because of that? :smiley: I would expect issues such as #828 to become common (but they should be non-fatal, so...).

File: app/Actions/Album/Merge.php [hunk 20]
```diff
@@ -0,0 +1,65 @@
...
+		// ! we have to do it via Model::delete() in order to not break the tree
+		$albums = Album::whereIn('id', $albumIDs);
+		foreach ($albums as $album) {
+			$album->delete();
+		}
+
+		if (Album::isBroken()) {
+			$errors = Album::countErrors();
+			$sum = $errors['oddness'] + $errors['duplicates'] + $errors['wrong_parent'] + $errors['missing_parent'];
+			Logs::warning(__FUNCTION__, __LINE__, 'Tree is broken with ' . $sum . ' errors.');
```
Comment (kamil4) [inline app/Actions/Album/Merge.php:50]: Are these messages here deliberately or are they leftovers from a debug session?

**Comment by ildyria** [comment]
> And nothing else broke because of that?

That's what we call robust code ;p

File: app/Actions/Album/Merge.php [hunk 21]
```diff
@@ -0,0 +1,65 @@
...
+		foreach ($albums as $album) {
+			$album->parent_id = $album_master->id;
+			$album->save();
+		}
+
+		// now we delete the albums
+		// ! we have to do it via Model::delete() in order to not break the tree
+		$albums = Album::whereIn('id', $albumIDs);
+		foreach ($albums as $album) {
+			$album->delete();
```
Comment (kamil4) [inline app/Actions/Album/Merge.php:44]: So I see the code below that does the takestamps update for the destination album. What about updating the sources though (the parents of `$albumIDs`)? Does that magically get triggered by `$album->delete()` here or is that code missing? (With all these abstractions I no longer know what gets invoked when :smiley:)

File: app/Actions/Album/Move.php [hunk 22]
```diff
@@ -0,0 +1,87 @@
...
+			$no_error &= $album->save();
+		}
+		// Tree should be updated by itself here.
+
+		$sql = Album::select('_lft', '_rgt', 'min_takestamp', 'max_takestamp')
+			->where(DB::raw('0')); // initialize with 0.
+
+		$oldParentID->eachSpread(function ($id, $min, $max) use (&$sql) {
+			$sql = $sql->orWhere(fn ($q) => $q
+				// this smartly select all the ancestors
```
Comment (kamil4) [inline app/Actions/Album/Move.php]: Inaccurate comment (copy-paste?).

File: app/Actions/Album/Move.php [hunk 23]
```diff
@@ -0,0 +1,87 @@
...
+				// this smartly select only the one that need to be updated:
+				// min is greater OR EQUAL than the min of the deleted album
+				// max is smaller OR EQUAL than the max of the deleted album
+				//? the EQUAL is the condition we are interested in, bigger/smaller is just for safety
+				->where(fn ($q) => $q
+					->where('min_takestamp', '>=', $min)
+					->orWhere('max_takestamp', '<=', $max)));
+		});
+		$ancestorsList = $sql->get()->pluck(['_lft', '_rgt', 'min_takestamp', 'max_takestamp']);
+		DebugBar::notice($ancestorsList);
```
Comment (kamil4) [inline app/Actions/Album/Move.php]: Leftover debugging code...

File: app/Actions/Album/UpdateTakestamps.php [hunk 24]
```diff
@@ -0,0 +1,41 @@
...
+
+	public function ancestors(Album $album)
+	{
+		if ($album->min_takestamp != null && $album->max_takestamp != null) {
+			$album->ancestors()
+				->where('min_takestamp', '>=', $album->min_takestamp)
+				->orWhere('max_takestamp', '<=', $album->max_takestamp)
+				->update(['max_takestamp' => $album->max_takestamp, 'min_takestamp' => $album->min_takestamp]);
```
Comment (kamil4) [inline app/Actions/Album/UpdateTakestamps.php]: I suspect this might be wrong, in that it will always update both `min_takestamp` and `max_takestamp`, even when only one of them should be updated and the other should be left as-is?

**Review by kamil4 — COMMENTED** [review]
I looked through your updates. I also tried to run some experiments to see how the new takestamps update code behaves, and that hit some major roadblocks.

First, the ancestors updates you made to Album actions apparently need to be duplicated within Photo actions as well. I.e., if I upload or delete a photo in a subalbum, the updates are not propagated up the tree.

I thought -- never mind, I'm going to limit my experiments to album actions, which should be fixed now, right? But those turn out to be very unstable. The simplest album/subalbum move, merge, or delete operations trigger server-side errors for me. When I managed to find one that didn't crash (a move of one top-level album into another), the takestamps of the remaining top-level one after the move were reset to NULL. I can go into more detail but I'm pretty sure that you can reproduce these issues in five minutes on your own if you just create a couple of albums and try to move them in/out of each other, merge them, etc.

I think the better use of my time right now is to continue the review of the files I haven't seen yet (as I still have a lot of those to go through), so that's what I'll try doing for the next few hours.

**Comment by kamil4** [comment]
Here's another thought. Why are we storing the takestamps in albums at all? As should be obvious by now, they are a major PITA to get right. And we even know that we never did it right (we accept the minor leak of potentially leaking a takestamp from an invisible subalbum).

We already calculate the thumbs dynamically. We can do the same with takestamps (actually, it's easier than thumbs) and all this pain will be gone for good.

File: app/Actions/Photo/Extensions/VideoEditing.php [hunk 25]
```diff
@@ -0,0 +1,163 @@
...
+	public function extractVideo(Photo $photo, int $videoLengthBytes, string $frame_tmp = ''): bool
+	{
+		// We extract the video from the jpg file
+		// Google Motion Photo: See here for details
+		//
+
+		if ($frame_tmp === '') {
+			$filename = $photo->url;
+			//! why is this dead code?
+			$url = Storage::path('big/' . $filename);
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/VideoEditing.php:116]: Because `$url` isn't used anywhere?

File: app/Actions/Photo/Extensions/VideoEditing.php [hunk 26]
```diff
@@ -0,0 +1,163 @@
...
+
+				return '';
+			}
+		}
+
+		return $tmp;
+	}
+
+	/**
+	 * Creates smaller copies of Photo.
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/VideoEditing.php]: This whole comment is for a different function.

File: app/Actions/Photo/Extensions/VideoEditing.php [hunk 27]
```diff
@@ -0,0 +1,163 @@
...
+			 * ! check if we can use path instead of this ugly thing.
+			 */
+			$ffmpeg = FFMpeg\FFMpeg::create();
+			$video = $ffmpeg->open(stream_get_meta_data($fp_video)['uri']);
+			$format = new MOVFormat();
+			// Add additional parameter to extract the first video stream
+			$format->setAdditionalParameters(['-map', '0:0']);
+			$video->save($format, $uploadFolder . $filename_video_mov);
+
+			// 3. Close files ($fp_video will be again deleted)
```
Comment (kamil4) [inline app/Actions/Photo/Extensions/VideoEditing.php:151]: I have no means to test it but I'm suspicious about this comment. There is no code in sight that could delete that file?!

File: app/Actions/Photo/SetAlbum.php [hunk 28]
```diff
@@ -0,0 +1,55 @@
...
+				throw new JsonError('Sorry, cannot Set to smart Album.');
+			}
+		}
+
+		$old_parents = Photo::select('album_id')->whereNotNull('album_id')->whereIn('id', $photoIDs)->pluck('album_id');
+
+		$no_error &= $this->do($photoIDs, $albumID == '0' ? null : $albumID);
+
+		if ($album !== null) {
+			$no_error &= $this->updateTakestamps->singleAndSave($album);
```
Comment (kamil4) [inline app/Actions/Photo/SetAlbum.php]: May need to update the ancestors as well.

File: app/Actions/Photo/SetAlbum.php [hunk 29]
```diff
@@ -0,0 +1,55 @@
...
+		}
+
+		$old_albums = Album::whereIn('id', $old_parents)->get();
+		foreach ($old_albums as $old_album) {
+			$no_error &= $this->updateTakestamps->singleAndSave($old_album);
```
Comment (kamil4) [inline app/Actions/Photo/SetAlbum.php]: May need to update the ancestors as well.

File: app/Actions/Photo/Setter.php [hunk 30]
```diff
@@ -0,0 +1,31 @@
+<?php
+
+namespace App\Actions\Photo;
+
+use App\Models\Photo;
+
+/**
+ * This class is used to set a property of a SINGLE photo.
+ * As a result, the do function takes as input an photoID.
```
Comment (kamil4) [inline app/Actions/Photo/Setter.php]: **a** photoID

File: app/Actions/Photo/Toggle.php [hunk 31]
```diff
@@ -0,0 +1,31 @@
+<?php
+
+namespace App\Actions\Photo;
+
+use App\Models\Photo;
+
+/**
+ * This class is used to toggle a boolean property of a SINGLE photo.
+ * As a result, the do function takes as input an photoID.
```
Comment (kamil4) [inline app/Actions/Photo/Toggle.php]: **a** photoID

**Review by kamil4 — COMMENTED** [review]
OK, that's it for tonight. I'm done reading through `app/Actions/Photo/*` (80 out of 235 files).

**Comment by ildyria** [comment]
> Here's another thought. Why are we storing the takestamps in albums at all? As should be obvious by now, they are a major PITA to get right. And we even know that we never did it right (we accept the minor leak of potentially leaking a takestamp from an invisible subalbum).
> 
> We already calculate the thumbs dynamically. We can do the same with takestamps (actually, it's easier than thumbs) and all this pain will be gone for good.

You forgot a small detail... Some of us order albums by max_takestamps DESC. :sweat_smile: 
But I will give it a serious thought given how a PITA it is to keep updated.

**Comment by kamil4** [comment]
> That's what we call robust code ;p

I like your optimistic spin on it :smiley:. Personally I think that the availability of `albums.json` in the front end is so uncertain that, short of the albums view, nothing can actually depend on it being there or being accurate...

> You forgot a small detail... Some of us order albums by max_takestamps DESC.

True :smiley:. So we wouldn't be able to use the DB engine for sorting... Although there's already a precedent for that, with titles and descriptions, which are sorted in PHP so that we can have natural sorting. This wouldn't be all that different, although we would of course first need to do the potentially costly calculation of album takestamps before we could sort them.

I was actually going to recommend something diametrically opposite: that we implement the caching of the _thumbnails_ in the album records. And my argument was going to be: well, we already do it for the takestamps. To be useful, two sets would've been required, one used for the public view and one for the owner view (that still wouldn't cover _all_ the cases but it would cover the major ones). But, on seeing how much struggle it is to get the simpler takestamp caching to work reliably, my idea "evolved" :wink:.

**Comment by ildyria** [comment]
I was actually trying some experiments to see if I could retrieve min_takestamp & max_takestamp from a subquery. Something in the style of the following
```php
$ret = Album::whereIsRoot()
	->addSelect([
		'max_takestamp' =>
		Photo::leftJoin('albums as s', 'album_id', '=', 's.id')
			->select(DB::raw('max_takestamp as MAX(takestamp)')
			->where('_lft', '<=', DB::raw('s._lft'))
			->where('s._rgt', '<=', DB::raw('_rgt'))
			->whereNotNull('takestamp'),
			->whereNotIn('s.id', $id_not_accessible),
		'min_takestamp' =>
		Photo::leftJoin('albums as s', 'album_id', '=', 's.id')
			->select(DB::raw('min_takestamp as MIN(takestamp)')
			->where('_lft', '<=', DB::raw('s._lft'))
			->where('s._rgt', '<=', DB::raw('_rgt'))
			->whereNotNull('takestamp'),
			->whereNotIn('s.id', $id_not_accessible)
	])
	->get();
dd($ret);
```

But I haven't managed to do so yet :(

**Comment by ildyria** [comment]
Coincidentally, I find today's XKCD extremely accurate. :rofl: 

[](https://xkcd.com/2407/)
> A death-first search is when you lose your keys and travel to the depths of hell to find them, and then if they're not there you start checking your coat pockets.

File: app/Console/Commands/Takedate.php [hunk 32]
```diff
@@ -64,12 +47,12 @@ public function handle()
...
 			$url = Storage::path('big/' . $photo->url);
 			if (file_exists($url)) {
-				$info = $this->metadataExtractor->extract($url, $photo->type);
+				$info = $metadataExtractor->extract($url, $photo->type);
 				if ($info['takestamp'] != null) {
 					$photo->takestamp = $info['takestamp'];
 					if ($photo->save()) {
 						$this->line($i . ': Takestamp updated for ' . $photo->title);
-						AlbumUpdate::update_takestamps($photo->album, [$photo->takestamp], true);
+						$updateTakestamps->singleAndSave($photo->album);
```
Comment (kamil4) [inline app/Console/Commands/Takedate.php]: Another place where ancestors may need updating...

**Comment by d7415** [comment]
> [](https://xkcd.com/2407/)

You're trying to implement the bread one, aren't you? *sigh*

File: app/Http/Controllers/Administration/DiagnosticsController.php [hunk 33]
```diff
@@ -319,8 +88,8 @@ public function show()
 	public function get_size()
 	{
 		$infos = ['You must be logged to see this.'];
```
Comment (kamil4) [inline app/Http/Controllers/Administration/DiagnosticsController.php]: This should say `logged in`.

File: app/Http/Controllers/Administration/DiagnosticsController.php [hunk 34]
```diff
@@ -270,10 +38,11 @@ public function get_config()
...
-			$infos = $this->get_info();
-			$configs = $this->get_config();
+		$errors = resolve(Errors::class)->get();
+
+		if (AccessControl::is_admin() || AccessControl::noLogin()) {
+			$infos = resolve(Info::class)->get();
+			$configs = resolve(Configuration::class)->get();
 		} else {
 			$infos = ['You must be logged to see this.'];
 			$configs = ['You must be logged to see this.'];
```
Comment (kamil4) [inline app/Http/Controllers/Administration/DiagnosticsController.php]: These should say `logged in`.

File: app/Http/Controllers/AlbumController.php [hunk 35]
```diff
@@ -225,37 +107,29 @@ public function getAlbum(string $albumId): Album
...
 			'password' => 'string|nullable',
 		]);
 
-		return $this->albumFunctions->unlockAlbum($request['albumID'], $request['password']) ? 'true' : 'false';
+		return $unlock->do($request['albumID'], $request['password']) ? 'true' : 'false';
 	}
 
 	/**
-	 * Provided a title and an albumID, change the title of the album.
+	 * Provided a title and an albumIDs, change the title of the albums.
```
Comment (kamil4) [inline app/Http/Controllers/AlbumController.php]: Remove **an**

File: app/Models/Extensions/AlbumGetters.php [hunk 36]
```diff
@@ -0,0 +1,101 @@
...
+	{
+		[$sort_col, $sort_order] = $this->get_sort();
+
+		$sql = $this->get_all_photos();
+
+		//? apply safety filter : Do not leak pictures which are not ours
+		$forbiddenID = resolve(PublicIds::class)->getNotAccessible();
+		if ($forbiddenID != null && !$forbiddenID->isEmpty()) {
+			$sql = $sql->whereNotIn('album_id', $forbiddenID);
+		}
```
Comment (kamil4) [inline app/Models/Extensions/AlbumGetters.php:81]: Will this by any chance trigger for thumbs of subalbums inside a hidden album? If so, that would suck...

**Review by kamil4 — COMMENTED** [review]
I'm beginning to see light at the end of the tunnel (177 / 235 files viewed).

File: app/Console/Commands/Takedate.php (hunk 32 above)
Comment (ildyria) [reply app/Console/Commands/Takedate.php]: Good one.

File: app/Models/Extensions/AlbumGetters.php (hunk 36 above)
Comment (ildyria) [reply app/Models/Extensions/AlbumGetters.php:81]: Hahaha nicely spotted. ^^"

Comment (kamil4) [reply app/Models/Extensions/AlbumGetters.php:81]: Yeah, I guess that NotAccessible set needs to be rebuilt from the current album, not from the root of the albums tree? For cases like smart albums or search that's the same thing, but not here...

Comment (ildyria) [reply app/Models/Extensions/AlbumGetters.php:81]: Yes, but that should be easily adaptable so I am not too worried about that.

File: app/Models/Extensions/PhotoBooleans.php [hunk 37]
```diff
@@ -0,0 +1,29 @@
...
+	{
+		$sql = $this->where(function ($q) use ($checksum) {
+			$q->where('checksum', '=', $checksum)
+				->orWhere('livePhotoChecksum', '=', $checksum);
+		});
+		if (isset($photoID)) {
+			$sql = $sql->where('id', '<>', $photoID);
+		}
+
+		return ($sql->count() == 0) ? false : $sql->first();
```
Comment (kamil4) [inline app/Models/Extensions/PhotoBooleans.php]: Is this the optimal way of doing it? It will be two queries if there are duplicates. Can't we simply issue `$sql->first()` and test for `null` or something instead of issuing `count()` first?

File: app/Models/Extensions/PhotoCast.php [hunk 38]
```diff
@@ -0,0 +1,204 @@
...
+	}
+
+	/**
+	 * Downgrade the quality of the pictures.
+	 *
+	 * @param array $return
+	 */
+	public function downgrade(array &$return)
+	{
+		if (strpos($this->type, 'video') === 0) {
```
Comment (kamil4) [inline app/Models/Extensions/PhotoCast.php]: I believe this condition is reversed. This is supposed to trigger for photos, not videos. It won't do anything for videos anyway since they never have `medium` or `medium2x` variants, but as written it won't do anything for photos either...

**Review by kamil4 — COMMENTED** [review]
Nearly finished (218 / 235 files viewed). I only have the new (livewire-specific) files to go through.

**Comment by ildyria** [comment]
> I only have the new (livewire-specific) files to go through.

Yeah but you will have to "enable" them to test it. I did not really rework on them since I did the refactoring.

To enable them you need to add `LIVEWIRE_ENABLED=true` to your `.env` file. That way this is intended to be able to merge with master without revealing such routes/files.

File: app/Models/Extensions/PhotoCast.php (hunk 38 above)
Comment (ildyria) [reply app/Models/Extensions/PhotoCast.php]: Not sure. Because in the case of video the thumbnails are containing the preview.

Anyway, the check `strpos($this->type, 'video') === 0` should be integrated in the photo model (`$this->is_video()`)  making it more readable and easier to work with as we would make it a single application point to modify in case of further refactoring...

File: app/Models/Extensions/PhotoBooleans.php (hunk 37 above)
Comment (ildyria) [reply app/Models/Extensions/PhotoBooleans.php]: hummm would `return $sql->first() ?? false;` be better? :)

Comment (kamil4) [reply app/Models/Extensions/PhotoBooleans.php]: If that evaluates `$sql->first()` just once, then yes :smiley:.

File: app/Models/Extensions/PhotoCast.php (hunk 38 above)
Comment (kamil4) [reply app/Models/Extensions/PhotoCast.php]: Yeah, I saw multiple of these calls sprinkled under `app/Models`; I agree they should be replaced.

Back to the main point, I'm pretty sure I'm right. The job of `downgrade` is to prevent the full photo (`big`) from being available. It's not supposed to do anything for videos, because the only video variants we have are `big` (we don't resize video files, and we only generate `thumb` and `small` `.jpeg` previews for them).

I checked the code on `master` and there's a subtle difference: there it uses `== 0`. `strpos` returns `false` if there's no match, and since in PHP `false == 0`, the condition triggers for image files like it's supposed to. As far as I can tell though, that's just two bugs canceling each other out, rather than a deliberate coding :smiley:.

File: app/Actions/Album/Merge.php (hunk 20 above)
Comment (ildyria) [reply app/Actions/Album/Merge.php:50]: deliberately.

File: app/Actions/Photo/Extensions/VideoEditing.php (hunk 26 above)
Comment (ildyria) [reply app/Actions/Photo/Extensions/VideoEditing.php]: fixed.

File: app/Actions/Photo/Setter.php (hunk 30 above)
Comment (ildyria) [reply app/Actions/Photo/Setter.php]: fixed.

File: app/Actions/Photo/Toggle.php (hunk 31 above)
Comment (ildyria) [reply app/Actions/Photo/Toggle.php]: fixed.

**Comment by ildyria** [comment]
@kamil4 I did a few simple fix, I suggest you go through the commits instead of the files again. :)
I will create a new branch to fix the ancestor/descendants problem and make a PR to this branch so that it is easier to review.

**Comment by kamil4** [comment]
> @kamil4 I did a few simple fix, I suggest you go through the commits instead of the files again. :)

No worries; github keeps track of what I've seen and gives me a convenient _New changes since you last viewed_ shortcut.

**Comment by kamil4** [comment]
Do you want regressions reported here or should I be opening issues for them?

First regression: smart albums display `undefined Photos` in albums view. Looks like it's because `num` is not set for them in the response to `Albums::get`.

**Comment by ildyria** [comment]
Fixed.

**Comment by kamil4** [comment]
Next regression: photo delete does not refresh the album view in the front end. I believe I tracked it down to:

https://github.com/LycheeOrg/Lychee/blob/63a990c2102634f3ae8e8049df5c7107ad74099d/app/Actions/Album/Prepare.php#L47

This needs to be wrapped in a `strval`.

**Comment by ildyria** [comment]
Fixed.

**Comment by kamil4** [comment]
Album merge has a number of issues. If a source album has no photos, an error is returned. Subalbums are not moved over. The source is not deleted. The latter two are because of a missing `get()` (took me a while to figure that out :smiley:).

**Comment by ildyria** [comment]
Fixed.

I'm really surprised this didn't break earlier for that one.

**Comment by kamil4** [comment]
Doesn't seem to cause any real issues, but `has_albums` is set to `1` for smart albums.

**Comment by ildyria** [comment]
lol weird.

**Comment by ildyria** [comment]
Should be fixed now.

**Comment by kamil4** [comment]
Tag (smart) albums have an empty title in `Album::get`. I'm guessing it's because `TagAlbum` inherits from `SmartAlbum`?

**Comment by ildyria** [comment]
Hummm yeah I think so.

**Comment by ildyria** [comment]
Should be fixed.

**Comment by kamil4** [comment]
Tag albums can't be made public, probably for the same reason... Description can't be updated as well.

**Comment by ildyria** [comment]
> Tag albums can't be made public, probably for the same reason... Description can't be updated as well.

That bug has been there for a while then.

**Comment by kamil4** [comment]
> That bug has been there for a while then.

No, I'm only reporting new regressions here that are not present on `master`. I'm saving the bugs also on `master` for later :smiley:.

**Comment by kamil4** [comment]
"Search" doesn't work:
```
Undefined property: App\\Http\\Controllers\\SearchController::$album_model at [...]/app/Http/Controllers/SearchController.php:145)
```

Looks like a case missed during a round of refactoring.

**Comment by kamil4** [comment]
Video uploads don't work:
```
Class 'App\\Actions\\Photo\\Extensions\\FFMpeg\\FFMpeg' not found at [...]/app/Actions/Photo/Extensions/VideoEditing.php:46
```
Looks like a missing `use FFMpeg;`?

**Comment by kamil4** [comment]
If there are no public starred photos, frame fails with the following error:
```
Return value of App\\Actions\\Photo\\Random::do() must be of the type array, string returned at [...]/app/Actions/Photo/Random.php:19)
```

**Comment by ildyria** [comment]
- [x] Tag albums can't be made public, probably for the same reason... Description can't be updated as well.
- [x] If there are no public starred photos, frame fails with the following error
- [x] Video uploads don't work
- [x] "Search" doesn't work

**Comment by kamil4** [comment]
Download of the Starred smart album doesn't work. It needs:
```
        public $id = 'starred';
```
in `app/SmartAlbums/StarredAlbum.php`.

**Comment by kamil4** [comment]
(Public) Search doesn't return password-protected albums. I'm hesitating whether to call this an issue or not; the old code made sure that they are returned, but if that's a hassle with the new code, it may not be worth fixing? In that case though, the `SearchController` could be simplified a bit and the comments should be updated, as they currently reflect the old behavior.

**Comment by ildyria** [comment]
```
        public $id = 'starred';
```

Fixed.

**Comment by ildyria** [comment]
Everything is working but Larapass is broken again. :(

**Comment by haivala** [comment]
Just asking: After this is there still going to be custom auth system that makes Oauth2 client hard to implement?

**Comment by ildyria** [comment]
> Just asking: After this is there still going to be custom auth system that makes Oauth2 client hard to implement?

This was already changed with version 4.1 :)

**Comment by haivala** [comment]
> > Just asking: After this is there still going to be custom auth system that makes Oauth2 client hard to implement?
> 
> This was already changed with version 4.1 :)

That really did not answer my question :)
