### PR TITLE
Consistent JSON API incl. Proper Handling of Errors (2nd half of big refactoring)

### LINKED ISSUE #592: [Enhancement] Catch exceptions for individual photos so that it will not stop syncing of large photo library
Lychee may fail to process some photos in a large set of photos for various reasons such as corrupted photo, exceptional boundary condition. 

Current, Gdhandler->crop() did not catch all exceptions so that it will stop the whole syncing procedure. And It is very difficult and tediously to location the photos which caused the exception.

It will be really nice if Lychee can skip and record photos which can not be processed and keep syncing other photos. 

```php
ErrorException: getimagesize(): Read error! in /var/www/html/Lychee/app/Image/GdHandler.php:145
Stack trace:                                                                                                                                                                                                
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'getimagesize():...', '/var/www/html/L...', 145, Array)                                                            
#1 /var/www/html/Lychee/app/Image/GdHandler.php(145): getimagesize('/tmp/lycheeTPvv...')                                                                                                                    
#2 /var/www/html/Lychee/app/Image/ImageHandler.php(59): App\Image\GdHandler->crop('/tmp/lycheeTPvv...', '/var/www/html/L...', 200, 200)                                                                     
#3 /var/www/html/Lychee/app/ModelFunctions/PhotoFunctions.php(547): App\Image\ImageHandler->crop('/tmp/lycheeTPvv...', '/var/www/html/L...', 200, 200)                                                      
#4 /var/www/html/Lychee/app/ModelFunctions/PhotoFunctions.php(411): App\ModelFunctions\PhotoFunctions->createThumb(Object(App\Photo), '/tmp/lycheeTPvv...')                                                 
#5 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 1589660971, false, true)                                                               
#6 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(369): App\Http\Controllers\ImportController->photo('/conf/sync/zhan...', false, 1589660971, true)                                         
#7 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(405): App\Http\Controllers\ImportController->server_exec('/conf/sync/zhan...', 1589660971, false, true, NULL)                             
#8 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(405): App\Http\Controllers\ImportController->server_exec('/conf/sync/zhan...', 1589650651, false, true, NULL)                             
#9 /var/www/html/Lychee/app/Console/Commands/Sync.php(85): App\Http\Controllers\ImportController->server_exec('/conf/sync/zhan...', 0, false, true)                                                         
#10 [internal function]: App\Console\Commands\Sync->handle()                                                                                                                                                
#11 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)                                                                          
#12 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()                                                 
#13 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))                                                 
#14 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)        
#16 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)                                                                      
#17 /var/www/html/Lychee/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))    
#18 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/html/Lychee/vendor/symfony/console/Application.php(912): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/Lychee/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/Lychee/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/Lychee/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))               
#25 {main}  
```

### LINKED ISSUE #902: Deleting User which owns albums breaks Lychee.
### Detailed description of the problem [REQUIRED]

see #900 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create user A with upload rights.
2. Log as user A and create an album
3. Log as admin and delete user A.
4. **BOUM**

### Solutions

1. Forbid User deletion if they still own albums
2. If a user is delete, all the pictures and albums they are are deleted.
3. If a user is delete, all the pictures and albums have their ownership transferred to admin.

Pick your poison.

### LINKED ISSUE #944: Trusted Proxies
Ref LycheeOrg/Lychee-Docker#89

Lychee includes [`fideloper/proxy`](https://github.com/fideloper/TrustedProxy/) which appears to tell Laravel when to trust `X-Forwarded-*` headers. At a glance, it looks like it uses `app/Http/Middleware/TrustProxies.php` for its configuration.

Assuming I'm correct:
 - `10.0.2.2` is hardcoded as a trusted proxy. That's not ideal.
 - This can't be configured `.env`.

Thoughts?

### LINKED ISSUE #962: HTTP request to `/api/Album::get` with illegal or non-existing albumID returns a HTTP 200 instead of 404 or 422, resp.
I am working on an Android client for Lychee and use the [API documentation](https://lycheeorg.github.io/docs/api.html) as my starting point. (However, I still need to reverse-engineer a lot, because the JSON schema is undocumented).

I stumbled across a surprising aspect.

If I post a request to `/api/Album::get` with an empty string as album ID or a non-existing album ID, both times the Lychee responds with HTTP status 200 OK and a text message body which contains `false`.

In other words

    POST https://photos-dev.mhnnet.de/api/Album::get
    {"albumID":""}

returns

    200 OK https://photos-dev.mhnnet.de/api/Album::get
    Content-Type: application/json
    
    "false"

and

    POST https://photos-dev.mhnnet.de/api/Album::get
    {"albumID":"42"}

with "42" not being an existing album also returns

    200 OK https://photos-dev.mhnnet.de/api/Album::get
    Content-Type: application/json
    
    "false"

IMHO, the first one should be a 422 and the latter one a 404. Moreover, it would recommend to respond with a proper JSON object which explains the error. I am speaking about the following JSON response which one gets in other cases

    {"message":"The given data was invalid.","errors":{"albumID":["The album i d field is required."]}}

Returning 200 in the cases above makes it rather difficult to implement a client, because one must not rely on a correct HTTP status code which in turn makes it difficult to use 3rd party libraries like Retrofit2, OkHTTP and GSON out-of-the-box without patching around strange server responses.

### LINKED ISSUE #964: [Enhancement] Overhaul REST API
I am working on an Android client for Lychee. The current state of the REST API drives me nuts. The way the API is right now make it rather difficult to write a client with the Java libraries GSON+Retrofit2, cache the responses in local SQL database with Room and drive the client GUI from the local cache during offline scenarios.

Maybe, the API is the way it is due to historic reasons and because nobody had the time or an reason to overhaul the API. But maybe there are also good reasons why the API must be the way it is and which a I am not aware of. In the first case, I might try and spend some time to improve the API on-the-go while I am working an the Android client. In the second case, I would like to be enlighten why the API has to be the way it is.

If I had to categorize my findings, I would come up with the following categories

 1. Varying actual type of attributes for the same formal type in JSON responses
 2. Conversion to human-readable strings on the server side instead on the client side including partial but inconsistent localization
 3. Inconsistent naming of attributes

The categories are explained in detail in the addendum. If you think it might be doable to overhaul the API with manageable effort and if there is an option how I could help out, let me know.

----

**Addendum**

*I. -- Mismatch of formal types and actual types in JSON objects / Prevalence of strings*

Most of the time the server responds with attributes encoded as strings although the should actually be of a different type. I guess this might be a problem with PHP on the server-side as PHP tends to convert everything into a string if one does not take care. More specifically:

- Boolean: Booleans in responses are reported as actual JSON boolean, i.e. `{ visbible : true }` and `{ visbible : false }`, but also as JSON numbers `0` and `1` and as literal strings `"0"`, `"1"`, `"true"`, `"false"`.

- Numbers: Numbers in responses are reported as actual JSON numbers, i.e. `{ id : 42 }`, but also as literal strings `"42"`. In particular this affect most of the "ID"-like attributes, i.e. `photoID`, `albumID` ..., counters for arrays and dimensional attributes (width and height of an image)

- Arrays of objects: If the array is non-emtpy the response looks like `{ photos : [ ... ] } ` and everything is fine. But empty arrays are correctly reposted as `[] ` but also as `null` and even worse as `false`. In particular the latter is a problem. While a Java list object can perfectly be `null`, one cannot assign `false` to it.

All this might be no problem, if the attributes are only used to be displayed to a user via an HTML page. However, it makes it rather difficult to deserialize the JSON object into a proper Java object with GSON+Retrofit2. In particular, if an attribute is expected to be an array of other objects, the GSON libraray expects to find the tokens `[...]` which will be deserialized into a Java-`List<>`. But an empty array must never be `false`. This seems to be typical PHP quirk.

*II. -- Human-readable string conversion on the server side*

Many attributes are already converted into a human-readable form on the server side. This mostly affect timestamps (e.g. the attribute `takestamp` and friends). Two particular ugly findings:

 - Precision varies with the context: for an album which includes a multitude of photos, the maximal and minimal timestamps are reported up to a monthly precision, for an album which only includes some photos from the same month, the timestamps are reported with daily precision. A timestamp of a photo entity is reported with hourly precision, if this photo entity is part of an array of photos in an album (i.e. as part of the response from `/api/Album::get`), but the timestamp of the very same photo entity the timestamp is reported up to a precision with seconds. 
 - Localization depends on server-settings and is inconsistent: The formatted timestamp depends on the localization settings of the PHP configuration. However, not all timestamps are returned localized, some are always returned in the C-locale.

Both aspects make it nearly impossible to deserialize the response on the Android client side and store the response in a local database cache, because it needs a lot of clever guessing what time format is used and then convert this time into a true Java time object or SQL timestamp. Moreover, if the same entity is received from different responses and with different timestamps it is not clear which one is "more" correct.

IMHO, localization should only take place on the client side on the GUI level right before the timestamp is going to be displayed, but should not happen on the server backend. I believe it would be best to report all times as a JSON number (Java/Javascript long) in seconds from epoch or another suitable unambiguous format. A JSON-like ISO 8601 string would also be fine. Even Javascript in a browser support to convert those timestamps into a human-readable format and will also honor the browsers locale settings.

The same problem also affects other attributes:

 - File sizes are reported as strings formatted as "\<localized quantity\> \<unit\>" with quantity being a possibly fractional number and the unit something like "kB", "MB" etc, i.e `"12.5 kB"`. With a different server-side locale, the same size could also be reported as `"12,5kB"` (comma instead of decimal point, no between space between value and unit). IMHO, one should use a fixed unit, e.g. bytes, and only report the value as an integer. Conversion into a more human-friendly format should be left to the GUI layer.
 - Shutter speed is reported as a string with a true fraction, i.e. `"1/50 s"`, or as a decimal fraction, i.e `"0.02 s"`, or with a different unit, i.e. `"20ms"`. IMHO, one should use a fixed base unit, e.g. µs, and report the shutter speed as an integer multitude of that base unit
 - and so on

*III. -- Inconsistent naming of attributes*

This is the least problem and probably the easiest to fix. Some attributes are named inconsistently over the API or the same name has different meaning. Of course, this is nitpicking but is makes it harder to implement a client fluently. For example, lets take the attribute `size`. When it comes to images this meaning is ambiguous: size of file on disk or geometrical size of the photo? Unfortunately, the API uses the name for both depending on the context. IMHO, the wording should at least be consistent across an API and unambiguous at the optimum. In this particular case: `filesize` and `dimension`. 

My apologies for this very long post. But I wanted to point out all aspects at once.

### PR DESCRIPTION
**Pull request by nagmat84**
# Summary

## Custom Exceptions with Optional HTTP Status Code

A lot of custom exception classes have been created. They are organized as follows:

Exceptions

All exceptions realize the interface `LycheeException`. This interface does not declare any methods. It is only used for grouping all Lychee exceptions. Lychee exceptions are categorized into external and internal exceptions via the interfaces `ExternalLycheeException` and `InternalLycheeException`.

External exceptions are meant to be returned to the frontend. To foster this, external Lychee exceptions must also realize
`HttpExceptionInterface` to provide meaningful HTTP status codes to the frontend. In particular, the message text of external Lychee exceptions should

 1. be understandable and provide a meaningful information for an end user as the message text is displayed to the user inside the status bar of the front-end
 2. not disclose any sensitive, security-relevant information

Internal exceptions are used for internal error propagation. While internal exceptions bubble up the call graph they should become wrapped into an external exception at some point.

Ideally, the methods of the HTTP controllers eventually only throw external exceptions. However, if an internal exception slips through the exception handler will take care of that and return a generic `500 Internal Server Error` to the frontend as a last line of defense to avoid unintended leakage of sensitive information.

## Revised Exception Handler

The exception handler `App\Exceptions\Handler` has heavily been revised.

### Correct content type

The old method `render` is gone. This method was bad, because it did not honor the content type which was expected by the client but unconditionally returned a HTML representation of the exception even if the frontend requested JSON.

The method has been replaced by the two distinct methods `renderHttpException` and `convertExceptionToArray`.
The former is called by the Laravel framework for HTML responses, the latter for JSON responses. Note, that `renderHttpException` is actually a misnomer, it should be named `renderHTMLException` (because JSON also uses HTTP as a transport layer), but heh, this is Laravel. :cry:

### Logging

Exceptions are now properly logged to our own home-brewed logging mechanism. The method `report` of the Laravel default exception handler has been overridden. The Larvavel default method tries to use a service which realizes the `\Psr\Log\LoggerInterface` which is not implemented by our class `Logs` and hence it has not worked until now.

This gives us two benefits:

 - We can avoid the "double" error handling in our code, i.e. we do not need to throw an exception and separately create a log entry with the same error message. Creating and throwing the exception now suffices.
 - If any uncaught exception (from the framework or a low-level PHP exception) occurs, we will see it in the logs with a proper error message and backtrace. So we will be able to help our users much faster if they experience an unexpected error. :sunglasses: :tada: :confetti_ball:
   
## Consistent Handling of Requests

Previously, incoming requests have been handled very inconsistently. In particular, proper and complete input validation of was matter of luck and even if it partially happened it was too late most of the time. Authorization was inconsistent, too. Some of it happened inside the middleware (but at a too early stage), some of it happened inside the controller methods or even deeper down.

Now, there is a strict order

 1. Input validation (HTTP status on failure: `422 Unprocessable`)
 2. User authentication (HTTP status on failure: `401 Unauthorized`)
 3. Model hydration (HTTP status on failure: `404 Not Found`)
 4. Authorization (HTTP status on failure: `403 Forbidden`)

Or in cat format:

This gives us three benefits:

 - **Higher Security:** Previously, the middleware which tried to do some authorization during a very early stage fed the unvalidated input to the DB. That's avoided now; we always validate first.
 - **Slightly Higher Efficiency:** Previously, there were several database requests for the same model which was indicated by the request while the request was being processed only to hydrate this model from the DB eventually as part of the controller method. This is gone now; the models which are indicated by the request are now loaded in step 3 and become part of the request object so they can be used later on without repeated DB request.
 - **Solved Regression Bug:** The known regression bug of the first half of the re-factoring was due to the wrong order of step 4 and 3. So the frontend always got a 403 response even if the model did not exist.

All this is achieved by a _lot_ of custom request classes in `App\Http\Requests`. Maybe you know the Laravel feature that routes can have place-holders for model IDs, e.g. something like `GET /album/{album}/` and then "by magic" Laravel hydrates the model and puts it into the request object. This does not work in out case, because our routes don't follow this pattern and the IDs are part of the JSON payload of the request. The custom request classes rectify this problem.

## Middleware Cleanup

The middleware has been mucked out:

 - Authorization in the middleware is gone. It is now part of the request handling, see previous point.
 -  Strict checks for the content type in a request and for the expected content type of the response have been added.
 - Middlewares do _not_ directly return a HTML response unconditionally, if something fails but they only throw a specific exception and let the exception handler do the rest. This is required in order to return the correct content type depending
   on the expectation of the request (either HTML or JSON)

## Miscellaneous

 - The streamed response for importing images from the server streamed a proper JSON array. This allows much easier and "type-safe" parsing on the frontend.
 - In `Albums::get` the tags albums have been split from the collection of built-in smart albums. Using two separate collections avoids some awkward and unnecessary checks in the frontend.
 - A lot of DTO (data-transfer objects): previously, a lot of methods passed around associative arrays instead of proper and type-safe objects. 
 - The routing files have been cleaned up; in particular requests for HTML pages and API requests for JSON have been separated.
 - Many requests and responses now use proper JSON array to transport lists (e.g. lists of tags, lists of IDs, etc.)

### CODE REVIEW

**Comment by ildyria** [comment]
TL, DR, LGTM.

no ? :D

File: app/Actions/Album/SetSorting.php [hunk 1]
```diff
@@ -2,14 +2,20 @@
...
+use Illuminate\Database\Eloquent\ModelNotFoundException;
+
 class SetSorting extends Action
 {
-	public function do(string $albumID, ?string $sortingCol, ?string $sortingOrder): bool
+	/**
+	 * @throws ModelDBException
+	 * @throws ModelNotFoundException
+	 */
+	public function do(string $albumID, ?string $sortingCol, ?string $sortingOrder): void
```
Comment (ildyria) [inline app/Actions/Album/SetSorting.php]: why is this method taking a `$albumID` instead of a BaseAlbum ?
(just to be consistent with the other Action calls)

File: app/Actions/Album/Setter.php [hunk 2]
```diff
@@ -35,6 +35,8 @@ protected function __construct(Builder $query, string $property)
 	/**
 	 * @param string $albumID the ID of the album
 	 * @param mixed  $value   the value to be set
+	 *
+	 * @throws ModelNotFoundException
 	 */
 	public function do(string $albumID, mixed $value): void
```
Comment (ildyria) [inline app/Actions/Album/Setter.php]: Can't we have this method use a Album or BaseAlbum instead ?

**Comment by nagmat84** [comment]
> TL, DR, LGTM.
> 
> no ? :D

Did you just add these cat photos to my description? :rofl:

File: app/Actions/Album/Setter.php (hunk 2 above)
Comment (ildyria) [reply app/Actions/Album/Setter.php]: I will need to reread he code globally outside the PR.

File: app/Actions/AlbumAuthorisationProvider.php [hunk 3]
```diff
@@ -246,51 +263,33 @@ public function applyReachabilityFilter(Builder $query): Builder
...
+		if ($album instanceof BaseAlbum) {
 			return
 				($album->owner_id === $userID) ||
 				($album->is_public && $album->password === null) ||
-				($album->is_public && $this->isAlbumUnlocked($album->id)) ||
+				($album->is_public && $this->isUnlocked($album)) ||
 				($album->shared_with()->where('user_id', '=', $userID)->count());
+		} elseif ($album instanceof BaseSmartAlbum) {
+			return
+				($userID && AccessControl::can_upload()) ||
```
Comment (ildyria) [inline app/Actions/AlbumAuthorisationProvider.php]: can_upload() is already checking if user is logged in, so you don't need the `$userId` here.
Only reason for it would be lazy evaluation of the `&&` but that is more of the domain of the micro optimization.

File: app/Actions/Album/SetSorting.php (hunk 1 above)
Comment (nagmat84) [reply app/Actions/Album/SetSorting.php]: Because the action calls are not used by the controllers anymore. At least not for the trivial setters. For this specific case see

https://github.com/LycheeOrg/Lychee/pull/1217/files#diff-64646ce0183575e7ffc0f7292df2b7611839781641acddd7792a4c029e5404c1R298-R302

Actually, most of the actions can be nuked. I didn't do that, because I did not know if you still want to keep them for the Livewire part. But currently they are dead code.

File: app/Actions/Album/Setter.php (hunk 2 above)
Comment (nagmat84) [reply app/Actions/Album/Setter.php]: See above. This is dead code and I did not nuke it, because I didn't know if you wanted to keep it.

Comment (ildyria) [reply app/Actions/Album/Setter.php]: Will need to dig into it, with how to interface with Livewire.

**Comment by ildyria** [comment]
> > TL, DR, LGTM.
> > no ? :D
> 
> Did you just add these cat photos to my description?  :rofl:

File: app/Actions/Diagnostics/Configuration.php [hunk 4]
```diff
@@ -21,25 +18,22 @@ public function __construct(ConfigFunctions $configFunctions)
...
-				if (!is_array($value) && !is_null($value)) {
-					$configs[] = $this->line($key . ':', $value);
-				} elseif (is_null($value)) {
-					$configs[] = 'Error: ' . $key . ' has a NULL value!';
-				}
+		// Load settings
+		$settings = $this->configFunctions->min_info();
+		foreach ($settings as $key => $value) {
+			if (!is_array($value) && !is_null($value)) {
+				$configs[] = parent::line($key . ':', $value);
```
Comment (ildyria) [inline app/Actions/Diagnostics/Configuration.php]:
```suggestion
				$configs[] = Diagnostics::line($key . ':', $value);
```
Just for uniformity with the other diagnostics files.

File: app/Actions/Install/ApplyMigration.php [hunk 5]
```diff
@@ -2,73 +2,97 @@
...
+					unlink($filename);
+				} else {
+					throw new InstallationFailedException('A filesystem object . ' . $filename . ' exists, but is not an ordinary file.');
+				}
+			}
+		} catch (\ErrorException $e) {
+			// possibly thrown by `unlink`
+			$output[] = $e->getMessage();
+			$output[] = 'Could not remove file `.NO_SECURE_KEY`.';
+			throw new InstallationFailedException('Could not remove file `.NO_SECURE_KEY`', $e);
```
Comment (ildyria) [inline app/Actions/Install/ApplyMigration.php:93]: I am not sure if `$output[]` is needed as we are now throwing an exception...

File: app/Actions/PhotoAuthorisationProvider.php [hunk 6]
```diff
@@ -67,21 +75,52 @@ public function applyVisibilityFilter(Builder $query): Builder
...
+	 *                          and the `null` photo is always authorized
+	 *
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	public function isVisible(?Photo $photo): bool
+	{
+		return
+			$photo === null ||
+			AccessControl::is_current_user($photo->owner_id) ||
+			$photo->is_public ||
```
Comment (ildyria) [inline app/Actions/PhotoAuthorisationProvider.php:88]: To check, but does this property is the computed result of album & photo public or is it the value in the DB ? :thinking:

File: app/Actions/Settings/Login.php [hunk 7]
```diff
@@ -58,29 +92,36 @@ public function do(Request $request)
...
-
-				return $user->save();
+			// TODO: This looks suspicious.
+			// Users can only change the username/password of their own
+			// account and must be authenticated in order to do so.
+			// (See above, we use `AccessControl::id()` and query for the
+			// currently authenticated user).
+			// The user name of the currently authenticated user is visible on
+			// the GUI anyway.
+			// Why do we re-check whether users have been able to correctly
```
Comment (ildyria) [inline app/Actions/Settings/Login.php:111]: Most likely legacy stuff from when there was no multi user support.

File: app/Actions/Update/Apply.php [hunk 8]
```diff
@@ -59,94 +60,105 @@ private function check_prod_env_allow_migration(array &$output)
...
+		try {
+			if (Configs::get_value('apply_composer_update', '0') == '1') {
+				// @codeCoverageIgnoreStart
+				Logs::warning(__METHOD__, __LINE__, 'Composer is called on update.');
+
+				// Composer\Factory::getHomeDir() method
+				// needs COMPOSER_HOME environment variable set
+				putenv('COMPOSER_HOME=' . base_path('/composer-cache'));
+				chdir(base_path());
+				exec('composer install --no-dev --no-progress --no-suggest 2>&1', $output);
```
Comment (ildyria) [inline app/Actions/Update/Apply.php]: https://getcomposer.org/upgrade/UPGRADE-2.0.md
> Deprecated --no-suggest flag as it is not needed anymore
```suggestion
				exec('composer install --no-dev --no-progress 2>&1', $output);
```

File: app/Http/Middleware/TrustProxies.php [hunk 9]
```diff
@@ -1,25 +0,0 @@
-<?php
```
Comment (ildyria) [inline app/Http/Middleware/TrustProxies.php:1]: No no no no no.

This file must stay or your are breaking the IP transfer for users running Lychee on VM with proxy.
Or you have another solution.

This one is build breaking for me.

File: resources/views/diagnostics.blade.php [hunk 10]
```diff
@@ -1,3 +1,10 @@
+<!DOCTYPE html>
```
Comment (ildyria) [inline resources/views/diagnostics.blade.php:1]: I will need to check the change in Lychee-front for that one.

File: resources/views/logs/list.blade.php [hunk 11]
```diff
@@ -1,5 +1,16 @@
+<!DOCTYPE html>
+<html lang="en">
+<head>
+	<title>Lychee Diagnostics</title>
+	<meta charset="utf-8"/>
+</head>
+<body>
 <pre>
-@foreach($logs as $log)
+@forelse($logs as $log)
```
Comment (ildyria) [inline resources/views/logs/list.blade.php:9]: interesting. Today I learned.

File: resources/views/logs/list.blade.php [hunk 12]
```diff
@@ -1,5 +1,16 @@
+<!DOCTYPE html>
+<html lang="en">
+<head>
+	<title>Lychee Diagnostics</title>
```
Comment (ildyria) [inline resources/views/logs/list.blade.php]:
```suggestion
	<title>Lychee Logs</title>
```

**Review by ildyria — COMMENTED** [review]
Aside from the Trusted Proxy, LGTM.
Still need to test.

File: app/Http/Middleware/TrustProxies.php (hunk 9 above)
Comment (ildyria) [reply app/Http/Middleware/TrustProxies.php:1]: Also see this: https://github.com/LycheeOrg/Lychee/issues/1197

File: app/Actions/Album/Archive.php [hunk 13]
```diff
@@ -206,6 +225,7 @@ private static function isArchivable(AbstractAlbum $album): bool
 	{
 		return
 			$album->is_downloadable ||
+			AccessControl::is_admin() ||
```
Comment (kamil4) [inline app/Actions/Album/Archive.php]: Is this a bugfix? What case did we miss without this? Or is it more of an efficiency shortcut?

File: app/Actions/Import/Exec.php [hunk 14]
```diff
@@ -7,141 +7,174 @@
...
-	 * - Status: <directory name>: <percentage of completion>
-	 *   (A status is always sent for 0 and 100 percent at least).
-	 * - Problem: <file or directory name>: <problem description>
-	 *   (We avoid starting a line with 'Error' as that has a special meaning
-	 *   in the front end, preventing the completion callback from being
-	 *   invoked).
-	 * - Warning: Approaching memory limit.
+	 * Output status update to stdout.
+	 *
+	 * The output is either send to a web-client via {@link StreamedResponse}
```
Comment (kamil4) [inline app/Actions/Import/Exec.php]:
```suggestion
	 * The output is either sent to a web-client via {@link StreamedResponse}
```

File: app/Actions/Import/Exec.php [hunk 15]
```diff
@@ -7,141 +7,174 @@
...
+	 * or to the CLI.
+	 *
+	 * For web-clients this method reports JSON objects.
+	 * The outer caller precedes and terminates the whole output by `[` and
+	 * `]`, resp., in order to indicate the start and beginning of a JSON
```
Comment (kamil4) [inline app/Actions/Import/Exec.php]:
```suggestion
	 * `]`, resp., in order to indicate the start and end of a JSON
```

File: app/Actions/Album/SetSorting.php (hunk 1 above)
Comment (ildyria) [reply app/Actions/Album/SetSorting.php]: But if I don't use the actions in the Livewire side, wouldn't that lead to code duplication ? :thinking:

File: app/Actions/Photo/Delete.php [hunk 16]
```diff
@@ -2,23 +2,32 @@
...
 
+use App\Exceptions\ModelDBException;
 use App\Models\Photo;
 
 class Delete
 {
+	/**
+	 * @throws ModelDBException
+	 */
 	public function do(array $photoIds): void
```
Comment (kamil4) [inline app/Actions/Photo/Delete.php]: Is there a reason why this is kept as an array, not a `Collection` like in other cases?

File: app/Actions/Photo/SetAlbum.php [hunk 17]
```diff
@@ -13,28 +15,25 @@ public function __construct()
 		$this->property = 'album_id';
 	}
 
-	public function execute(array $photoIDs, ?string $albumID): bool
+	/**
+	 * @throws ModelNotFoundException
+	 * @throws QueryBuilderException
+	 */
+	public function do(array $photoIDs, ?string $albumID): void
```
Comment (kamil4) [inline app/Actions/Photo/SetAlbum.php]: Same question as to Delete earlier: why is this one left to use strings? Is it not being used?

File: app/Actions/Photo/Strategies/AddStandaloneStrategy.php [hunk 18]
```diff
@@ -147,36 +171,32 @@ protected function normalizeOrientation(): void
...
-			$metadataExtractor = resolve(Extractor::class);
-			$this->photo->filesize = $metadataExtractor->filesize($absolutePath);
-			$this->photo->checksum = $metadataExtractor->checksum($absolutePath);
-			$this->photo->save();
-		}
+		// If the image has actually been rotated, the size
+		// and the checksum may have changed.
+		$this->photo->filesize = $this->metadataExtractor->filesize($absolutePath);
+		$this->photo->checksum = $this->metadataExtractor->checksum($absolutePath);
+		$this->photo->save();
```
Comment (kamil4) [inline app/Actions/Photo/Strategies/AddStandaloneStrategy.php:201]: Why was the `if` eliminated? Is it because `$this->photo->save();` won't actually do anything if the filesize or checksum have not changed, so the `if` doesn't really help much?

**Comment by kamil4** [comment]
The two typos in the title were driving me crazy so I had to fix them :wink:.

File: app/Actions/Settings/Login.php [hunk 19]
```diff
@@ -2,51 +2,85 @@
...
+	 * This method serves three different purposes and the method tries to
+	 * "cleverly" find out which use-case is needed:
+	 *
+	 *  1. Initially setting the admin password in case no password has
+	 *     been set yet (e.g. after/during installation)
+	 *  2. Changing a user's own password by the users themselves.
+	 *  3. Changing a user's username and password for some arbitrary user
+	 *     by the administrator.
+	 *
+	 * Unfortunately, this make is rather difficult to authorize the request
```
Comment (kamil4) [inline app/Actions/Settings/Login.php]:
```suggestion
	 * Unfortunately, this makes it rather difficult to authorize the request
```

File: app/Actions/Album/SetSorting.php (hunk 1 above)
Comment (nagmat84) [reply app/Actions/Album/SetSorting.php]: No, it would not. Actually most of the actions are completely ridiculous. They create around 20 lines of code of indirection instead of one. Moreover, they are not type safe at all. For example.

Setting the title of an album now is basically:

```php
class AlbumController {
  public function setTitle(Album $album, string $title): void {
    $album->title = $title;
  }
}
```

I left out some parts, but I think the general idea is clear. The method is trivial and concise. The actual "magic" is a single line. The "Action" classes basically did the same, but in an unnecessary complicated manner.

```php
class AlbumSetter {
  private string $attribute;
  
  protected function __construct(string $attribute) {
    $this->attribute = $attribute;
  }

  /**
   * @param Album $album  the album whose attribute shall be set
   * @param mixed $value  the new value of the attribute
   */
  public function set(Album $album, $value): void {
    $album->{$this->attribute} = $value;
  }
}

class AlbumTitleAction extends AlbumSetter {
  public function __construct() {
    parent::__construct('title');
  }
}

class AlbumController {
  public function setTitle(Album $album, string $title, AlbumTitleAction $action): void {
    $action->set($album, $title);
  }
}
```

The latter approach is completely insane. The `AlbumSetter` class does nothing more than setting a single attribute of the object. Moreover, `$album->{$this->attribute} = $value` is dangerous in two ways:

 1. As we use runtime reflection here, we don't know if `$this->attribute` actually denotes a proper attribute of `$album`. We have no IDE completion and any static code analyzer will simply skip this part, because it cannot do anything.
 2. `$value` is of mixed type, because we don't know whether the requested attribute is a string, an integer, a boolean, a float or another object (e.g. a DateTime object).

And worst of all: it does not save anything. Instead of directly calling `$album->title = $title` in the controller method we call `$action->set($album, $title);`.

File: app/Actions/Album/Setter.php (hunk 2 above)
Comment (nagmat84) [reply app/Actions/Album/Setter.php]: I would like to nuke all these superfluous, overly complicated actions. Just call the model function directly. See my [comment in the previous thread](https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r825428655).

I simply haven't nuked them in this PR, because I did not want to break the Livewire part. Of course, there are a handful of actions (like archiving, rotating images) which do something relevant. These actions have been adopted to use the model objects directly instead of IDs. But 95% of the actions are a ridiculous, complicated way to express a one-liner. As the controller methods don't use these actions anymore, I haven't adopted them.

File: app/Actions/AlbumAuthorisationProvider.php (hunk 3 above)
Comment (nagmat84) [reply app/Actions/AlbumAuthorisationProvider.php]: Actually, it is not identical and it already has driven me crazy. If no admin user is configured, i.e. if the password and the user name of the admin equals the empty string `'' `, then many parts of the application behave as if the admin user was logged in, in particular `is_logged_in` returns `true` (and so does `can_upload`) although `$userID` equals `null`.

IMHO, this is bad design. First of all, many methods are dangerous misnomers. If there is no user, `is_logged_in` and similar methods should return `false`. Moreover, the code should precisely distinguish between `is_admin` and `has_admin_privileges`. The former should return `true`, if and only if a proper admin user exists and the admin user is properly logged in, but `false` otherwise. The latter method might also return `true`, if there is no admin yet and thus any user has admin privileges. Unfortunately, the current code base is extremely bad with respect to this whole issue.

Long story short, for the moment I would not change this but leave it as is. In the long run, I am considering to completely replace the whole home-brewed `SessionFunctions` by the proper, built-in Laravel component. This would also allow to use `request->user()`, because the user object is injected into the request by Laravel middleware. At the moment this does not work. In this context, I would also clean up this whole mess around privileges and how they are named.

File: app/Actions/Diagnostics/Configuration.php (hunk 4 above)
Comment (nagmat84) [reply app/Actions/Diagnostics/Configuration.php]: I am not sure, if I have written that code or if I only moved it around. Anyway, we can change it nonetheless.

File: app/Actions/Install/ApplyMigration.php (hunk 5 above)
Comment (nagmat84) [reply app/Actions/Install/ApplyMigration.php:93]: We do, because the parameter `$output` is passed by reference and thus becomes an output parameter which is used by the caller and returned to the web client even if an exception is thrown, because the caller catches the exception.

Haven't I said that I don't like this web installer/updater at all, have I? IMHO the whole thing should be replaced. Moreover, I don't like output parameters, because they tend to disguise the information flow. Your comment is prove of that.

However, I did not come up with this code. Improving this whole installer is a job for another PR.

File: app/Actions/PhotoAuthorisationProvider.php (hunk 6 above)
Comment (nagmat84) [reply app/Actions/PhotoAuthorisationProvider.php:88]: It is the computed result.

File: app/Actions/Settings/Login.php (hunk 7 above)
Comment (nagmat84) [reply app/Actions/Settings/Login.php:111]: Yes, that is what I assumed, too. But what exactly do you want to tell me by your comment? What is your intention?

IMHO, there are three (may be four) areas in the code which are dangerous and need improvement:

 1. User and Session Management: See also [my comment in this tread](https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r825435745).
 2. Web updater/installer: If it works, it works and everything is fine. If it fails (in particular, if dependencies via composer must be installed), then the user has no idea what went wrong. IMHO, at the moment this component does more harm than it helps. Moreover, the code is really wicked and incomprehensible, also see [this comment](https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r825437068).
 3. Exif data and file types: (You might count this as two, if you wish). The Exiftool returns a nice and type-safe object with extracted exif data. However, our code copies all the values into an unsafe, associative array and passes around that array. Also the array is changed in some non-obvious ways while it is passed around.  Moreover, we have a lot (i mean A LOT) of duplicated code which decides if we support a certain type of file or not (and of course the decision logic is always slightly different)

However, I did not come up with this code. When I added proper exception handling to our code I tried to work around these areas as well as I could without touching too much in these areas. IMHO, these three components needs to be rewritten from scratch. They are beyond "repairability".

IMHO, this should be three different, future PRs. Luckily, the impact of these PRs while be much more locally concentrated than this PR.

File: app/Actions/Update/Apply.php (hunk 8 above)
Comment (nagmat84) [reply app/Actions/Update/Apply.php]: Again, not my code. I only copied it or more precisely, wrapped it into an exception handler. That's why it appears as new code.

File: app/Http/Middleware/TrustProxies.php (hunk 9 above)
Comment (nagmat84) [reply app/Http/Middleware/TrustProxies.php:1]: I see. Will add the trusted proxy middleware again.

File: app/Actions/Album/Archive.php (hunk 13 above)
Comment (nagmat84) [reply app/Actions/Album/Archive.php]: A bug fix. Without it an admin was not able to unconditionally download an album.

File: app/Actions/Photo/Delete.php (hunk 16 above)
Comment (nagmat84) [reply app/Actions/Photo/Delete.php]: The answer is simple: This action is not used anymore but dead code. So my IDE did not catch it, when I re-factored the code. This action is one of the unnecessary ones [as discussed in this comment](https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r825428655).

Probably, I should simply remove all of these unnecessary actions so that nobody is wondering anymore.

File: app/Actions/Photo/SetAlbum.php (hunk 17 above)
Comment (nagmat84) [reply app/Actions/Photo/SetAlbum.php]: And same answer, https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r825448899

File: app/Actions/Photo/Strategies/AddStandaloneStrategy.php (hunk 18 above)
Comment (nagmat84) [reply app/Actions/Photo/Strategies/AddStandaloneStrategy.php:201]: For all of the mentioned reasons.

1. If `rotate` _fails_, then it throws a proper exception. `rotate` doesn't return `[false, false]`.
2. If `rotate` is a _no op_, i.e. the photo does not require rotation because it is already correctly oriented, then `rotate` returns an array with the original dimensions, but not `[false, false]`.
3. `->save` calculates the changed set of attributes and does nothing, if there was no change.

In other words, the condition is never taken and in case of a no-op, `save` itself prevents an unnecessary DB operation.

File: app/Actions/Album/SetSorting.php (hunk 1 above)
Comment (nagmat84) [reply app/Actions/Album/SetSorting.php]: Resolved by simple deletion of offending class.

File: app/Http/Middleware/TrustProxies.php (hunk 9 above)
Comment (nagmat84) [reply app/Http/Middleware/TrustProxies.php:1]: I added the middleware `TrustProxies` again, but directly call the parent class now. There is absolutely no need to extend a class if it is not extended.

File: app/Actions/Photo/Delete.php (hunk 16 above)
Comment (nagmat84) [reply app/Actions/Photo/Delete.php]: Resolved by simple deletion of offending class.

File: app/Actions/Photo/SetAlbum.php (hunk 17 above)
Comment (nagmat84) [reply app/Actions/Photo/SetAlbum.php]: Resolved by simple deletion of the offending class.

File: app/Actions/Settings/Login.php (hunk 7 above)
Comment (ildyria) [reply app/Actions/Settings/Login.php:111]: 1. User and Session management are indeed in need of improvement. I do hope to be able to refactor that a bit at least the front-end side.
2. I am open to having those rewritten from scratch.
I tried my best to provide an installer which works in similar fashion as the one provided with Lychee v3, that was one of the big complaint when moving to v4: there was the need of some commands to be executed with SSH which obviously is not really doable in the case of FTP webhosting solutions without command line access.
3. No complaints there either. I am always open to code improvement.

File: app/Http/Controllers/SessionController.php [hunk 20]
```diff
@@ -33,18 +38,20 @@ public function __construct(ConfigFunctions $configFunctions, GitHubFunctions $g
...
-	 * @return IlluminateResponse|array (array containing config information or killing the session)
+	 * TODO: Remove `status`; `status === 0 ` should result in a HTTP error response "no config", `status === {1|2}` should be a proper boolean `isAuthenticated`.
+	 *
+	 * @return array
+	 *
+	 * @throws ModelNotFoundException
+	 * @throws VersionControlException
 	 */
-	public function init()
+	public function init(): array
```
Comment (ildyria) [inline app/Http/Controllers/SessionController.php:60]: This sound like something that @nagmat84 would refactor with a DTO. :)

File: app/Http/Middleware/TrustProxies.php (hunk 9 above)
Comment (ildyria) [reply app/Http/Middleware/TrustProxies.php:1]: True, but the point of `TrustProxies` is to overload this part:
```php
	protected $proxies = [
		'10.0.2.2',
	];
```
Otherwise the parent class is useless, or am I failing to understand your goals.

I am considering having this array to be instantiated via a `.env` and `split(' ')`

Comment (nagmat84) [reply app/Http/Middleware/TrustProxies.php:1]: The idea of the parent class is to load those values from a config file. The config file has been added to this PR. So there is absolutely no need to extend the class.

File: config/trustedproxy.php [hunk 21]
```diff
@@ -0,0 +1,37 @@
...
+	 * supported, along with CIDR notation.
+	 *
+	 * The "*" character is syntactic sugar
+	 * within TrustedProxy to trust any proxy
+	 * that connects directly to your server,
+	 * a requirement when you cannot know the address
+	 * of your proxy (e.g. if using ELB or similar).
+	 *
+	 */
+	'proxies' => [], // [<ip addresses>,], '*'
```
Comment (ildyria) [inline config/trustedproxy.php]: this should use `env()` to read from `.env` rather than having the user modify it. :)

File: app/Http/Controllers/SessionController.php (hunk 20 above)
Comment (nagmat84) [reply app/Http/Controllers/SessionController.php:60]: In theory, yes and I also gave it some thought but intentionally did not touch it given the prospect of its impact.

On the plus side, the returned array is luckily not used anywhere else (here we are at the outer boundary of the backend).

On the minus side, the returned values are wicked, undocumented and usually misnamed (especially all the values in the context of user authentication) and not type-safe. If I had started to write a DTO for that, this would have led to another large re-factoring not only of the backend but also of the frontend.

Before I touch this one, the user management needs to be repaired, the session management and then the updater/installer in that order. Then and only then it is worth considering cleaning up this messy array.

File: config/trustedproxy.php (hunk 21 above)
Comment (nagmat84) [reply config/trustedproxy.php]: In theory, I agree with you. However, this has been the matter of state on the current master branch since commit 8139e62 on December 2008:

https://github.com/LycheeOrg/Lychee/blob/a8c1354890fdd8d49b3a73931764df1b5ed566b6/app/Http/Middleware/TrustProxies.php#L15-L17

Is this code insane and crap? Yes, definitely. Should it be improved? Yes. Is this targeted by this PR? No.

I cannot fix everything at once or my PRs would never make it. The last PR has been and this PR is already too large for a single PR. Unfortunately, it was actually impossible to keep them smaller. But at some point I need to draw a line and say, this or that is not going to be fixed now. Otherwise I could simply nuke Lychee entirely and start it from scratch. This won't be the last PR and hopefully the upcoming PRs will be much smaller with a more local impact (as I said, session handling, user management, exif extraction, file handling is still a mess) and without blocking other PRs.

It is completely unhelpful to comment on code that has already been there for years and which has not been invented by me, but which pops up in the PR only because I had to move it to another place or for which I simply changed the indentation due to an added `try`-`catch`-block. I know that this code is shitty. I feel very sorry, but IHMO 70% of the code of Lychee is in a state which I would have never accepted professionally in the first place. (Luckily, Lychee does not try to achieve a CC and/or DO certification. You don't want me to be your code reviewer.)

It was even you who hard-coded the magic IP `'10.0.2.2'` in the code snippet above in the first place and there has been an open issue #944 since last year and you gave it low priority. So don't tell me that is is bad to have hard-coded configuration values. If you had wanted to change that there would have been plenty of time to do it.

I will fix it now, because the fix will only add a couple of extra lines.

But I would really appreciate if you could keep your comments stick to the problems which are addressed by this PR and not randomly comment on things which accidentally happen to turn up as part of this PR but which have been this way for a long time and for which nobody felt responsible so far. This is completely contra-productive.

As a closing remark, I want to thank @kamil4 again for his thorough review of the last PR and (hopefully) this PR and the many fruitful, helpful and conducive remarks. (And no this is not irony, I really mean it that way.)

File: app/Exceptions/ConflictingPropertyException.php [hunk 22]
```diff
@@ -0,0 +1,30 @@
+<?php
+
+namespace App\Exceptions;
+
+use Symfony\Component\HttpFoundation\Response;
+
+/**
+ * InvalidPropertyException.
```
Comment (kamil4) [inline app/Exceptions/ConflictingPropertyException.php]:
```suggestion
 * ConflictingPropertyException.
```

File: app/Exceptions/FileOperationException.php [hunk 23]
```diff
@@ -0,0 +1,30 @@
...
+
+namespace App\Exceptions;
+
+use Symfony\Component\HttpFoundation\Response;
+
+/**
+ * Class FileOperationException.
+ *
+ * Indicates any error related to files.
+ * This includes error like moving/copying, files, reading files, etc.
```
Comment (kamil4) [inline app/Exceptions/FileOperationException.php]:
```suggestion
 * This includes error like moving/copying files, reading files, etc.
```

File: app/Exceptions/Handler.php [hunk 24]
```diff
@@ -2,83 +2,212 @@
...
 	 */
-	protected $dontFlash = [
-		'password',
-		'password_confirmation',
-	];
+	protected function renderHttpException(HttpExceptionInterface $e): SymfonyResponse
+	{
+		// If we are in debug mode, we use the internal method of the parent
+		// method to render a useful response with backtrace, etc., depending
+		// on the available extensions (i.e. Whoops, Symfonfy renderer, etc.)
```
Comment (kamil4) [inline app/Exceptions/Handler.php]:
```suggestion
		// on the available extensions (i.e. Whoops, Symfony renderer, etc.)
```

File: app/Exceptions/Internal/FrameworkException.php [hunk 25]
```diff
@@ -0,0 +1,27 @@
+<?php
+
+namespace App\Exceptions\Internal;
+
+/**
+ * FrameworkException.
+ *
+ * This exception is meant to wrap the generic PHP standard exception which
```
Comment (kamil4) [inline app/Exceptions/Internal/FrameworkException.php]:
```suggestion
 * This exception is meant to wrap the generic PHP standard exceptions which
```

File: app/Exceptions/Internal/QueryBuilderException.php [hunk 26]
```diff
@@ -0,0 +1,21 @@
+<?php
+
+namespace App\Exceptions\Internal;
+
+/**
+ * QueryBuilderException.
+ *
+ * This exception is meant to wrap the generic PHP standard exception which
```
Comment (kamil4) [inline app/Exceptions/Internal/QueryBuilderException.php]:
```suggestion
 * This exception is meant to wrap the generic PHP standard exceptions which
```

File: app/Exceptions/InvalidPropertyException.php [hunk 27]
```diff
@@ -0,0 +1,28 @@
...
+/**
+ * InvalidPropertyException.
+ *
+ * Indicates that a model could not be processed, because one of its
+ * properties had an invalid value.
+ * The error message should at least indicate the type of model and the name
+ * of the property.
+ * Returns status code 422 (Unprocessable entity) to an HTTP client.
+ * As this exception reports a 4xx status code (opposed to a 5xx code),
+ * this exception should be used if the client or user is "responsible" of
```
Comment (kamil4) [inline app/Exceptions/InvalidPropertyException.php]:
```suggestion
 * this exception should be used if the client or user is "responsible" for
```

File: app/Exceptions/LycheeBaseException.php [hunk 28]
```diff
@@ -0,0 +1,58 @@
...
+ * application should extend this class.
+ * Outer-most methods means those methods which are entry (and also exit)
+ * points of the Lychee application for the framework.
+ * These include at least the methods of the HTTP controllers and the methods
+ * of the console commands.
+ *
+ * Note, that messages of exceptions inherited from this class are presented
+ * to the (end) user: either via the CLI or a browser.
+ * Hence, the derived exceptions and messages should sufficiently hide
+ * internal implementation details, but still helpful for an ordinary user.
```
Comment (kamil4) [inline app/Exceptions/LycheeBaseException.php]:
```suggestion
 * internal implementation details, but still be helpful for an ordinary user.
```

File: app/Exceptions/LycheeBaseException.php [hunk 29]
```diff
@@ -0,0 +1,58 @@
...
+ * Moreover, due to security considerations internal information (like paths,
```
Comment (kamil4) [inline app/Exceptions/LycheeBaseException.php]:
```suggestion
 * Moreover, due to security considerations, internal information (like paths,
```

File: app/Exceptions/LycheeBaseException.php [hunk 30]
```diff
@@ -0,0 +1,58 @@
...
+ * values of variables, control flows) should not be exposed.
+ * However, those internal details might be chained into the previous
+ * exception.
+ *
+ * The framework ensures that only the message of this exception is
+ * printed if the application runs in productive mode.
```
Comment (kamil4) [inline app/Exceptions/LycheeBaseException.php]:
```suggestion
 * printed if the application runs in production mode.
```

File: app/Exceptions/UnauthenticatedException.php [hunk 31]
```diff
@@ -0,0 +1,30 @@
...
+{
+	public const DEFAULT_MESSAGE = 'User is not authenticated';
+
+	public function __construct(string $msg = self::DEFAULT_MESSAGE, \Throwable $previous = null)
+	{
+		// Note: Due to historic reasons the name of the HTTP Status Code 401
+		// is "unauthorized", but actually means "unauthenticated".
+		// So it is correct, to use HTTP_UNAUTHORIZED here.
+		// Side remark: If one wants to express that a user is unauthorized,
+		// the HTTP Status Code would equal 403 (HTTP_FORBIDDEN).
```
Comment (kamil4) [inline app/Exceptions/UnauthenticatedException.php]: This comment repeats some 10 lines earlier in the same file. Maybe keep just one copy?

File: app/Factories/AlbumFactory.php [hunk 32]
```diff
@@ -80,35 +88,90 @@ public function findModelOrFail(string $albumId, bool $withRelations = true): Ba
...
 		$modelAlbumIDs = array_diff($albumIDs, array_keys(self::BUILTIN_SMARTS));
 
 		$smartAlbums = [];
 		foreach ($smartAlbumIDs as $smartID) {
-			$smartAlbums[] = $this->createSmartAlbum($smartID);
+			try {
+				$smartAlbums[] = $this->createSmartAlbum($smartID, $withRelations);
+			} catch (InvalidSmartIdException) {
+				// must not happen, because we limited search to
+				// `self::BUILTIN_SMARTS` above
```
Comment (kamil4) [inline app/Factories/AlbumFactory.php]: Is there nothing like `assert` in PHP to indicate such _must not happen_ cases?

File: app/Http/Controllers/Administration/SettingsController.php [hunk 33]
```diff
@@ -160,199 +157,214 @@ public function setNSFWVisible(Request $request)
...
-	 * @return string
+	 * @return void
+	 *
+	 * @throws InvalidConfigOption
 	 */
-	public function setMapProvider(Request $request)
+	public function setMapProvider(Request $request): void
 	{
-		$request->validate(['map_provider' => 'required|string']);
+		// TODO: It seems as if the configuration option `map_provider` is not read anywhere; do we need it?
```
Comment (kamil4) [inline app/Http/Controllers/Administration/SettingsController.php]: Yes. It's used by the front end.

File: app/Actions/Album/Archive.php (hunk 13 above)
Comment (kamil4) [reply app/Actions/Album/Archive.php]: Sorry, I still don't understand when exactly that's needed. We have the following two conditions right below:
```
($album instanceof BaseSmartAlbum && AccessControl::is_logged_in()) ||
($album instanceof BaseAlbum && AccessControl::is_current_user($album->owner_id));
```
Don't they always trigger for an admin?

Comment (nagmat84) [reply app/Actions/Album/Archive.php]: You are right. `is_current_user` also returns true, if the currently authenticated user is not the owner but the admin. I have been mislead by another unfortunate named method.

However, if we are going to replace the session management by the proper Laravel component, then this code needs to be revised again anyway. I feel as if this code make more explicit what the desired outcome should be.

I can revert the change or keep it. I don't mind either way. What do you propose?

File: app/Exceptions/UnauthenticatedException.php (hunk 31 above)
Comment (nagmat84) [reply app/Exceptions/UnauthenticatedException.php]: Sure, I will delete it.

File: app/Factories/AlbumFactory.php (hunk 32 above)
Comment (nagmat84) [reply app/Factories/AlbumFactory.php]: Indeed, it is. Thank you for reminding me. Why haven't I thought of that myself in the first place?! I will commit a change.

File: app/Http/Controllers/Administration/SettingsController.php (hunk 33 above)
Comment (nagmat84) [reply app/Http/Controllers/Administration/SettingsController.php]: I will revise the comment.

File: app/Http/Controllers/AlbumController.php [hunk 34]
```diff
@@ -5,344 +5,308 @@
...
 	/**
 	 * Set if an album contains sensitive pictures.
 	 *
-	 * @param AlbumIDRequest $request
-	 * @param SetNSFW        $setNSFW
+	 * This method is either a misnomer and should rather be called
+	 * `toggleNSFW` or the request `SetAlbumNSFWRequest` should contain an
+	 * explicit boolean with the new NSFW state.
+	 *
+	 * TODO: Fix the method, see above.
```
Comment (kamil4) [inline app/Http/Controllers/AlbumController.php]: Just my $0.02: I don't like toggle methods, and especially when there's an unreliable network between the client and the server. I vote for adding a boolean argument.

File: app/Actions/Album/Archive.php (hunk 13 above)
Comment (kamil4) [reply app/Actions/Album/Archive.php]: Yeah, `is_current_user` is a bit hackish functionality-wise, or at least the name is confusing, but it's _such_ a useful shortcut... We use it all-over...

So are you saying that if we move to the Laravel session management, we will need to add "or admin" to all such tests? That's a bit unfortunate, though of course so long as we do it in one go, it's not a big deal... Anyway, if that's the case, then we may just as well keep the change...

File: app/Http/Controllers/ImportController.php [hunk 35]
```diff
@@ -1,54 +1,80 @@
...
-use ImagickException;
+use Symfony\Component\HttpFoundation\StreamedResponse;
 
+/**
+ * Class ImportController.
+ *
+ * This controller handles requests to import photos from a sequence of
+ * URLs or from a local path on the server.
+ *
+ * Note, the return types of the methods is quite differently.
```
Comment (kamil4) [inline app/Http/Controllers/ImportController.php]: I'm not even sure how to rewrite it, but it doesn't read well :wink:.

File: app/Http/Controllers/ImportController.php [hunk 36]
```diff
@@ -1,54 +1,80 @@
...
+ * While {@link ImportController::server()} returns a streamed response with
+ * intermediate updates, {@link ImportController::url} returns an atomic
+ * response at the end.
+ * The former approach appears to be more appropriate in order to avoid
+ * timeout errors at the client side.
+ * While {@link ImportController::url} returns a well-formed and
+ * syntactically valid JSON response which is a properly serialized collection
+ * of the imported photos, {@link ImportController::server()} just streams
+ * the terminal output of the command line.
+ * The latter cannot properly be interpreted by web-clients client which
```
Comment (kamil4) [inline app/Http/Controllers/ImportController.php]:
```suggestion
 * The latter cannot properly be interpreted by web-clients which
```

File: app/Http/Controllers/ImportController.php [hunk 37]
```diff
@@ -1,54 +1,80 @@
...
+ * expect a proper JSON response.
+ * Actually, both methods should be re-factored such that their return
+ * types are consistent and the best of both worlds: a streamed collection.
+ * In other words, the streamed response should immediately send back a
+ * `[`-character to the client (the beginning of the collection), then
+ * send back a JSONized {@link Photo} as soon as it has been imported
+ * (element of the collection, and send a final `]`-character (the end of
+ * the collection).
```
Comment (kamil4) [inline app/Http/Controllers/ImportController.php:42]: Such format would effectively prevent the client from displaying the percentage of completion like it does now, although that percentage is not terribly useful as it is local to the current folder (i.e., for each subfolder it goes from 0 to 100).

More usefully, the current format shows which directory is being imported at the moment, and it provides meaningful errors/warnings ("Skipped duplicate XYZ", "Invalid file format XYZ", etc). Won't we lose that with what you propose?

And a bit of a historical perspective: I'm the one who added interim progress notifications on "Import from Server" to the web client. It was later extended to handle CLI as well (I believe we didn't even have CLI import capability at first). I never bothered with "Import from URL" probably because the interface does not encourage providing multiple URLs so I didn't think it was worth improving that aspect.

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (nagmat84) [reply app/Http/Controllers/AlbumController.php]: Totally agreed, but that the NSFW attribute is being toggled instead of set explicitly has not been invented by me.

I fixed the that problem for `setPublic` of a single photo which suffered from the same problem.

**Current situation on master for "setPublic" (note that `setPublic` actually means "toggle"):**

https://github.com/LycheeOrg/Lychee/blob/05f21d48bd7205016c7b8618da711c4d7cf4d959/app/Actions/Photo/Toggle.php#L25-L30

and

https://github.com/LycheeOrg/Lychee/blob/05f21d48bd7205016c7b8618da711c4d7cf4d959/app/Actions/Photo/SetPublic.php#L5-L11

**New situation for "setPublic"**

https://github.com/LycheeOrg/Lychee/blob/89a948323c786c0bc41bcddd2c9c3a15cda9ea3f/app/Http/Controllers/PhotoController.php#L172-L176

**Problems**

It crossed my mind just now that I could have done the same for `Albums::setNSFW` because it only affects a single instance of an album. However, we also have some `set...`-methods, like `toggleStar` which toggles but for _multiple photos_. See here:

https://github.com/LycheeOrg/Lychee-front/blob/d7f12fb3ccf94133c41111b47b14bea4c644e51e/scripts/main/photo.js#L526-L540

I wonder what we should do with that. I never have tested it myself with the frontend what happens if one selects multiple photos and clicks the star button. Is this supported at all for multiple photos?

File: app/Http/Controllers/ImportController.php (hunk 35 above)
Comment (nagmat84) [reply app/Http/Controllers/ImportController.php]: I will rephrase the sentence.

File: app/Http/Controllers/ImportController.php (hunk 37 above)
Comment (nagmat84) [reply app/Http/Controllers/ImportController.php:42]: > Such format would effectively prevent the client from displaying the percentage of completion like it does now, although that percentage is not terribly useful as it is local to the current folder (i.e., for each subfolder it goes from 0 to 100).

No, it does not. It still works and even better than before. Just try it or have a look at the at the following code snippets: 

 - [`upload.start.server.action.runUpload.progressHandler`](https://github.com/LycheeOrg/Lychee-front/blob/d7f12fb3ccf94133c41111b47b14bea4c644e51e/scripts/main/upload.js#L658-L700)
 - [`upload.start.server.action.runUpload.processIncremental`](https://github.com/LycheeOrg/Lychee-front/blob/d7f12fb3ccf94133c41111b47b14bea4c644e51e/scripts/main/upload.js#L519-L526)

It is even much nicer and more type-safe than before, because we have proper JSON objects `ImportProgessReport` and `ImportEventReport` and use standard JSON encoding/decoding methods. So no problem with dangerous characters in strings (i.e. paths) anymore.
 
> More usefully, the current format shows which directory is being imported at the moment, and it provides meaningful errors/warnings ("Skipped duplicate XYZ", "Invalid file format XYZ", etc). Won't we lose that with what you propose?

Nope. See

- [`App\DTO\ImportReport`](https://github.com/LycheeOrg/Lychee/blob/6e13c20f644cf86a233ef617dc22928a8500e7bc/app/DTO/ImportReport.php)
- [`App\DTO\ImportProgressReport`](https://github.com/LycheeOrg/Lychee/blob/6e13c20f644cf86a233ef617dc22928a8500e7bc/app/DTO/ImportProgressReport.php)
- [`App\DTO\ImportEventReport`](https://github.com/LycheeOrg/Lychee/blob/6e13c20f644cf86a233ef617dc22928a8500e7bc/app/DTO/ImportEventReport.php)

for the backend side.

Basically, the backend streams a JSON array with proper report objects to the client. Report objects either indicate singular events or cumulative progress reports. The client receives this JSON array and progressively decodes the JSON stream (i.e. it decodes as much from the array as it can, because the array is truncated).

As a nice side effect we also get a readable response in the developer tools of the browser.

> And a bit of a historical perspective: I'm the one who added interim progress notifications on "Import from Server" to the web client. It was later extended to handle CLI as well (I believe we didn't even have CLI import capability at first). I never bothered with "Import from URL" probably because the interface does not encourage providing multiple URLs so I didn't think it was worth improving that aspect.

Not entirely correct. The interface does support multiple URLs, see

 - [`upload.start.url.action.runImport`](https://github.com/LycheeOrg/Lychee-front/blob/d7f12fb3ccf94133c41111b47b14bea4c644e51e/scripts/main/upload.js#L394-L421).
 - [`upload.start.dropbox.action.runImport`](https://github.com/LycheeOrg/Lychee-front/blob/d7f12fb3ccf94133c41111b47b14bea4c644e51e/scripts/main/upload.js#L835-L846)

It is only the frontend which just sends a single-valued array of URLs in case of import from ordinary URLs, because the dialog only allows to enter a single URL. But even for a single URL, I experienced timeout problems occasionally. I have never used the Dropbox feature myself, but this has to fail with a timeout for more than a couple of files.

File: app/Factories/AlbumFactory.php (hunk 32 above)
Comment (nagmat84) [reply app/Factories/AlbumFactory.php]: Done in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/89a948323c786c0bc41bcddd2c9c3a15cda9ea3f

File: app/Http/Controllers/Administration/SettingsController.php (hunk 33 above)
Comment (nagmat84) [reply app/Http/Controllers/Administration/SettingsController.php]: Done in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/89a948323c786c0bc41bcddd2c9c3a15cda9ea3f

File: app/Http/Controllers/ImportController.php (hunk 35 above)
Comment (nagmat84) [reply app/Http/Controllers/ImportController.php]: Done in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/c034f313bdc29e8de8e367fac4ea208107b07953

File: app/Actions/Album/Archive.php (hunk 13 above)
Comment (nagmat84) [reply app/Actions/Album/Archive.php]: > So are you saying that if we move to the Laravel session management, we will need to add "or admin" to all such tests?

No, I did not want to imply that. I haven't had a look into the method which are negatively provided by Laravel yet. Even if there was not such a method, we could still add our own decorator methods.

What I wanted to say it that the explicit check for admin might help as a reminder to not fall into this pit when we migrate. But you have convinced me to simply rename the method properly.

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (ildyria) [reply app/Http/Controllers/AlbumController.php]: > what happens if one selects multiple photos and clicks the star button.

This will not happen, the star button is only available in photo header, not in album header if I remember correctly.

File: app/Actions/Album/Archive.php (hunk 13 above)
Comment (nagmat84) [reply app/Actions/Album/Archive.php]: Done in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/073424326c476ccb0ce75077845387ccec75bf44

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (nagmat84) [reply app/Http/Controllers/AlbumController.php]: The action is also available in the album view from the context menu. You can select multiple photos in the album view, do a right click and then select "Mark as favorites". The action is actually also a misnomer, because you don't unconditionally mark the photos as favorites, but the status is toggled.

I just tried it. I even selected a mix of starred and unstarred photos and after the action the stars are inverted. 

However, I wonder if this is what _should_ happen. IMHO, this function is awkward. I could imagine several better alternatives:

- Select multiple photos, but the status of the last photo counts for all and determines whether the star is set or unset.
- Deactivate the method if multiple photos are selected and only provide the method for single photos. I completely understand that one would like to have this method available in the album view when one has an overview of all photos. But is it actually a use case to a) first select several photos with the mouse and then b) invoke "Mark as favorites" from the context menu? In this case one could also simple mark each photo one after another.

Comment (ildyria) [reply app/Http/Controllers/AlbumController.php]: Definitively NOT the expected behavior. :')

Comment (nagmat84) [reply app/Http/Controllers/AlbumController.php]: Which one?

Comment (nagmat84) [reply app/Http/Controllers/AlbumController.php]: Done in https://github.com/LycheeOrg/Lychee/pull/1217/commits/15374daa8b425704da2385549ac0b3ee6be2f98c and in https://github.com/LycheeOrg/Lychee-front/pull/282/commits/e712c60761d6bcc5428e34f729f2974262fa04fe.

Comment (kamil4) [reply app/Http/Controllers/AlbumController.php]: I had only a brief look at the commit and I like most of it but I'm not sure about what looks like adding a separate "Set" and "Unset" options to the multi-select context menu. Honestly, I think we should completely remove starring in that case (so, your second alternative above). We could also leave a (properly labeled) "Toggle Star Selected" in case all the selected photos are either starred or unstarred -- or, if we wanted to be _real_ fancy, display it as either "Star Selected" or "Unstar Selected" depending on the condition of the selected photos. While doing that, I would also get rid of "Rename Selected" -- it strikes me as completely pointless. But we can do that after this PR, of course.

File: app/Http/Controllers/ImportController.php (hunk 37 above)
Comment (kamil4) [reply app/Http/Controllers/ImportController.php:42]: Sorry, that's what I get for speaking up before looking over the whole PR... I misunderstood that you were planning to send back `Photo` objects only and nothing else...

I was actually under the impression that, at least with the front end on `master`, one _can_ provide multiple URLs by comma-separating them in the input box. But it's such a crude interface that I honestly can't imagine that anyone would bother, so I felt disinclined to improve server support for it.

As an aside, I am a little surprised how easily you seem to experience timeouts. I saw a mention of 500ms in one of the comments? I thought that just gives you a warning in the debug console -- don't true timeouts start at like 30s or even more?

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (nagmat84) [reply app/Http/Controllers/AlbumController.php]: > Honestly, I think we should completely remove starring in that case (so, your second alternative above)

That would also have been my first choice, but I feared that some users might start yelling, because we removed a feature. But it would be so much more consistent with other binary attributes like NSFW, etc.

> We could also leave a (properly labeled) "Toggle Star Selected" in case all the selected photos are either starred or unstarred -- or, if we wanted to be real fancy, display it as either "Star Selected" or "Unstar Selected" depending on the condition of the selected photos.

That was what I wanted to implement as an alternative to my first choice above until I noticed that this isn't possible efficiently. The main obstacle is that in the album view we we don't have any efficient access to the selected photos (we only have the photos IDs) and thus we cannot _efficiently_ determine wether all are starred or unstarred. Hence, we can only submit a request to star/unstar the set of photos belonging to the IDs without looking at their current state.

That is why I decided to add both options. I don't like it either. I would rather prefer to use the first solution, i.e. completely remove the option.

I assume that this is also the reason why the previous and unfortunate option "Toggle star" made it. It simply asks the sever to toggle the star attribute of a set of photos with a possibly mixed set of attributes without being aware of it. An old comment in the code said "ugly, but efficient".

File: app/Http/Controllers/ImportController.php (hunk 37 above)
Comment (nagmat84) [reply app/Http/Controllers/ImportController.php:42]: > Sorry, that's what I get for speaking up before looking over the whole PR... I misunderstood that you were planning to send back `Photo` objects only and nothing else...

No problem. Better be thoroughly. Besides adding a lot of jsDoc comments to the entire frontend code, most of the actual changes in the frontend went into revising the processing of the streamed response.

I am allergic to home-brewed encodings schemes, so I decided to replace it by something proper. It always tends to shoot you in the foot after some time (see the "XSS atack" reported recently, the problems with the markdown support and the unfortunate `lychee.html`-method).

I know that the whole code is "historically grown" or "legacy" and no single individual is responsible for the situation the code was in. I was also wondering if it was worth the effort to revise it with the emerging Livewire frontend at the horizon. But at least this approach also provides a template how the web installer can be improved and how the web installer may stream the actual console commands to the frontend.

> I was actually under the impression that, at least with the front end on `master`, one _can_ provide multiple URLs by comma-separating them in the input box. But it's such a crude interface that I honestly can't imagine that anyone would bother, so I felt disinclined to improve server support for it.

No at the moment you can't. However, there is a pending PR #1153 which tried to add such support for importing from the server. 

> As an aside, I am a little surprised how easily you seem to experience timeouts. I saw a mention of 500ms in one of the comments?

Good question. Maybe I set an option in "about:config" in the past which reduced the timeout value or it is system-dependent? I don't know. But I don't mind. It forces you to be careful what you code.

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (kamil4) [reply app/Http/Controllers/AlbumController.php]: I suggest that we leave it as-is for now and when I get to the front end PR and then to testing I'll see if I can figure out a way to improve it.

File: app/Http/Controllers/ImportController.php (hunk 37 above)
Comment (kamil4) [reply app/Http/Controllers/ImportController.php:42]: No worries; I'm not emotionally attached to my home-brewed encoding scheme :wink: so I'm happy to see it replaced with something better.

FYI, I just tried entering two image URLs to "Import from Link" on `master` and it worked as I thought: both images were imported. It sounds like that's no longer the case with your PR? I'm sure we could fix that but honestly, I don't care: I wonder if more than three people in the world knew about that capability...

File: app/Http/Controllers/SearchController.php [hunk 38]
```diff
@@ -1,64 +1,46 @@
...
-		foreach ($terms as $term) {
-			$escaped_terms[] = $this->escape_like($term);
-		}
-
-		// Initialize return var
 		$return = [];
-		$return['albums'] = $albumSearch->query($escaped_terms);
-		$return['photos'] = $photoSearch->query($escaped_terms);
-		$return['hash'] = md5(json_encode($return));
+		// For efficiency reasons, we call directly call `toArray` here,
```
Comment (kamil4) [inline app/Http/Controllers/SearchController.php]:
```suggestion
		// For efficiency reasons, we directly call `toArray` here,
```

File: app/Http/Middleware/ContentType.php [hunk 39]
```diff
@@ -0,0 +1,51 @@
...
+	 * @throws LycheeInvalidArgumentException
+	 */
+	public function handle(Request $request, \Closure $next, string $contentType): mixed
+	{
+		if ($contentType === self::JSON) {
+			if (!$request->isJson()) {
+				throw new UnexpectedContentType(self::JSON);
+			}
+		} elseif ($contentType === self::MULTIPART) {
+			if ($request->getContentType() !== 'form') {
```
Comment (kamil4) [inline app/Http/Middleware/ContentType.php:42]: Does that happen during photo upload? If so, perhaps add a comment to that effect. Also, the code contradicts a comment from ~30 lines earlier that only json is supported...

File: app/Http/Middleware/MigrationStatus.php [hunk 40]
```diff
@@ -0,0 +1,70 @@
...
+
+/**
+ * Class MigrationStatus.
+ *
+ * This middleware ensures that the migration has the required status.
+ * If the migration has the required status, then the request passes
+ * unchanged.
+ * If the required status equals `:complete` but the installation is
+ * incomplete, then the client is redirected to the installation pages.
+ * If the required status equals `:incomplete` but the installation is
```
Comment (kamil4) [inline app/Http/Middleware/MigrationStatus.php]:
```suggestion
 * If the required status equals `:complete` but the migration is
 * incomplete, then the client is redirected to the migration page.
 * If the required status equals `:incomplete` but the migration is
```

File: app/Http/Requests/Album/AddTagAlbumRequest.php [hunk 41]
```diff
@@ -0,0 +1,48 @@
...
+	use HasTitleTrait;
+	use HasTagsTrait;
+
+	/**
+	 * {@inheritDoc}
+	 */
+	public function authorize(): bool
+	{
+		// Sic!
+		// Tag albums can only be created below the root albums which has the
```
Comment (kamil4) [inline app/Http/Requests/Album/AddTagAlbumRequest.php]:
```suggestion
		// Tag albums can only be created below the root album which has the
```

File: app/Http/Requests/Album/AddTagAlbumRequest.php [hunk 42]
```diff
@@ -0,0 +1,48 @@
...
+
+	/**
+	 * {@inheritDoc}
+	 */
+	public function rules(): array
+	{
+		return [
+			HasTitle::TITLE_ATTRIBUTE => ['required', new TitleRule()],
+			HasTags::TAGS_ATTRIBUTE => 'required|array|min:1',
+			HasTags::TAGS_ATTRIBUTE . '.*' => 'required|string|min:1',
```
Comment (kamil4) [inline app/Http/Requests/Album/AddTagAlbumRequest.php:36]: ???

File: app/Http/Requests/Album/ArchiveAlbumsRequest.php [hunk 43]
```diff
@@ -0,0 +1,46 @@
...
+	}
+
+	/**
+	 * {@inheritDoc}
+	 */
+	protected function processValidatedValues(array $values, array $files): void
+	{
+		// TODO: `App\Actions\Album\Archive::compressAlbum` iterates over the original size variant of each photo in the album; we should eagerly load them for higher efficiency.
+		$this->albums = $this->albumFactory->findAbstractAlbumsOrFail(
+			explode(',', $values[HasAlbums::ALBUM_IDS_ATTRIBUTE])
```
Comment (kamil4) [inline app/Http/Requests/Album/ArchiveAlbumsRequest.php:43]: Why isn't the album list passed as a proper array?

File: app/Http/Requests/Album/SetAlbumTagsRequest.php [hunk 44]
```diff
@@ -0,0 +1,53 @@
...
+use App\Models\TagAlbum;
+use App\Rules\RandomIDRule;
+
+class SetAlbumTagsRequest extends BaseApiRequest implements HasTagAlbum, HasTags
+{
+	use HasTagAlbumTrait;
+	use HasTagsTrait;
+
+	/**
+	 * For historic reasons the parameter of the API is called `show_tags`
```
Comment (kamil4) [inline app/Http/Requests/Album/SetAlbumTagsRequest.php]:
```suggestion
	 * For historical reasons the parameter of the API is called `show_tags`
```

But actually, since you are cleaning up the API anyway, wouldn't it make sense to get rid of any such "historical reasons"?

File: app/Http/Requests/BaseApiRequest.php [hunk 45]
```diff
@@ -0,0 +1,310 @@
...
+	}
+
+	/**
+	 * Validate the class instance.
+	 *
+	 * Fixes another Laravel stupidity.
+	 * We must **first** validate the input parameters of the request
+	 * for syntactical correctness, and **then** authorize the request.
+	 * Rationale: Whether a user is authorized to perform a specific action or
+	 * not typically depend on the input parameters (e.g. the ID of the model,
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * not typically depends on the input parameters (e.g. the ID of the model,
```

File: app/Http/Requests/BaseApiRequest.php [hunk 46]
```diff
@@ -0,0 +1,310 @@
...
+	 * @throws UnauthorizedException
+	 * @throws UnauthenticatedException
+	 */
+	protected function failedAuthorization(): void
+	{
+		throw AccessControl::is_logged_in() ? new UnauthorizedException() : new UnauthenticatedException();
+	}
+
+	/**
+	 * Determines of the user is authorized to access the designated album.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to access the designated album.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 47]
```diff
@@ -0,0 +1,310 @@
...
+	 *
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	protected function authorizeAlbumAccess(?AbstractAlbum $album): bool
+	{
+		return $this->albumAuthorisationProvider->isAccessible($album);
+	}
+
+	/**
+	 * Determines of the user is authorized to access the designated album.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to access the designated albums.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 48]
```diff
@@ -0,0 +1,310 @@
...
+			if (!$this->authorizeAlbumAccess($album)) {
+				return false;
+			}
+		}
+
+		return true;
+	}
+
+	/**
+	 * Determines of the user is authorized to modify or write into the
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to modify or write into the
```

File: app/Http/Requests/BaseApiRequest.php [hunk 49]
```diff
@@ -0,0 +1,310 @@
...
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	protected function authorizeAlbumWrite(?AbstractAlbum $album): bool
+	{
+		return $this->albumAuthorisationProvider->isEditable($album);
+	}
+
+	/**
+	 * Determines of the user is authorized to modify or write into the
+	 * designated album.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to modify or write into the
	 * designated albums.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 50]
```diff
@@ -0,0 +1,310 @@
...
+			if (!$this->authorizeAlbumWrite($album)) {
+				return false;
+			}
+		}
+
+		return true;
+	}
+
+	/**
+	 * Determines of the user is authorized to see the designated photo.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to see the designated photo.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 51]
```diff
@@ -0,0 +1,310 @@
...
+	 *
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	protected function authorizePhotoVisible(?Photo $photo): bool
+	{
+		return $this->photoAuthorisationProvider->isVisible($photo);
+	}
+
+	/**
+	 * Determines of the user is authorized to download the designated photo.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to download the designated photo.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 52]
```diff
@@ -0,0 +1,310 @@
...
+	 *
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	protected function authorizePhotoDownload(Photo $photo): bool
+	{
+		return $this->photoAuthorisationProvider->isDownloadable($photo);
+	}
+
+	/**
+	 * Determines of the user is authorized to download the designated photos.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to download the designated photos.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 53]
```diff
@@ -0,0 +1,310 @@
...
+			if (!$this->authorizePhotoDownload($photo)) {
+				return false;
+			}
+		}
+
+		return true;
+	}
+
+	/**
+	 * Determines of the user is authorized to modify the designated photo.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to modify the designated photo.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 54]
```diff
@@ -0,0 +1,310 @@
...
+	 *
+	 * @return bool true, if the authenticated user is authorized
+	 */
+	protected function authorizePhotoWrite(Photo $photo): bool
+	{
+		return $this->photoAuthorisationProvider->isEditable($photo);
+	}
+
+	/**
+	 * Determines of the user is authorized to modify the designated photos.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php]:
```suggestion
	 * Determines if the user is authorized to modify the designated photos.
```

File: app/Http/Requests/BaseApiRequest.php [hunk 55]
```diff
@@ -0,0 +1,310 @@
...
+		}
+
+		return true;
+	}
+
+	/**
+	 * Converts the input value to a boolean.
+	 *
+	 * Opposed to trivial type-casting the conversion also correctly recognizes
+	 * the inputs `0`, `1`, `'0'`, `'1'`, `'true'` and `'false'`.
```
Comment (kamil4) [inline app/Http/Requests/BaseApiRequest.php:297]: I'm assuming that's for legacy reasons? Wouldn't it be better to eliminate any such cases during this cleanup and only accept proper boolean values? Or were there simply too many?

File: app/Http/Requests/Contracts/HasSizeVariant.php [hunk 56]
```diff
@@ -0,0 +1,24 @@
...
+	/**
+	 * Due to historic reasons the attribute which stores the type of
+	 * size variant is called `kind`.
+	 * Note that the designation `kind` is excessively used for various
+	 * things with different semantic meanings.
+	 * In other contexts, `kind` may also refer to the category of media
+	 * object (i.e. `'photo'` versus `'video'`) or the specific MIME type
+	 * (i.e. `'image/jpeg'`, `'image/png'`, etc.).
+	 *
+	 * TODO: Maybe rename the attribute in the back- and front-end to avoid overloading the same term.
```
Comment (kamil4) [inline app/Http/Requests/Contracts/HasSizeVariant.php:16]: :+1:

File: app/Http/Requests/Import/ImportFromUrlRequest.php [hunk 57]
```diff
@@ -0,0 +1,71 @@
...
+			Album::query()->findOrFail($albumID);
+		// The replacement below looks suspicious.
+		// If it was really necessary, then there would be much more special
+		// characters (e.i. for example umlauts in international domain names)
+		// which would require replacement by their corresponding %-encoding.
+		// However, I assume that the PHP method `fopen` is happily fine with
+		// any character and internally handles special characters itself.
+		// Hence, either use a proper encoding method here instead of our
+		// home-brewed, poor-man replacement or drop it entirely.
+		// TODO: Find out what is needed and proceed accordingly.
```
Comment (kamil4) [inline app/Http/Requests/Import/ImportFromUrlRequest.php:60]: +100

**Review by kamil4 — COMMENTED** [review]
I don't really understand what those `'.*'` rules in requests are for, and I believe there was at least one that I would've expected to be an array but was kept a `,`-separated string, again for reasons I don't understand, so I would appreciate an explanation. It feels like we should clean up all the legacy aspects from this API, although I can certainly understand that in specific circumstances it may simply not be worth the effort...

File: app/Http/Middleware/ContentType.php (hunk 39 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:42]: Yes, you are right. Initially, I wanted everything to be JSON. In theory, you can even upload files via JSON, but this isn't supported by any browser. (It also create a lot of encoding overhead.) So I needed to add support for `multipart/form-data` later and forgot to update the initial comment above.

File: app/Http/Requests/Album/AddTagAlbumRequest.php (hunk 42 above)
Comment (nagmat84) [reply app/Http/Requests/Album/AddTagAlbumRequest.php:36]: I believe you are wondering about the `.* ` syntax? The asterisk applies to the value _inside_ the array. E.g. if you have a JSON object like this

```json
{
  "title": "my title",
  "tags": [ "tag_1", "tag 2" ]
}
```

The validation rule `'tags' => 'required|array|min'` ensures that `tags` is an array with at least one element, `'tags.*' => 'required|string|min:1' ` ensures that every element _inside_ the array is string with at least one character.

See here: https://laravel.com/docs/9.x/validation#validating-nested-array-input

File: app/Http/Requests/Album/ArchiveAlbumsRequest.php (hunk 43 above)
Comment (nagmat84) [reply app/Http/Requests/Album/ArchiveAlbumsRequest.php:43]: Because, the browser needs to download the final zip file and ask the user where to store it.

Hence, the frontend code redirects the browser to a "normal" URL and the browser triggers an ordinary GET-request by itself. As the GET request must not have any body, the IDs must be part of the URL and the simplest way to encode all the IDs in the URL is as a comma-separated string. See here:

See here: https://github.com/LycheeOrg/Lychee-front/blob/e712c60761d6bcc5428e34f729f2974262fa04fe/scripts/main/album.js#L1083-L1089

Same holds for archiving of photos.

I would be more than happy to have proper JSON request everywhere. If you know a way how to make an AJAX request by the frontend, but don't parse the response programmatically, but let the browser "download" it (i.e. store it in a file), I am all yours.

File: app/Http/Requests/Album/AddTagAlbumRequest.php (hunk 42 above)
Comment (kamil4) [reply app/Http/Requests/Album/AddTagAlbumRequest.php:36]: Thanks for the explanation!

File: app/Http/Requests/BaseApiRequest.php (hunk 55 above)
Comment (nagmat84) [reply app/Http/Requests/BaseApiRequest.php:297]: At least at one place we don't let the client sent JSON, but a form request (for uploading photos). The other attributes in that request (i.e. the form data, not the file) are all encoded as strings. A browser sends the string `"true"`. This is how `multipart/form-data` works.

File: app/Http/Requests/Album/ArchiveAlbumsRequest.php (hunk 43 above)
Comment (kamil4) [reply app/Http/Requests/Album/ArchiveAlbumsRequest.php:43]: Right, I forgot that the archiving requests are special. So that's why they use GET and not POST like most of the rest of the API? I was going to ask if this is something we should unify but, by the sound of it, it is the way it is for good reasons...

**Comment by nagmat84** [comment]
> I don't really understand what those `'.*'` rules in requests are for

See answer here: https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r833659389

> and I believe there was at least one that I would've expected to be an array but was kept a `,`-separated string, again for reasons I don't understand, so I would appreciate an explanation.

See answer here: https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r833669481

> It feels like we should clean up all the legacy aspects from this API, although I can certainly understand that in specific circumstances it may simply not be worth the effort...

Totally agreed and I even did that in the first place before I started to work on the frontend code. Unfortunately, in this two cases it is not the fault of legacy frontend code, but simply due to restrictions of how browsers work.

**Comment by kamil4** [comment]
> Totally agreed and I even did that in the first place before I started to work on the frontend code. Unfortunately, in this two cases it is not the fault of legacy frontend code, but simply due to restrictions of how browsers work.

Yeah, I now remember trying to change the form request to json at one point in the frontend, but I couldn't get it to work...

File: app/Image/ImagickHandler.php [hunk 58]
```diff
@@ -110,7 +113,6 @@ public function scale(
 			}
 
 			$image->writeImage($destination);
-			Logs::notice(__METHOD__, __LINE__, 'Saving thumb to ' . $destination);
```
Comment (kamil4) [inline app/Image/ImagickHandler.php:113]: Thank you! :wink:

File: app/Image/SizeVariantDefaultFactory.php [hunk 59]
```diff
@@ -358,8 +381,11 @@ protected function getMaxDimensions(int $sizeVariant): array
 	 * configurable and are always enabled (e.g. a thumb).
 	 * Hence, it is save to call this function for all size variants.
```
Comment (kamil4) [inline app/Image/SizeVariantDefaultFactory.php]:
```suggestion
	 * Hence, it is safe to call this function for all size variants.
```
Not your edit but it was visible in the context diff...

File: app/Image/SizeVariantDefaultFactory.php [hunk 60]
```diff
@@ -358,8 +381,11 @@ protected function getMaxDimensions(int $sizeVariant): array
...
 	 * For size variants which may be enabled/disabled trough configuration at
```
Comment (kamil4) [inline app/Image/SizeVariantDefaultFactory.php]:
```suggestion
	 * For size variants which may be enabled/disabled through configuration at
```
Likewise...

File: app/Http/Middleware/ContentType.php (hunk 39 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:42]: Fixed in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/5901299fdb9aa6934c5d3076403d50a9a39e97c2

File: app/Metadata/Extractor.php [hunk 61]
```diff
@@ -120,47 +130,58 @@ public function extract(string $fullPath, string $kind): array
...
 
-		try {
-			// this can throw an exception in the case of Exiftool adapter!
 			$exif = $reader->read($fullPath);
-		} catch (\Exception $e) {
-			Logs::error(__METHOD__, __LINE__, $e->getMessage());
+		} catch (\InvalidArgumentException|NoAdapterException $e) {
+			throw new ExternalComponentMissingException('The configured EXIF adapter is not available', $e);
+		} catch (\RuntimeException $e) {
+			// thrown be $reader->read if EXIF could not be extracted,
```
Comment (kamil4) [inline app/Metadata/Extractor.php]:
```suggestion
			// thrown by $reader->read if EXIF could not be extracted,
```

File: app/Metadata/Extractor.php [hunk 62]
```diff
@@ -120,47 +130,58 @@ public function extract(string $fullPath, string $kind): array
...
-			$exif = $reader->read($fullPath);
+			try {
+				Logs::notice(__METHOD__, __LINE__, 'Falling back to native adapter.');
+				// Use Php native tools
+				$reader = Reader::factory(Reader::TYPE_NATIVE);
+				$exif = $reader->read($fullPath);
+			} catch (\InvalidArgumentException|NoAdapterException $e) {
+				throw new ExternalComponentMissingException('The configured EXIF adapter is not available', $e);
+			} catch (\RuntimeException $e) {
+				// thrown be $reader->read if EXIF could not be extracted,
```
Comment (kamil4) [inline app/Metadata/Extractor.php]:
```suggestion
				// thrown by $reader->read if EXIF could not be extracted,
```

File: app/Metadata/LycheeVersion.php [hunk 63]
```diff
@@ -49,90 +44,54 @@ private function fetchReleaseInfo()
...
+		return Version::createFromString(
+			file_get_contents(base_path('version.md'))
+		);
 	}
 
 	/**
 	 * Return the information with respect to Lychee.
 	 *
-	 * @return array
+	 * @return LycheeChannelInfo the version of lychee or null if not git data could be found
```
Comment (kamil4) [inline app/Metadata/LycheeVersion.php]:
```suggestion
	 * @return LycheeChannelInfo the version of lychee or null if no git data could be found
```

File: app/Models/Extensions/ConfigsHas.php [hunk 64]
```diff
@@ -10,16 +10,12 @@ trait ConfigsHas
...
 	{
 		if ((bool) (extension_loaded('imagick') && self::get_value('imagick', '1') == '1')) {
 			return true;
 		}
-		try {
-			Logs::notice(__METHOD__, __LINE__, 'hasImagick : false');
-		} catch (Exception $e) {
-			//do nothing
-		}
+		Logs::notice(__METHOD__, __LINE__, 'hasImagick : false');
```
Comment (kamil4) [inline app/Models/Extensions/ConfigsHas.php]: I know this has been here before but can we just get rid of it? I find it needlessly chatty. What use does it serve that's not better served by the diagnostics output?

File: app/Models/Extensions/UTCBasedTimes.php [hunk 65]
```diff
@@ -26,9 +27,9 @@
  * This means the database configuration for MySQL should explicitly include
  * the option `'timezone' => '+00:00'` and the configuration for PostgreSQL
  * should explicitly include the option `'timezone => 'UTC'`.
- * Otherwise those RDBM system interpret a SQL datetime string without an
+ * Otherwise, those RDBM system interpret an SQL datetime string without an
```
Comment (kamil4) [inline app/Models/Extensions/UTCBasedTimes.php]:
```suggestion
 * Otherwise, those RDBM systems interpret an SQL datetime string without an
```

File: app/Models/Photo.php [hunk 66]
```diff
@@ -394,13 +417,16 @@ protected function hasDuplicate(): bool
 		return self::query()
 			->where(function ($q) use ($checksum) {
 				$q->where('checksum', '=', $checksum)
-					->orWhere('original_checksum', '=', $checksum)
```
Comment (kamil4) [inline app/Models/Photo.php:402]: What's the consequence of this change? Will it enable different orientations of the same picture in Lychee?

File: app/Rules/AlbumIDListRule.php [hunk 67]
```diff
@@ -9,37 +9,33 @@
...
-	 * Get the validation error message.
-	 *
-	 * @return string
+	 * {@inheritDoc}
 	 */
 	public function message(): string
 	{
-		return ':attribute ' .
-			' must be a comma-seperated string of strings with ' . HasRandomID::ID_LENGTH . ' characters each or the built-in IDs ' .
+		return ':attribute must be a comma-seperated string of strings with either ' .
```
Comment (kamil4) [inline app/Rules/AlbumIDListRule.php]:
```suggestion
		return ':attribute must be a comma-separated string of strings with either ' .
```

File: app/Rules/AlbumIDListRule.php [hunk 68]
```diff
@@ -9,37 +9,33 @@
...
+			HasRandomID::ID_LENGTH . ' characters each one of the built-in IDs ' .
```
Comment (kamil4) [inline app/Rules/AlbumIDListRule.php]:
```suggestion
			HasRandomID::ID_LENGTH . ' characters each or one of the built-in IDs ' .
```

File: app/Rules/SizeVariantRule.php [hunk 69]
```diff
@@ -0,0 +1,44 @@
...
+
+use App\Actions\Photo\Archive;
+use Illuminate\Contracts\Validation\Rule;
+
+/**
+ * SizeVariantRule.
+ *
+ * Rule to check whether the given attribute represents a valid size variant
+ * usable for archiving.
+ * Note that there are to different ways how to express the type of size
```
Comment (kamil4) [inline app/Rules/SizeVariantRule.php]:
```suggestion
 * Note that there are two different ways how to express the type of size
```

File: public/.htaccess [hunk 70]
```diff
@@ -21,6 +21,7 @@
 </IfModule>
 
 Options -Indexes
+SetEnv no-gzip
```
Comment (kamil4) [inline public/.htaccess]: What's this about? Why is it needed now?

File: resources/views/update/results.blade.php [hunk 71]
```diff
@@ -0,0 +1,79 @@
...
+<html lang="en">
+    <head>
+        <meta charset="utf-8">
+        <meta name="viewport" content="width=device-width, initial-scale=1">
+
+        <title>Database Migration</title>
+
+        <!-- Fonts -->
+        <link rel="dns-prefetch" href="//fonts.gstatic.com">
+        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
```
Comment (kamil4) [inline resources/views/update/results.blade.php:11]: I'm personally not a fan of Lychee having external run-time dependencies, especially on anything Google -- I believe it goes against the very spirit of self-hosting one's content -- but I realize that you simply duplicated existing code.

I'm not advocating that we fix it here and now; I'm simply bringing it up before I forget, to gauge the opinions of the rest of you, and if we all agree, we can address it in a separate future PR.

File: routes/web-admin.php [hunk 72]
```diff
@@ -0,0 +1,39 @@
...
+
+Route::get('/phpinfo', [IndexController::class, 'phpinfo']);
+
+Route::get('/Logs', [LogController::class, 'view']);
+
+// Traditionally, the diagnostic page has been accessible by anybody
+// While this might be helpful for debugging purposes if the setup is so
+// broken that even logging in as an administrator fails, it poses a security
+// risk.
+// TODO: Reconsider, if we really want the diagnostic page to be world-wide accessible.
```
Comment (kamil4) [inline routes/web-admin.php:35]: Well, it's mostly _not_ accessible already (the relevant System and Config info is missing in public mode) so we might as well bite the bullet and hide the rest of it?

File: tests/Feature/PhotosRotateTest.php [hunk 73]
```diff
@@ -60,13 +60,13 @@ public function testRotate()
 
 		$editor_enabled_value = Configs::get_value('editor_enabled');
 		Configs::set('editor_enabled', '0');
-		$response = $this->post('/api/PhotoEditor::rotate', [
+		$response = $this->postJson('/api/PhotoEditor::rotate', [
 			// somewhere in the Laravel middleware is a test which checks
 			// if `photoID` is a string; find where
 			'photoID' => (string) $id,
```
Comment (kamil4) [inline tests/Feature/PhotosRotateTest.php]: This looks like an obsolete comment and cast, given that `id` is expected to be a string these days?

**Review by kamil4 — APPROVED** [review]

File: app/Models/Extensions/ConfigsHas.php (hunk 64 above)
Comment (nagmat84) [reply app/Models/Extensions/ConfigsHas.php]: Totally agreed. @ildyria: Any strong opinions?

File: resources/views/update/results.blade.php (hunk 71 above)
Comment (nagmat84) [reply resources/views/update/results.blade.php:11]: I agree. As far as I know this is only used in the web installer/updater and probably only slipped in, because @ildyria copied & pasted most of the code for the installer/updater from some Laravel cook book. I always have been wondering why the style and layout of the installer/updater looks so different than the rest of Lychee.

When I take care of the installer, I will try to remember to fix at least that. The installer will still have a completely different look & feel than Lychee, because I don't feel appealed to do that, but at least the font can be replaced by "sans-serif" like the rest of Lychee.

File: app/Models/Photo.php (hunk 66 above)
Comment (nagmat84) [reply app/Models/Photo.php:402]: Au contraire. It ensures that Lychee shows the the same behavior as it always has been.

We had this discussion, if the checksum of a photo should be calculated directly after upload and before any potential auto-rotation or after auto-rotation. Previously, Lychee proceeded according to the first option, i.e. it calculated the checksum from the original photo before any modification and then never touch that checksum. Mostly due to my misunderstanding how the checksum was supposed to work I accidentally changed that, i.e. the checksum is now calculated after a potential auto-rotation and also updated with each rotation.

In order to restore the old behavior, we decided to introduce the new column `original_checksum` which plays the role of `checksum` before. So in order to determine if an uploaded photo is a duplicate we need to compare with `original_checksum`. (Please not the OR-operand.) A photo is considered a duplicate if the current checksum _or_ the original checksum matches.

File: public/.htaccess (hunk 70 above)
Comment (nagmat84) [reply public/.htaccess]: It is required to reliably enable streaming responses. Without this option Apache buffers the whole answer generated by PHP in order to compress it and then transfer it with the header `Encoding: gzip` or `Encoding: deflate`. This buffering prevents streaming responses from working and we need them for the progress and status report during import from server.

However, Apache uses compression only under very specific circumstances:

1. The module `mod_gzip` or `mod_deflate` must be installed and enabled
2. You don't use `mod_php`, but `mod_proxy_fcgi` together with PHP FPM.
3. The browser (and any potential content delivery proxy in between) advertises that it supports compressed connections

If all three conditions apply _simultaneously_, then and only then gzip or deflate kicks in. In that case you need to set `no_gzip` in order to still ensure that streaming responses work as expected. It took me nearly two days to find that out while I was working on that part of the backend. I was unable to get a streamed response, but the whole response came at once in the end.

The answer was deeply buried in the official Apache docs and I don't find the link anymore. Currently, I only find this obscure website: https://www.jeffgeerling.com/blog/2016/streaming-php-disabling-output-buffering-php-apache-nginx-and-varnish. Search for the phrase "If you use mod_proxy_fcgi with PHP-FPM"

I believe nobody noticed this problem before, because point 2 is a rather rare setup. I guess most user simply use `mod_php`, although it is rather slow, legacy and prevents Apache from multi-threading. Even vanilla Apache does not use `mod_php` anymore and recommend against it, but most of the big distros (Debian, Ubuntu, ...) still use it as default. I guess I am the only crazy person who uses `mod_proxy_fcgi` + PHP FPM. It makes PHP so much faster :sunglasses:

Moreover, neither `mod_gzip` nor `mod_deflate` are default Apache modules in Debian or Ubuntu. My productive system at my web hoster is Ubuntu-based, so I never had run into the problem before. However, my development machine at home uses Gentoo and Gentoo installs `mod_gzip` by default. Et voila, ..., the problem occurred.

I guess, it always should have been set, but nobody has noticed so far.

Of course, we could set the option `no_gzip` more locally via a fancy Apache rewrite rule only for the URLs that need it instead of disabling compression for Lychee on a global level. But I decided that is is not worth the effort. The real content of Lychee are images and these files are already highly compressed, so another layer of compression would rather be harmful. The remaining responses are short JSON snippets with a few bytes, so the total number of saved bytes is small, too.

File: routes/web-admin.php (hunk 72 above)
Comment (nagmat84) [reply routes/web-admin.php:35]: I don't mind either way. I mostly added the TODO as a reminder for discussion. @ildyria: What is your opinion?

File: tests/Feature/PhotosRotateTest.php (hunk 73 above)
Comment (nagmat84) [reply tests/Feature/PhotosRotateTest.php]: How did you even find that code?! The file was one of the few which were not part of the diff. :astonished: I agree, this seems to be an obsolete comment. I will post a commit which removes it.

Comment (nagmat84) [reply tests/Feature/PhotosRotateTest.php]: Fixed in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/426845268b8ded243e92d443dcb0e0a23257a2d3

Comment (kamil4) [reply tests/Feature/PhotosRotateTest.php]: It must've been in the diff (well, as context lines); otherwise there's no way I would've seen it...

File: public/.htaccess (hunk 70 above)
Comment (kamil4) [reply public/.htaccess]: Understood. I have compression enabled in Apache but I use `mod_php`... I can imagine that responses to calls like `Album::get` can get rather large for big albums so they could benefit from compression, but if it's nontrivial to disable compression just for the streaming output, it's probably not worth it...

File: app/Models/Photo.php (hunk 66 above)
Comment (kamil4) [reply app/Models/Photo.php:402]: Right. What I still don't understand is why we're deleting the comparison against `original_checksum` above?

Comment (nagmat84) [reply app/Models/Photo.php:402]: Damn. You are right, I deleted it. I thought I had added it (well probably in the last PR). Let me think about it for one night or two. I assume there was a reason for it and something was buggy, but I don't remember. I should have written a comment.

File: public/.htaccess (hunk 70 above)
Comment (nagmat84) [reply public/.htaccess]: > I can imagine that responses to calls like Album::get can get rather large for big albums so they could benefit from compression,

Yes. This also has been the only response, I could think of, whose size is not constant but grows linearly (and the log listing, of course). But even if an album contains 1,000 photos, a photo entry has around 200 characters (I didn't count them, just a gut feeling). So we end up with 200kB. 


> but if it's nontrivial to disable compression just for the streaming output, it's probably not worth it...

I actually did not spend much time to even try it. I was just happy after I had finally managed to get streamed responses to work. It was really frustrating. Honestly, I find the syntax for Apache's rewrite rules extremely unintuitive. It feels like the 70s with all the single letter commands. While O really like Apache a lot better than Nginx, the rewrite system is just, meeeeeh

Either we try to fix it now or in a separate PR.

File: app/Http/Controllers/AlbumController.php (hunk 34 above)
Comment (kamil4) [reply app/Http/Controllers/AlbumController.php]: I pushed a change to the front end PR to implement the selective Star/Unstar. Sure, using `album.getByID` for each element of an array is not very efficient, but I think it's acceptable, especially in a GUI context (where a human is likely to be the slowest link).

File: app/Actions/Albums/Tree.php [hunk 74]
```diff
@@ -14,16 +16,20 @@
...
 		$this->albumAuthorisationProvider = $albumAuthorisationProvider;
-		$this->sortingCol = Configs::get_value('sorting_Albums_col', 'created_at');
-		$this->sortingOrder = Configs::get_value('sorting_Albums_order', 'ASC');
+		$this->sorting = AlbumSortingCriterion::createDefault();
 	}
 
+	/**
+	 * @throws InternalLycheeException
+	 */
 	public function get(): array
```
Comment (kamil4) [inline app/Actions/Albums/Tree.php]: Not directly related to this PR but inspired by it, I think that this API call should also return smart and tag albums. While they can't be the target of a Move operation or such, they should be included in the front-end GUI in the pull-down list of all the albums that's available after clicking on the album name in the header.

I'm happy to do the necessary coding but I'm wondering if the return type of this call should be kept an array or whether it should be changed to the `TopAlbums` DTO to match `Albums::get`?

Comment (nagmat84) [reply app/Actions/Albums/Tree.php]: > I think that this API call should also return smart and tag albums. While they can't be the target of a Move operation or such, they should be included in the front-end GUI in the pull-down list of all the albums that's available after clicking on the album name in the header.

The latter is a good point. However, how and where you remove the smart albums from the tree for a move operation? On the frontend?

> I'm happy to do the necessary coding but I'm wondering if the return type of this call should be kept an array or whether it should be changed to the `TopAlbums` DTO to match Albums::get?

The return code should probably be a proper DTO to improve type-safty. But unless I am not completely mistaken, it cannot be `TopAlbums`, can it? TopAlbums` only includes the first level of the hierarchy while the returned array of this method returns the complete tree with all subalbums unfolded.

File: routes/web-admin.php (hunk 72 above)
Comment (ildyria) [reply routes/web-admin.php:35]: There are pros and cons.

For example if you prevent the access to Diagnostics while not logged, then if you cannot login for some reason, you cannot have access to the diagnostics which would potentially tell you that you are missing a specific dependency.

File: resources/views/update/results.blade.php (hunk 71 above)
Comment (ildyria) [reply resources/views/update/results.blade.php:11]: agreed.

File: app/Models/Photo.php (hunk 66 above)
Comment (nagmat84) [reply app/Models/Photo.php:402]: I did some archeological research on the git log history :-) It seems that the line has not been removed on purpose, but was never added to this branch. The missing line was added to the master branch after this branch had been forked from master. I guess the current result is the outcome of a failed merged when the changes to the master were merged back onto this branch.

Although the change seems to be accidental, I would keep it this way, if you don't mind.

 1. This method is not called when new photos are added to the gallery. The upload action has its own method for that, see https://github.com/LycheeOrg/Lychee/blob/3dd42332d0d372fe983c68f0ae4a03b72d9ffb0f/app/Actions/Photo/Extensions/Checks.php#L59-L69 which also correctly handled images that were auto-rotated.
    The method at hand is `protected` and only used by `Photo::delete`, see https://github.com/LycheeOrg/Lychee/blob/3dd42332d0d372fe983c68f0ae4a03b72d9ffb0f/app/Models/Photo.php#L462-L479 For this specific use case it does not make a difference, if the query has the additional OR-clause or not.
 2. Although we only rotate all instances of a photo together at the moment, you are right, in theory this change would enable to have different orientations of the same photo in Lychee. In theory, one could rotate a single instance of a photo individually, create a new media file during the process and later if one rotates another instance of the same photo in the same direction the media files would be re-merged again.
 3. I believe not checking for `original_checksum` follows the principle of least surprise from a developer's perspective. If one calls the method `hasDuplicates` one expect to check for duplicates of the photo in this very moment, not for photos which would have been duplicates in the past.

Off-the-topic: Of course one could wonder why there are two different implementations of a seemingly similar method: one in `\App\Models\Photo` and one in [`\App\Actions\Photo\Extensions\Checks`](https://github.com/LycheeOrg/Lychee/blob/3dd42332d0d372fe983c68f0ae4a03b72d9ffb0f/app/Actions/Photo/Extensions/Checks.php). I do really not like the traits we have in Lychee and I already removed many of them, but this trait is evil. It simply combines some unrelated checks.

File: public/.htaccess (hunk 70 above)
Comment (nagmat84) [reply public/.htaccess]: A more fine-granular settings was actually really easy. Fixed it in https://github.com/LycheeOrg/Lychee/pull/1217/commits/1cc7bc74062f8c58422654944e02cb442916a913

File: app/Exceptions/Handler.php [hunk 75]
```diff
@@ -2,83 +2,213 @@
...
+		$class = null;
+		$function = null;
+		foreach ($backtrace as $bt) {
+			$class = $bt['class'] ?? null;
+			$function = $bt['function'] ?? null;
+			if (str_contains($file, $this->appPath)) {
+				break;
 			}
+			$file = $bt['file'];
+			$line = $bt['line'];
```
Comment (kamil4) [inline app/Exceptions/Handler.php]: I again encountered a case when these two lines are failing. When testing #1274, I decided to change the permissions on `public/uploads/tracks` directory to make the writing of the track file fail so that I could verify that my simplified front-end error handling code worked as expected.

Instead of an expected message, I got `array key "file" not found`. I worked it around by adding `array_key_exists` tests here. I don't know what the correct fix is, but... we need it!

Comment (nagmat84) [reply app/Exceptions/Handler.php]: Totally agreed. I will try to trigger the error and then have a look at why the attributes `file` and `line` are missing. They definitely shouldn't, because the PHP docs require every `\Throwable` to have them. 

So all I have to do is to set wrong permissions on one of the upload folders and upload a file, right?

File: app/Http/Middleware/ContentType.php [hunk 76]
```diff
@@ -0,0 +1,51 @@
...
+				throw new UnexpectedContentType(self::MULTIPART);
+			}
+		} else {
+			throw new LycheeInvalidArgumentException('$contentType must either be "' . self::JSON . '" or "' . self::MULTIPART . '"');
+		}
+
+		return $next($request);
```
Comment (kamil4) [inline app/Http/Middleware/ContentType.php:49]: It seems that at least some error conditions (server crashes?) result in a `Syntax error` exception in this line rather than a helpful response pinpointing the actual problem. We need to fix it somehow because it makes debugging a real pain...

It's easily reproducible as I type this by setting `has_exiftool` to `0` and uploading any random picture.

File: app/Exceptions/Handler.php (hunk 75 above)
Comment (kamil4) [reply app/Exceptions/Handler.php]: Well, if I change the permissions on `big` it doesn't fail here, but it does for `tracks`...

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > It seems that at least some error conditions (server crashes?) result in a `Syntax error` exception in this line rather than a helpful response pinpointing the actual problem.

Yes, indeed these are server crashes.

A complete backtrace of a typical Laraval crash has hundreds of lines with dozens of unreadable anonymous closures in between which I personally find very difficult to read. Usually, I want to see the method of our own code which was involved in the problem.


So I thought it would be a clever idea not to print the whole backtrace into the log, but only print the _most inner method_ of _our_ code per exception.

See here:

https://github.com/LycheeOrg/Lychee/blob/cedfe3be5c9cc9abe4bd5fe09e1508e53ee7badb/app/Exceptions/Handler.php#L201

However, the problem which you observe happens when Lychee crashes after the middleware has been executed, but before the actual controller method has been reached. In this case the most inner of our own methods is one of our middleware methods.

Normally, the controller method should always be reached at least and if not this most likely indicates a severe error like a missing route, a unloadable class file, i.e. something really bad. I did not expect this to happen often.

But now I see that my initial idea might not have been so clever at all. 

> We need to fix it somehow because it makes debugging a real pain...

Right, but I wonder what would be the best approach?

The easiest solution would be not to try to be clever and not shorten the backtrace, but simply print the whole backtrace to the log. However, I fear that this will needlessly clutter the log for ordinary exceptions of "ordinary" use cases, i.e. after the controller method has been reached.

Another solution would be to let it depend on the environment. For "development" environments the whole backtrace is logged, for "production" environments a shortened backtrace is logged.

Or we could try to be even more clever and try to determine if the exception occurred before or after a controller method has been reached and then log different variants of backtraces. But I don't like the sound of that idea.

**Comment by ildyria** [comment]
I tested going to `/install` after the installation has been run. The previous behavior was redirecting to `/`, now it is throwing an exception:
2022-04-15_1920x1080_11:49:02
This needs to redirect back.

File: app/Exceptions/Handler.php (hunk 75 above)
Comment (nagmat84) [reply app/Exceptions/Handler.php]: > Well, if I change the permissions on `big` it doesn't fail here, but it does for `tracks`...

That's because we check the permissions for the (traditional) upload folders explicitly and throw our own custom exception, while in the latter case `fopen` throws a legacy PHP error.

Luckily, I own a proper IDE which allows step-debugging and annotates all variables with their value at runtime. This makes debugging so much easier.

Screenshot_20220416_123558

I fixed the problem in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/077bc67e3c0a6c064fbd41034095aa647157ff09

Most of the time went into writing that long comment. Sometimes PHP can be really annoying.

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > It's easily reproducible as I type this by setting has_exiftool to 0 and uploading any random picture.

Strangely, it does not happen for me:

Screenshot_20220416_143424

Screenshot_20220416_143515

Screenshot_20220416_143533

**Comment by nagmat84** [comment]
> I tested going to `/install` after the installation has been run. The previous behavior was redirecting to `/`, now it is throwing an exception: This needs to redirect back.

Why do want a re-direction back? The change was mostly intentional. IMHO, if systems try to be too clever or try to cover up errors (without indicating that there has been an error), tend to become annoying. Please note, that the detailed exception page, which you see, is only displayed if (a) `APP_DEBUG=true` is set in the `.env` file and (b) the `Whoops` exception renderer (part of the development dependencies) is available.

Otherwise, i.e. for non-developers, the exception page looks like that:

Screenshot_20220416_144006

You can easily test it when you set `APP_DEBUG=false` in the `.env` file. The templates for the non-debug exceptions reside in [/resources/views/error/error.blade.php](https://github.com/LycheeOrg/Lychee/blob/077bc67e3c0a6c064fbd41034095aa647157ff09/resources/views/error/error.blade.php). I know, the template does not follow the Lychee Look & Feel, but I haven't wrote this template and have been to lazy to change it.

This approach is in line how all responses work (let it be JSON or HTML):

- If Lychee runs in debug mode and an exception occurs, then a full back trace is reported:
  - for JSON as part of the returned object in `response.trace`,
  - for HTML the Whoops renderer is used (if installed)
- If Lychee runs in non-debug, productive mode, then only the name of the top-level exception and a explanatory message is reported:
  - for JSON as part of the returned object in `response.exception` and `response.message`,
  - for HTML an analogous web page is rendered.

Of course, an unconditional redirection to the homepage in case of exceptions for HTML responses could be implemented. But I thought that this might be confusing. If someone tries to access `/install` and always ends up in `/` without any message indicating why.

@ildyria: What do you think? @kamil4: What is your opinion?

**Comment by ildyria** [comment]
Okay. works for me. I was worried that the full details would show up. :)

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: Even though, I could not trigger the error in the same way as @kamil4, I triggered a similar error by deliberately introducing a crash inside the Laravel framework.

I fixed the problem here: https://github.com/LycheeOrg/Lychee/pull/1217/commits/b3daac3bb63707c3fca761f6a3c03bbc9b01bf22

I went a little bit over the edge and decided to log up to two frames per exception. @kamil4: What do you think about it?

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: Now, an early crash is supposed to look like this.

Screenshot_20220416_202636

You see the actual method which has thrown the exception (e.g. `ValidatePostSize`) and the most inner method of our own code (e.g. `FixStatusCode`). The latter won't be helpful for error cases like these, when the exception occurred before the controller method has been reached, but it doesn't harm either. The message `just a test` was the message of the exception I inserted deliberately into the code in order to provoke the problem.

File: resources/views/update/results.blade.php (hunk 71 above)
Comment (nagmat84) [reply resources/views/update/results.blade.php:11]: As we received the issue https://github.com/LycheeOrg/Lychee/issues/1261 for this in the meanwhile, I am going to close this discussion here as resolved.

File: routes/web-admin.php (hunk 72 above)
Comment (nagmat84) [reply routes/web-admin.php:35]: I won't change the behavior for the moment, but leave it as it always has been. I try to close as many conversations as I can in order to keep track of the major ones.

File: app/Actions/AlbumAuthorisationProvider.php (hunk 3 above)
Comment (nagmat84) [reply app/Actions/AlbumAuthorisationProvider.php]: Fixed in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/da561cb361a0a4919cfa53f487e1e26ce3ab6981

File: app/Models/Extensions/ConfigsHas.php (hunk 64 above)
Comment (nagmat84) [reply app/Models/Extensions/ConfigsHas.php]: Fixed in: https://github.com/LycheeOrg/Lychee/pull/1217/commits/da561cb361a0a4919cfa53f487e1e26ce3ab6981

File: app/Models/Photo.php (hunk 66 above)
Comment (nagmat84) [reply app/Models/Photo.php:402]: If we merge https://github.com/LycheeOrg/Lychee/pull/1277 into master first and then merge the head of master into this branch, this method will be gone anyway.

File: app/Actions/Albums/Tree.php (hunk 74 above)
Comment (nagmat84) [reply app/Actions/Albums/Tree.php]: I added a proper DTO for the sake of consistency. See this commit: https://github.com/LycheeOrg/Lychee/pull/1217/commits/2c556fece0197cd7319e5b8288301218548812a5. However, I did not include smart and tag albums into the tree. So it is still the the old behavior, but cleaned up.

While I was on it, I also create a DTO for `PositionData`. See this commit: https://github.com/LycheeOrg/Lychee/pull/1217/commits/d5c7d2ff12d6365ca574dc2555120cf913396b36.

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: Thanks for working on this. I'm still struggling to debug the issue I'm seeing though. Here's what I see in the logs now:
```
2022-04-21 19:50:15 UTC -- error   -- Illuminate\Http\JsonResponse::setData -- 88 -- Syntax error
2022-04-21 19:50:15 UTC -- error   -- App\Http\Middleware\ContentType::handle -- 49 -- Syntax error; caused by
```
I don't think I'm experiencing a crash. Rather, the serialization of newly added `Photo` model is failing. That happens for me if `has_exifool = 0`, even for images without EXIF data. The same photo model object persists successfully into the DB, and I verified that there's no weirdness there. So why is it failing here while being turned into json?

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: WTF? `JsonResponse::setData` is failing?! That's extremely weird. I assume it might be a `null` pointer issue, but that is just a guess. And why it is failing for you, while I cannot reproduce the problem.

Could you look into the debug panel of your browser and post the response? The Lychee logs only contain the two most relevant entries, because I didn't want to clutter the logs with a full backtrace. But the JSON response should contain the full backtrace.

Wait, you don't get a JSON response, because `JsonResponse::setData` fails, right? 😂

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: The only positive effect of the new logging is that I can now tell you exactly that it fails in line 88, i.e. here https://github.com/laravel/framework/blob/f0d10fd788a917e005c6dcbf9ade1b21bc685c73/src/Illuminate/Http/JsonResponse.php#L88

Do you have a proper step debugger which hooks into the PHP process when an exception is thrown? I am really curious what `$data` is.

Moreover, the error message is strange. `json_last_error` should return the last error message of JSON extension, but "syntax error" doesn't make any sense, if the last action was _encoding_. A syntax error makes only sense for _decoding_.

Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: I do not have a PHP step debugger -- I'm forced to add `Logs::notice` all over the place (because the debugbar doesn't work for uploads). `$data` is just fine, BTW.

So I figured it out, to a degree. Not the root cause, but why it fails here. It fails because `setData` is coded to assume that no exceptions are being thrown, so after invoking `toJson` on the model it calls `json_last_error()` to check if it succeeded. But our custom `toJson` forces the use of exceptions: https://github.com/LycheeOrg/Lychee/blob/324188c65316d49e4b2fcd79366922251c1a08cd/app/Models/Extensions/ThrowsConsistentExceptions.php#L134
So `json_last_error()` returns a stale error code from who-knows-where-and-when... As you pointed out, probably from some `json_decode`, given the `Syntax error`. I'm guessing that it works with ExifTool because its php-exif adapter invokes `json_decode` so the error gets cleared.

I was looking for a way to clear `json_last_error()` but I couldn't find one. I suppose we could do something crazy like invoking `json_encode` on an empty string. Still, fragile and nasty. I guess the correct fix is to provide a custom `setData` that works with exceptions? I'll let you figure it out...

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: I cannot follow your explanation.

> It fails because `setData` is coded to assume that no exceptions are being thrown, so after invoking `toJson` on the model it calls `json_last_error()` to check if it succeeded. But our custom `toJson` forces the use of exceptions.

This doesn't make sense to me. If `json_last_error` had already reported an error in our `toJson`, then our `toJson` method would have thrown an exception itself and the failing line in `setData` would never have been reached. The fact that line 88 in `toData` is executed, means that `toJson` has not thrown an exception which in turn means that `json_last_error` was just fine back there. Of course only, if it is our `toJson` which is called at all.

So, there are only three options:

 1. `$data` is one of our models, our `toJson` is called, does not throw an exception which means `json_last_error` is fine and then suddenly an error slips in between line 78 and 88 of `toData`.
 2. `$data` is an instance of `Jsomable`, but not one of our models, `toJson` of some other object is called and this one sets `json_last_error`
 3. `$data` is not an instance of `Jsonable` at all and `json_encode`  in line 80, 82 or 84 is called.

Option 1 is impossible. So option 2 and 3 remain.


> `$data` is just fine, BTW.

What exactly is `$data`? It cannot be one of our models.


> So `json_last_error()` returns a stale error code from who-knows-where-and-when... As you pointed out, probably from some `json_decode`, given the `Syntax error`.

And the question is from where? Any successful `json_...` method resets the error. Given the method `toData` this can only originate from one of the `json_...` methods in there or from a `toJson`, but not ours.

> I'm guessing that it works with ExifTool because its php-exif adapter invokes `json_decode` so the error gets cleared.

> I was looking for a way to clear `json_last_error()` but I couldn't find one. I suppose we could do something crazy like invoking `json_encode` on an empty string.

Not necessary. If any of the `json_...` methods in `toData` was successful, this would clear that error.


Anyway, I really need to reproduce this error myself. Could you post me your exact setup? Webserver, PHP version, Lychee configuration, etc. This is crazy.

Or maybe just before line https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/JsonResponse.php#L88, could you dump the backtrace to console via [`debug_print_backtrace`](https://www.php.net/manual/en/function.debug-print-backtrace.php) and then `die`?

**Comment by kamil4** [comment]
Are you planning to sync with `master` any time soon? Deleting the contents of the Unsorted album as an unprivileged user deletes visible photos of other users as well but I don't feel like investigating this right now given the recent refactoring on `master` (where this works fine).

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: Here's the output of `debug_print_backtrace` you wanted:
```
#0  Illuminate\Http\JsonResponse->setData() called at [Lychee-json/vendor/symfony/http-foundation/JsonResponse.php:54]
#1  Symfony\Component\HttpFoundation\JsonResponse->__construct() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:32]
#2  Illuminate\Http\JsonResponse->__construct() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:808]
#3  Illuminate\Routing\Router::toResponse() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:789]
#4  Illuminate\Routing\Router->prepareResponse() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:721]
#5  Illuminate\Routing\Router->Illuminate\Routing\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128]
#6  Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/ContentType.php:49]
#7  App\Http\Middleware\ContentType->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#8  Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50]
#9  Illuminate\Routing\Middleware\SubstituteBindings->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#10 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78]
#11 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() called at [Lychee-json/app/Http/Middleware/VerifyCsrfToken.php:61]
#12 App\Http\Middleware\VerifyCsrfToken->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#13 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:39]
#14 Illuminate\Session\Middleware\AuthenticateSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#15 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49]
#16 Illuminate\View\Middleware\ShareErrorsFromSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#17 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121]
#18 Illuminate\Session\Middleware\StartSession->handleStatefulRequest() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64]
#19 Illuminate\Session\Middleware\StartSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#20 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37]
#21 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#22 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67]
#23 Illuminate\Cookie\Middleware\EncryptCookies->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#24 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/AcceptContentType.php:61]
#25 App\Http\Middleware\AcceptContentType->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#26 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103]
#27 Illuminate\Pipeline\Pipeline->then() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:723]
#28 Illuminate\Routing\Router->runRouteWithinStack() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:698]
#29 Illuminate\Routing\Router->runRoute() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662]
#30 Illuminate\Routing\Router->dispatchToRoute() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:651]
#31 Illuminate\Routing\Router->dispatch() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167]
#32 Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128]
#33 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/livewire/livewire/src/DisableBrowserCache.php:19]
#34 Livewire\DisableBrowserCache->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#35 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:67]
#36 Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#37 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php:21]
#38 Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#39 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21]
#40 Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31]
#41 Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#42 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21]
#43 Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40]
#44 Illuminate\Foundation\Http\Middleware\TrimStrings->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#45 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27]
#46 Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#47 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86]
#48 Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#49 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/fideloper/proxy/src/TrustProxies.php:57]
#50 Fideloper\Proxy\TrustProxies->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#51 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/FixStatusCode.php:31]
#52 App\Http\Middleware\FixStatusCode->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#53 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php:24]
#54 Clockwork\Support\Laravel\ClockworkMiddleware->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#55 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103]
#56 Illuminate\Pipeline\Pipeline->then() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142]
#57 Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111]
#58 Illuminate\Foundation\Http\Kernel->handle() called at [Lychee-json/public/index.php:74]
```
Now, I owe you an apology for giving you an abbreviated version of my findings in my previous message, which sent you on that wild-goose chase.

So here's a long version of what I found by adding debug output all over this code:

1. `setData` (https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/JsonResponse.php#L73) gets invoked to handle the response of `Photo::add`.
2. `$data` is our newly added photo model object. So we are, in fact, in your option (1), which you ruled out early on as impossible -- but read on.
3. Our `toJson` gets called (https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/JsonResponse.php#L78).
4. Our `toJson` calls our `jsonSerialize:` https://github.com/LycheeOrg/Lychee/blob/324188c65316d49e4b2fcd79366922251c1a08cd/app/Models/Extensions/ThrowsConsistentExceptions.php#L134
5. Our `jsonSerialize` calls our `toArray:` https://github.com/LycheeOrg/Lychee/blob/324188c65316d49e4b2fcd79366922251c1a08cd/app/Models/Extensions/ThrowsConsistentExceptions.php#L114
6. Which one of these calls fails and throws an exception? The answer is: **none** of them. They all succeed and result in a perfectly formed JSON string.
7. However, back in `setData`, we get to the invocation of `json_last_error` (https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/JsonResponse.php#L87) which returns `4` (`JSON_ERROR_SYNTAX`)!
8. Yeah, that didn't make any sense to me either, until I added a debug output of `json_last_error` as the very *first* line of `setData` and there it was again: `4`. *It's a stale error that doesn't get cleared in spite of the subsequent json calls being successful*.
9. I thought it was a bug in PHP until I read word-for-word what [the manual](https://www.php.net/manual/en/function.json-last-error.php) says: *Returns the last error (if any) occurred during the last JSON encoding/decoding, which did not specify JSON_THROW_ON_ERROR.* The way I read it, it's _either_ exceptions _or_ `json_last_error`; we can't freely mix and match both and expect things to just keep working. Our `toJson` invokes `json_encode` with `JSON_THROW_ON_ERROR` which apparently not only prevents `json_last_error` from getting set on error but even (crucially for us) from getting cleared on success.
10. I don't know what code stores an error condition in `json_last_error` in the first place and why it does it for me and not for you. I'll see if I can find it but while that may help you reproduce the error in your setup, I don't think that's critical for coming up with a fix.

Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: So I verified that on call to `Photo:add`, here: https://github.com/LycheeOrg/Lychee/blob/324188c65316d49e4b2fcd79366922251c1a08cd/app/Http/Middleware/ContentType.php#L49 `json_last_error` is still `0`, but here: https://github.com/LycheeOrg/Lychee/blob/324188c65316d49e4b2fcd79366922251c1a08cd/app/Http/Requests/BaseApiRequest.php#L79 it's already `4`.
There are some 15 stack frames of Laravel in-between these two so pinpointing the culprit without a debugger is a major PITA. But if you have suggestions how to narrow it down, I'm willing to experiment...

**Comment by nagmat84** [comment]
> Are you planning to sync with `master` any time soon? Deleting the contents of the Unsorted album as an unprivileged user deletes visible photos of other users as well but I don't feel like investigating this right now given the recent refactoring on `master` (where this works fine).

This is my plan for this weekend, probably this evening. Another strange oddity as the logic hasn't changed, but only moved. Anyway, don't waste time on investigation.

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > Now, I owe you an apology for giving you an abbreviated version of my findings in my previous message, which sent you on that wild-goose chase.

No problem. I really appreciate that some takes the time to thoroughly test my code and look into it. My apologies that I cause so much trouble. You are really talented at finding weird bugs. :D I like that.

> 9. I thought it was a bug in PHP until I read word-for-word what [the manual](https://www.php.net/manual/en/function.json-last-error.php) says: *Returns the last error (if any) occurred during the last JSON encoding/decoding, which did not specify JSON_THROW_ON_ERROR.*

Yes, I only read this _after_ my long, previously reply, too. Now, everything makes perfect sense to me.

> The way I read it, it's _either_ exceptions _or_ `json_last_error`; we can't freely mix and match both and expect things to just keep working.

Here, I would like to object. You can mix it, but one must only call `json_last_error`, if one has called one of the json methods before without `JSON_THROW_ON_ERROR`. IMHO, the bug is actually in [`JsonResponse::setData`](https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/JsonResponse.php#L73). This method calls `json_last_error` although it cannot guarantee, that `toJson` has called `json_encode` at all. Just think of a trivial object which implements `Jsonable` but realizes the encoding in a completely different way, e.g. simply returns a valid JSON string. This way a previous, stalled Json Error would not be cleared either. You said, that `JsonResponse::setData` is written in a way which assumes that `toJson` does not throw an exception. I would like to rephrase that: `JsonResponse::setData` is written in a way which assumes that `toJson` uses `json_encode`. And that's a bug, IMHO.

> 10. I don't know what code stores an error condition in `json_last_error` in the first place and why it does it for me and not for you. I'll see if I can find it but while that may help you reproduce the error in your setup, I don't think that's critical for coming up with a fix.

Right. This sounds like another bug in Laravel. As our HTTP request at hand is not even a Json request, but uses Form Data, I guess that something in the middleware calls `json_decode` and does not accurately handle the error condition. Probably something which reads a configuration from a JSON-encoded file. This could also be an explanation why it fails for you but not for me.

Just to pin point the cause further. Could you once try to repreduce the problem with all development code being disabled? I know that the Laravel debug bar, Clockwork and so on, inject a lot JSON for communication between the backend and the frontend. I would like to rule out that the problem is there. Could you run a `composer install --no-dev`, and set `ENVIRONMENT` to `production` as well as `DEBUG_BAR| to `false` in your `.env` file?

Now, since I know for what I have to look out, I am certain I can use my debugger to trace for any call to `json_decode`. I am certain I will find the problematic code.

IMHO, there are three things to do:

1. Issue to bug report to Laravel for the problematic `setData` method. Justification see above.
2. Issue a bug report to Laravel for the actual root cause of this issue after we have found it.
3. Fix our `toJson` method so that it does not trigger the problematic code in `toData`. I already have an idea how to do it.

Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: > You are really talented at finding weird bugs. :D

I've heard that before :wink:.

> You said, that `JsonResponse::setData` is written in a way which assumes that `toJson` does not throw an exception. I would like to rephrase that: `JsonResponse::setData` is written in a way which assumes that `toJson` uses `json_encode`. And that's a bug, IMHO.

Agreed.

> Could you once try to repreduce the problem with all development code being disabled? I know that the Laravel debug bar, Clockwork and so on, inject a lot JSON for communication between the backend and the frontend. I would like to rule out that the problem is there. Could you run a `composer install --no-dev`, and set `ENVIRONMENT` to `production` as well as `DEBUG_BAR| to `false`in your`.env` file?

I tried. It still fails in the same way. The message in the front end is different (`Server error` rather than `Syntax error`, I think) but that's to be expected with debugging disabled.

> IMHO, there are three things to do:
> 
>     1. Issue to bug report to Laravel for the problematic `setData` method. Justification see above.

Given your past encounters with them, I'm not overly optimistic about the outcome, but it would be a shame not to try...

>     2. Issue a bug report to Laravel for the actual root cause of this issue after we have found it.

I wish I knew some easy way to intercept all calls to `json_decode`. I know how to do it in C for dynamically linked code but no idea about PHP...

>     3. Fix our `toJson` method so that it does not trigger the problematic code in `toData`. I already have an idea how to do it.

I think an easy way would be to add `json_encode([]);` as the first line of our `toJson` to clear any old errors...

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > >
> >  1. Issue to bug report to Laravel for the problematic `setData` method. Justification see above.
> >
> 
> Given your past encounters with them, I'm not overly optimistic about the outcome, but it would be a shame not to try...
> 

Exactly what I thought.

> >
> >  2. Issue a bug report to Laravel for the actual root cause of this issue after we have found it.
> > 
> 
> I wish I knew some easy way to intercept all calls to `json_decode`.
>

You don't know the power of [Xdebug](https://xdebug.org/) and a proper IDE. :stuck_out_tongue_closed_eyes: It took me 5min to trace all function calls to `json_encode` and properly will take 20min to write it down pleasantly.

As you mentioned that the bug also occurs in productive mode, here are the methods which call `json_encode` regularly:

 - [`\Illuminate\Encryption\Encrypter::getJsonPayload()`, line 215](https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Encryption/Encrypter.php#L213-L228)
   <details>
   <summary>Backtrace</summary>
  
       Encrypter.php:215, json_decode()
       Encrypter.php:215, Illuminate\Encryption\Encrypter->getJsonPayload()
       Encrypter.php:158, Illuminate\Encryption\Encrypter->decrypt()
       EncryptCookies.php:110, Illuminate\Cookie\Middleware\EncryptCookies->decryptCookie()
       EncryptCookies.php:84, Illuminate\Cookie\Middleware\EncryptCookies->decrypt()
       EncryptCookies.php:67, Illuminate\Cookie\Middleware\EncryptCookies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AcceptContentType.php:61, App\Http\Middleware\AcceptContentType->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Router.php:723, Illuminate\Routing\Router->runRouteWithinStack()
       Router.php:698, Illuminate\Routing\Router->runRoute()
       Router.php:662, Illuminate\Routing\Router->dispatchToRoute()
       Router.php:651, Illuminate\Routing\Router->dispatch()
       Kernel.php:167, Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:164-168}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       DisableBrowserCache.php:19, Livewire\DisableBrowserCache->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SecureHeadersMiddleware.php:21, Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       ConvertEmptyStringsToNull.php:31, Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       TrimStrings.php:40, Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ValidatePostSize.php:27, Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       PreventRequestsDuringMaintenance.php:86, Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TrustProxies.php:57, Fideloper\Proxy\TrustProxies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       FixStatusCode.php:31, App\Http\Middleware\FixStatusCode->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Kernel.php:142, Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
       Kernel.php:111, Illuminate\Foundation\Http\Kernel->handle()
       index.php:74, {main}()
   </details>

 - [`\Illuminate\Http\Request::json()`, line 384](https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/Request.php#L381-L392)
   <details>
   <summary>Backtrace</summary>

       Request.php:384, json_decode()
       Request.php:384, Illuminate\Http\Request->json()
       Request.php:435, Illuminate\Http\Request::createFrom()
       FormRequestServiceProvider.php:34, Illuminate\Foundation\Providers\FormRequestServiceProvider->Illuminate\Foundation\Providers\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php:33-37}()
       Container.php:1265, Illuminate\Container\Container->fireCallbackArray()
       Container.php:1212, Illuminate\Container\Container->fireResolvingCallbacks()
       Container.php:778, Illuminate\Container\Container->resolve()
       Application.php:851, Illuminate\Foundation\Application->resolve()
       Container.php:694, Illuminate\Container\Container->make()
       Application.php:836, Illuminate\Foundation\Application->make()
       RouteDependencyResolverTrait.php:79, Illuminate\Routing\ControllerDispatcher->transformDependency()
       RouteDependencyResolverTrait.php:48, Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies()
       RouteDependencyResolverTrait.php:28, Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies()
       ControllerDispatcher.php:41, Illuminate\Routing\ControllerDispatcher->dispatch()
       Route.php:262, Illuminate\Routing\Route->runController()
       Route.php:205, Illuminate\Routing\Route->run()
       Router.php:721, Illuminate\Routing\Router->Illuminate\Routing\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php:719-723}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       ContentType.php:49, App\Http\Middleware\ContentType->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SubstituteBindings.php:50, Illuminate\Routing\Middleware\SubstituteBindings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       VerifyCsrfToken.php:78, Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
       VerifyCsrfToken.php:61, App\Http\Middleware\VerifyCsrfToken->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AuthenticateSession.php:39, Illuminate\Session\Middleware\AuthenticateSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ShareErrorsFromSession.php:49, Illuminate\View\Middleware\ShareErrorsFromSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       StartSession.php:121, Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
       StartSession.php:64, Illuminate\Session\Middleware\StartSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AddQueuedCookiesToResponse.php:37, Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       EncryptCookies.php:67, Illuminate\Cookie\Middleware\EncryptCookies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AcceptContentType.php:61, App\Http\Middleware\AcceptContentType->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Router.php:723, Illuminate\Routing\Router->runRouteWithinStack()
       Router.php:698, Illuminate\Routing\Router->runRoute()
       Router.php:662, Illuminate\Routing\Router->dispatchToRoute()
       Router.php:651, Illuminate\Routing\Router->dispatch()
       Kernel.php:167, Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:164-168}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       DisableBrowserCache.php:19, Livewire\DisableBrowserCache->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SecureHeadersMiddleware.php:21, Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       ConvertEmptyStringsToNull.php:31, Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       TrimStrings.php:40, Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ValidatePostSize.php:27, Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       PreventRequestsDuringMaintenance.php:86, Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TrustProxies.php:57, Fideloper\Proxy\TrustProxies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       FixStatusCode.php:31, App\Http\Middleware\FixStatusCode->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Kernel.php:142, Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
       Kernel.php:111, Illuminate\Foundation\Http\Kernel->handle()
       index.php:74, {main}()
   </details>

 - [`\PHPExif\Adapter\Exiftool::getExifFromFile()`, line 151](https://github.com/LycheeOrg/php-exif/blob/a4e6f5c5bf30f1e240ec9a68b4433458c71c5d30/lib/PHPExif/Adapter/Exiftool.php#L128-L172)
   <details>
   <summary>Backtrace</summary>

       Exiftool.php:151, json_decode()
       Exiftool.php:151, PHPExif\Adapter\Exiftool->getExifFromFile()
       Reader.php:108, PHPExif\Reader\Reader->read()
       Extractor.php:162, App\Metadata\Extractor->extract()
       Create.php:136, App\Actions\Photo\Create->loadFileMetadata()
       Create.php:76, App\Actions\Photo\Create->add()
       PhotoController.php:103, App\Http\Controllers\PhotoController->add()
       Controller.php:54, Illuminate\Routing\Controller->callAction()
       ControllerDispatcher.php:45, Illuminate\Routing\ControllerDispatcher->dispatch()
       Route.php:262, Illuminate\Routing\Route->runController()
       Route.php:205, Illuminate\Routing\Route->run()
       Router.php:721, Illuminate\Routing\Router->Illuminate\Routing\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php:719-723}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       ContentType.php:49, App\Http\Middleware\ContentType->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SubstituteBindings.php:50, Illuminate\Routing\Middleware\SubstituteBindings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       VerifyCsrfToken.php:78, Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
       VerifyCsrfToken.php:61, App\Http\Middleware\VerifyCsrfToken->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AuthenticateSession.php:39, Illuminate\Session\Middleware\AuthenticateSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ShareErrorsFromSession.php:49, Illuminate\View\Middleware\ShareErrorsFromSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       StartSession.php:121, Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
       StartSession.php:64, Illuminate\Session\Middleware\StartSession->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AddQueuedCookiesToResponse.php:37, Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       EncryptCookies.php:67, Illuminate\Cookie\Middleware\EncryptCookies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       AcceptContentType.php:61, App\Http\Middleware\AcceptContentType->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Router.php:723, Illuminate\Routing\Router->runRouteWithinStack()
       Router.php:698, Illuminate\Routing\Router->runRoute()
       Router.php:662, Illuminate\Routing\Router->dispatchToRoute()
       Router.php:651, Illuminate\Routing\Router->dispatch()
       Kernel.php:167, Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:164-168}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       DisableBrowserCache.php:19, Livewire\DisableBrowserCache->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SecureHeadersMiddleware.php:21, Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       ConvertEmptyStringsToNull.php:31, Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       TrimStrings.php:40, Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ValidatePostSize.php:27, Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       PreventRequestsDuringMaintenance.php:86, Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TrustProxies.php:57, Fideloper\Proxy\TrustProxies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       FixStatusCode.php:31, App\Http\Middleware\FixStatusCode->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Kernel.php:142, Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
       Kernel.php:111, Illuminate\Foundation\Http\Kernel->handle()
       index.php:74, {main}()
   </details>

And here are the additional calls to `json_decode`, it debugging tools are enabled

 - [`Clockwork\DataSource\PhpDataSource::getRequestData()`, line 55](https://github.com/itsgoingd/clockwork/blob/9df41432da1d8cb39c7fda383ddcc02231c83ff3/Clockwork/DataSource/PhpDataSource.php#L49-L60)
   <details>
   <summary>Backtrace</summary>

       PhpDataSource.php:55, json_decode()
       PhpDataSource.php:55, Clockwork\DataSource\PhpDataSource->getRequestData()
       PhpDataSource.php:20, Clockwork\DataSource\PhpDataSource->resolve()
       Clockwork.php:59, Clockwork\Clockwork->resolveRequest()
       ClockworkSupport.php:382, Clockwork\Support\Laravel\ClockworkSupport->processRequest()
       ClockworkMiddleware.php:30, Clockwork\Support\Laravel\ClockworkMiddleware->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Kernel.php:142, Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
       Kernel.php:111, Illuminate\Foundation\Http\Kernel->handle()
       index.php:74, {main}()
   </details>

 - [`\Barryvdh\Debugbar\Storage\FilesystemStorage::get()`, line 84](https://github.com/barryvdh/laravel-debugbar/blob/b2d39072d094ccd060e27125352985d77aa60dc0/src/Storage/FilesystemStorage.php#L82-L85)
   <details>
   <summary>Backtrace</summary>

       FilesystemStorage.php:84, json_decode()
       FilesystemStorage.php:84, Barryvdh\Debugbar\Storage\FilesystemStorage->get()
       OpenHandler.php:106, DebugBar\OpenHandler->get()
       OpenHandler.php:61, call_user_func:{/var/www/localhost/lychee/vendor/maximebf/debugbar/src/DebugBar/OpenHandler.php:61}()
       OpenHandler.php:61, DebugBar\OpenHandler->handle()
       OpenHandlerController.php:15, Barryvdh\Debugbar\Controllers\OpenHandlerController->handle()
       Controller.php:54, Illuminate\Routing\Controller->callAction()
       ControllerDispatcher.php:45, Illuminate\Routing\ControllerDispatcher->dispatch()
       Route.php:262, Illuminate\Routing\Route->runController()
       Route.php:205, Illuminate\Routing\Route->run()
       Router.php:721, Illuminate\Routing\Router->Illuminate\Routing\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php:719-723}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       BaseController.php:29, Barryvdh\Debugbar\Controllers\BaseController->Barryvdh\Debugbar\Controllers\{closure:/var/www/localhost/lychee/vendor/barryvdh/laravel-debugbar/src/Controllers/BaseController.php:25-30}()
       Pipeline.php:149, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       DebugbarEnabled.php:41, Barryvdh\Debugbar\Middleware\DebugbarEnabled->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Router.php:723, Illuminate\Routing\Router->runRouteWithinStack()
       Router.php:698, Illuminate\Routing\Router->runRoute()
       Router.php:662, Illuminate\Routing\Router->dispatchToRoute()
       Router.php:651, Illuminate\Routing\Router->dispatch()
       Kernel.php:167, Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:164-168}()
       Pipeline.php:128, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:126-132}()
       DisableBrowserCache.php:19, Livewire\DisableBrowserCache->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       InjectDebugbar.php:67, Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       SecureHeadersMiddleware.php:21, Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       ConvertEmptyStringsToNull.php:31, Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TransformsRequest.php:21, Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
       TrimStrings.php:40, Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       ValidatePostSize.php:27, Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       PreventRequestsDuringMaintenance.php:86, Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       TrustProxies.php:57, Fideloper\Proxy\TrustProxies->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       FixStatusCode.php:31, App\Http\Middleware\FixStatusCode->handle()
       Pipeline.php:167, Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure:/var/www/localhost/lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:143-174}()
       Pipeline.php:103, Illuminate\Pipeline\Pipeline->then()
       Kernel.php:142, Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
       Kernel.php:111, Illuminate\Foundation\Http\Kernel->handle()
       index.php:74, {main}()
   </details>

So, there are only five options in total where it can happen! :tada:

> 
> >
> >  3. Fix our `toJson` method so that it does not trigger the problematic code in `toData`. I already have an idea how to do it.
> >
> 
> I think an easy way would be to add `json_encode([]);` as the first line of our `toJson` to clear any old errors...

Well, I had something else in mind. See here: https://github.com/LycheeOrg/Lychee/pull/1217/commits/33baac2c7a1cd08607fbbc02d77317a009eceb73

Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: This is the one:

[`\Illuminate\Http\Request::json()`, line 384](https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/Request.php#L381-L392)

```
            $this->json = new ParameterBag((array) json_decode($this->getContent(), true));
```
It's invoked just once while handling `Photo:add` and `$this->getContent()` is an empty string. Hence the parse error.

[`\PHPExif\Adapter\Exiftool::getExifFromFile()`, line 151](https://github.com/LycheeOrg/php-exif/blob/a4e6f5c5bf30f1e240ec9a68b4433458c71c5d30/lib/PHPExif/Adapter/Exiftool.php#L128-L172)

This one is not relevant when `has_exiftool = 0`. For me, when it runs, it actually masks the problem, by clearing `json_last_error`.

> > I think an easy way would be to add `json_encode([]);` as the first line of our `toJson` to clear any old errors...
> 
> Well, I had something else in mind. See here: [33baac2](https://github.com/LycheeOrg/Lychee/commit/33baac2c7a1cd08607fbbc02d77317a009eceb73)

Yes, that's better -- no extra calls just to clear the stored error code. I confirmed that it works.

Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > This is the one:
> 
> [`\Illuminate\Http\Request::json()`, line 384](https://github.com/laravel/framework/blob/6fea6c271086e2ad017a6078e1ee457a2b8c398e/src/Illuminate/Http/Request.php#L381-L392)
> 
> ```
>             $this->json = new ParameterBag((array) json_decode($this->getContent(), true));
> ```
> It's invoked just once while handling `Photo:add` and `$this->getContent()` is an empty string. Hence the parse error.
> 

Strangely, on my machine it is called several times and `getContent` returns `null` (not the empty string) and this is properly decoded as `null` again. Why these differences? I smell another Laravel bug here.

Although the original problem is now fixed, I would like to ask you one more time to determine if the method is called before or after our controller method is hit, i.e. does it happen on the way in or out, provide a backtrace and maybe a dump of the other variables in the scope.

I would like to file a Laravel bug on this, too, if we have enough information for that.

Comment (kamil4) [reply app/Http/Middleware/ContentType.php:49]: > Although the original problem is now fixed, I would like to ask you one more time to determine if the method is called before or after our controller method is hit, i.e. does it happen on the way in or out, provide a backtrace and maybe a dump of the other variables in the scope.

It happens on the way in. I believe the backtrace is essentially the same as yours, but here it is again:
```
#0  Illuminate\Http\Request->json() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Http/Request.php:448]
#1  Illuminate\Http\Request::createFrom() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php:37]
#2  Illuminate\Foundation\Providers\FormRequestServiceProvider->Illuminate\Foundation\Providers\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Container/Container.php:1270]
#3  Illuminate\Container\Container->fireCallbackArray() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Container/Container.php:1216]
#4  Illuminate\Container\Container->fireResolvingCallbacks() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Container/Container.php:782]
#5  Illuminate\Container\Container->resolve() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:857]
#6  Illuminate\Foundation\Application->resolve() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Container/Container.php:697]
#7  Illuminate\Container\Container->make() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:842]
#8  Illuminate\Foundation\Application->make() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:84]
#9  Illuminate\Routing\ControllerDispatcher->transformDependency() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:51]
#10 Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:31]
#11 Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:41]
#12 Illuminate\Routing\ControllerDispatcher->dispatch() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Route.php:262]
#13 Illuminate\Routing\Route->runController() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205]
#14 Illuminate\Routing\Route->run() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:721]
#15 Illuminate\Routing\Router->Illuminate\Routing\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128]
#16 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/ContentType.php:49]
#17 App\Http\Middleware\ContentType->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#18 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50]
#19 Illuminate\Routing\Middleware\SubstituteBindings->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#20 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78]
#21 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() called at [Lychee-json/app/Http/Middleware/VerifyCsrfToken.php:61]
#22 App\Http\Middleware\VerifyCsrfToken->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#23 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:39]
#24 Illuminate\Session\Middleware\AuthenticateSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#25 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49]
#26 Illuminate\View\Middleware\ShareErrorsFromSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#27 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121]
#28 Illuminate\Session\Middleware\StartSession->handleStatefulRequest() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64]
#29 Illuminate\Session\Middleware\StartSession->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#30 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37]
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#32 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67]
#33 Illuminate\Cookie\Middleware\EncryptCookies->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#34 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/AcceptContentType.php:61]
#35 App\Http\Middleware\AcceptContentType->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#36 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103]
#37 Illuminate\Pipeline\Pipeline->then() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:723]
#38 Illuminate\Routing\Router->runRouteWithinStack() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:698]
#39 Illuminate\Routing\Router->runRoute() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662]
#40 Illuminate\Routing\Router->dispatchToRoute() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Routing/Router.php:651]
#41 Illuminate\Routing\Router->dispatch() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167]
#42 Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128]
#43 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/livewire/livewire/src/DisableBrowserCache.php:19]
#44 Livewire\DisableBrowserCache->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#45 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:67]
#46 Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#47 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php:21]
#48 Bepsvpt\SecureHeaders\SecureHeadersMiddleware->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#49 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21]
#50 Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31]
#51 Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#52 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21]
#53 Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40]
#54 Illuminate\Foundation\Http\Middleware\TrimStrings->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#55 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27]
#56 Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#57 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86]
#58 Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#59 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/fideloper/proxy/src/TrustProxies.php:57]
#60 Fideloper\Proxy\TrustProxies->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#61 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/app/Http/Middleware/FixStatusCode.php:31]
#62 App\Http\Middleware\FixStatusCode->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#63 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php:24]
#64 Clockwork\Support\Laravel\ClockworkMiddleware->handle() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167]
#65 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103]
#66 Illuminate\Pipeline\Pipeline->then() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142]
#67 Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() called at [Lychee-json/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111]
#68 Illuminate\Foundation\Http\Kernel->handle() called at [Lychee-json/public/index.php:74]
```

I'm not sure how best to dump the relevant variables. If I dump the backtrace without passing `DEBUG_BACKTRACE_IGNORE_ARGS`, the output is unmanagable (>700 MB). `var_dump($this->toArray());` doesn't seem helpful. Any suggestions?

**Comment by nagmat84** [comment]
> Are you planning to sync with `master` any time soon? Deleting the contents of the Unsorted album as an unprivileged user deletes visible photos of other users as well but I don't feel like investigating this right now given the recent refactoring on `master` (where this works fine).

BTW, I would also like to see https://github.com/LycheeOrg/Lychee/pull/1275 being merged into master before this PR so that we can close https://github.com/LycheeOrg/Lychee/issues/1269.

File: app/Http/Middleware/ContentType.php (hunk 76 above)
Comment (nagmat84) [reply app/Http/Middleware/ContentType.php:49]: > I'm not sure how best to dump the relevant variables. If I dump the backtrace without passing `DEBUG_BACKTRACE_IGNORE_ARGS`, the output is unmanagable (>700 MB). `var_dump($this->toArray());` doesn't seem helpful. Any suggestions?

Never mind. I thought it would be nice to find out, why `$content` equals the empty string `''` for you and `null` for me. But this is not worth the time and I already figured out that the problem which sets `json_last_error` in the first place is actually worse than I thought. Here are the two Laravel bug reports:

 - https://github.com/laravel/framework/issues/42106
 - https://github.com/laravel/framework/issues/42107

Let's see what happens. Actually, the credits are yours for finding these bugs.

File: app/Metadata/GitHubFunctions.php [hunk 77]
```diff
@@ -51,48 +41,69 @@ private function trim($commit_id): string
...
+				throw new \RuntimeException('`file_get_contents` returned `false`');
+			}
+			$branch = explode('/', $branch, 3);
+			if ($branch === false) {
+				throw new \RuntimeException('`explode` returned `false`');
+			}
 
-		return trim($branch_[2]);
-		// @codeCoverageIgnoreEnd
+			return trim($branch[2]);
```
Comment (qwerty287) [inline app/Metadata/GitHubFunctions.php]: The branch is usually the last array key, so this should fix CI issues similar to https://github.com/LycheeOrg/Lychee/pull/1274.

```suggestion
			return trim(end($branch));
```

Comment (d7415) [reply app/Metadata/GitHubFunctions.php]: The problem here is that the result in #1274 wouldn't be a branch name. Which may be fine, but is likely to have consequences.

Comment (d7415) [reply app/Metadata/GitHubFunctions.php]: Actually, it looks like the errors here are new behaviour as a result of this PR. Previously the error would have been caught and they'd just be set to `false`.

Comment (qwerty287) [reply app/Metadata/GitHubFunctions.php]: Isn't this only used to pull the latest commits? Then this is possible as well - you can use `git pull` with commit references. (I don't know where this method is used elsewhere.)

File: app/Metadata/GitHubFunctions.php [hunk 78]
```diff
@@ -2,40 +2,30 @@
...
 		$this->gitRequest = $gitRequest;
-		try {
-			$this->branch = $this->get_current_branch();
-			$this->head = $this->get_current_commit();
-			// @codeCoverageIgnoreStart
-			// when testing on master branch this is not covered.
-		} catch (Exception $e) {
-			$this->branch = false;
-			$this->head = false;
-		}
```
Comment (d7415) [inline app/Metadata/GitHubFunctions.php:37]: Removing this causes exceptions in testing (https://github.com/LycheeOrg/Lychee/pull/1274#issuecomment-1107869076)

File: app/Metadata/GitHubFunctions.php (hunk 77 above)
Comment (nagmat84) [reply app/Metadata/GitHubFunctions.php]: @qwerty287 thanks for your suggestion, but I would rather like to keep that out of this PR. The PR is already ways to huge and this method was not introduced by this PR. So this is an unrelated fix.

If you feel like it, you are welcome to push another PR. But as @d7415 pointed out, your suggested change might have consequences elsewhere which I cannot assess right now. Personally, I consider this whole code ugly as hell. It is part of the unfortunate web installer/updater which is broken in so many ways that I plan to replace it entirely in the near future.

Comment (d7415) [reply app/Metadata/GitHubFunctions.php]: > The PR is already ways to huge and this method was not introduced by this PR.

Agreed.

> So this is an unrelated fix.

[I'm less sure about that](https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r857148691)

Comment (nagmat84) [reply app/Metadata/GitHubFunctions.php]: Damn it. You caught me. Let's see what I can do about it.

Comment (nagmat84) [reply app/Metadata/GitHubFunctions.php]: OK. I believe I have ultimately fixed all these problems. :crossed_fingers: The problem was not throwing exceptions or using an non-existing index. This was fine.

The problem was that the classes `GitHubFunctions` and `JsonRequestFunctions` already executed code in their constructors which was capable of throwing exceptions _and_ `GitHubFunctions` was registered as a service class in `AppServiceProvider`. Hence, Laravel already tried to construct these classes while building the routing pipeline even if these objects were never needed. The freshly constructed object `GitHubFunctions` tried to fetch GIT information and if it failed it threw an exception, but the `AppServiceProvider` was (and is) not prepared to handle those exceptions.

Now, the re-written classes only fetch the GIT information when the corresponding getter method is called for the first time. This may still fail with an exception, but this is OK, because we are prepared to handle these exceptions.

Comment (d7415) [reply app/Metadata/GitHubFunctions.php]: That makes sense to me!

**Review by nagmat84 — COMMENTED** [review]
Just a review on my own so that GIThub memorizes the files which I have viewed and checked.

**Comment by kamil4** [comment]
> Deleting the contents of the Unsorted album as an unprivileged user deletes visible photos of other users as well

This appears to be fixed now.

File: app/Rules/IntegerIDRule.php [hunk 79]
```diff
@@ -0,0 +1,46 @@
...
+		return
+			(
+				$value === null &&
+				$this->isNullable
+			) || (
+				$this->isRelaxed &&
+				filter_var($value, FILTER_VALIDATE_INT) !== false &&
+				intval($value) > 0
+			) || (
+				is_int($value) &&
```
Comment (kamil4) [inline app/Rules/IntegerIDRule.php:32]: Legacy ID translation fails because of this condition (`is_int`). I can make it work by changing it to `is_numeric` but then I'm not sure what would be the intended difference between this case and the one right above?

Comment (nagmat84) [reply app/Rules/IntegerIDRule.php:32]: Fixed this in https://github.com/LycheeOrg/Lychee-front/pull/282/commits/cd6df802744bee4342a06c5c997935f2c6a051bc and in https://github.com/LycheeOrg/Lychee/pull/1217/commits/6c99d6a3ee6e8f5f5b3693e177b5c77ab21a07fb.

The difference between `is_int` and `is_numeric` is that the latter also excepts numbers encoded as strings. But I really wanted `is_int` now after we have proper JSON everywhere. But I missed to update the rest.

File: app/Exceptions/Handler.php [hunk 80]
```diff
@@ -46,6 +59,46 @@ public function __construct(Container $container)
...
+	 * We overwrite this method such that {@link TokenMismatchException}
+	 * is not replaced by a generic HTTP exception but something more
+	 * specific, which we can detect more easily.
+	 * Note, that the default Laravel handler has actually **two** methods
+	 * which both replace exceptions by other exceptions:
+	 *
+	 *  - {@link ExceptionHandler::mapException()}
+	 *  - {@link ExceptionHandler::prepareException()}
+	 *
+	 * which are chained like one after the other like this
```
Comment (kamil4) [inline app/Exceptions/Handler.php]:
```suggestion
	 * which are chained one after the other like this
```
