### PR TITLE
Speed up `POST api/Album::getPositionData`

### LINKED ISSUE #1254: MySQL optimizer picks wrong DB indices and slows down query for albums
### Description of the problem

The DB dump by @geeklihui from [this comment](https://github.com/LycheeOrg/Lychee/issues/1251#issuecomment-1087413976) in issue #1251 unveiled a slow DB query for albums which takes 10 times longer than it should, because the MySQL query optimizer decides to pick the wrong index.

### Steps to reproduce the issue

1. Setup a MySQL DB and test bed with the DB dump from above, enable the Laravel Debug Bar
2. Open album "旅游" (ID = Rc57ztpnNJ1s4fywNKP5FW8O, the only public one)
3. Open the map view
4. The HTTP response takes 4.9s (see Laravel Debug Bar)

#### The defective query

The defective query is

```sql
SELECT
  `albums`.*,
  (
    SELECT `taken_at` FROM `photos`
    INNER JOIN `albums` AS `a` ON `a`.`id` = `album_id`
    WHERE
      `a`.`_lft` >= `albums`.`_lft` AND 
      `a`.`_rgt` <= `albums`.`_rgt` AND
      `taken_at` IS NOT NULL
    ORDER BY `taken_at` ASC
    LIMIT 1
  ) AS `min_taken_at`,
  (
    SELECT `taken_at` FROM `photos`
    INNER JOIN `albums` AS `a` ON `a`.`id` = `album_id`
    WHERE
      `a`.`_lft` >= `albums`.`_lft` AND
      `a`.`_rgt` <= `albums`.`_rgt` AND
      `taken_at` IS NOT NULL
    ORDER BY `taken_at` DESC
    LIMIT 1
  ) AS `max_taken_at`
FROM `albums`
WHERE `albums`.`id` in (
  '0mBr7HZpAYBCgSz0pfX0NBBd', '83sF2K5Zq2KGTuD0UjDbUrVm', '8OOupX9gdVrAPpPbQgT9xhQg',
  'CjbdbKHWE8nYlE-r-lAXAbfD', 'MaCjPtz4YfmyzdmoF7qxqhy5', 'UmGa9KwX1zTUkBak_WjnA_el',
  'W8-joUmxJ-_IfdZjoKLwSKl7', 'dQZe1FY1Ix3LOnOLJfqTu6Ao', 'doieSROAd9bt2bSlTbShgf3h',
  'fPUYimSJBdooiOchzNPRE1ZV', 'hQp3IHFrYfn-OCrKuVPnYoHZ'
);
``` 

Query statistics: 11 rows **approx. 140ms**

The `EXPLAIN` command shows

| id  | select_type        | table  | type   | key                   | key_len | rows |
|----:|:------------------ |:-------|:-------|:----------------------|--------:|-----:|
|   1 | PRIMARY            | albums | range  | PRIMARY               | 96      |   11 |
|   3 | DEPENDENT SUBQUERY | photos | range  | photos_taken_at_index | 9       | 3879 |
|   3 | DEPENDENT SUBQUERY | a      | eq_ref | PRIMARY               | 96      |    1 |
|   2 | DEPENDENT SUBQUERY | photos | range  | photos_taken_at_index | 9       | 3879 |
|   2 | DEPENDENT SUBQUERY | a      | eq_ref | PRIMARY               | 96      |    1 |

The problem is that this query
 1. selects _all_ photos of the DB (3879 rows),
 2. orders them by `taken_at`,
 3. joins these photos with the albums, and then
 4. selects only those albums which are sub-albums.

#### The improved query (with forced usage of indices)

This is the same query, but it additionally uses index hints with MySQL `USE INDEX`:

```sql
SELECT
  `albums`.*,
  (
    SELECT `taken_at` FROM `photos` USE INDEX (photos_album_id_taken_at_index)
    INNER JOIN `albums` AS `a` USE INDEX (albums__lft__rgt__index) ON `a`.`id` = `album_id`
    WHERE
      `a`.`_lft` >= `albums`.`_lft` AND
      `a`.`_rgt` <= `albums`.`_rgt` AND
      `taken_at` IS NOT NULL
    ORDER BY `taken_at` ASC
    LIMIT 1
  ) AS `min_taken_at`,
  (
    SELECT `taken_at` FROM `photos` USE INDEX (photos_album_id_taken_at_index)
    INNER JOIN `albums` AS `a` USE INDEX (albums__lft__rgt__index) ON `a`.`id` = `album_id`
    WHERE
      `a`.`_lft` >= `albums`.`_lft` AND
      `a`.`_rgt` <= `albums`.`_rgt` AND
      `taken_at` IS NOT NULL
    ORDER BY `taken_at` DESC
    LIMIT 1
  ) AS `max_taken_at`
FROM `albums`
WHERE `albums`.`id` in (
  '0mBr7HZpAYBCgSz0pfX0NBBd', '83sF2K5Zq2KGTuD0UjDbUrVm', '8OOupX9gdVrAPpPbQgT9xhQg',
  'CjbdbKHWE8nYlE-r-lAXAbfD', 'MaCjPtz4YfmyzdmoF7qxqhy5', 'UmGa9KwX1zTUkBak_WjnA_el',
  'W8-joUmxJ-_IfdZjoKLwSKl7', 'dQZe1FY1Ix3LOnOLJfqTu6Ao', 'doieSROAd9bt2bSlTbShgf3h',
  'fPUYimSJBdooiOchzNPRE1ZV', 'hQp3IHFrYfn-OCrKuVPnYoHZ'
);
```

Query statistics: 11 rows **approx. 6ms**

The `EXPLAIN` command shows

| id  | select_type        | table  | type  | key                            | key_len | rows |
|----:|:------------------ |:-------|:------|:-------------------------------|--------:|-----:|
|   1 | PRIMARY            | albums | range | PRIMARY                        | 96      |   11 |
|   3 | DEPENDENT SUBQUERY | a      | index | albums__lft__rgt__index        | 16      |  194 |
|   3 | DEPENDENT SUBQUERY | photos | ref   | photos_album_id_taken_at_index | 97      |   47 |
|   2 | DEPENDENT SUBQUERY | a      | index | albums__lft__rgt__index        | 16      |  194 |
|   2 | DEPENDENT SUBQUERY | photos | ref   | photos_album_id_taken_at_index | 97      |   47 |

This query
 1. selects the albums which are sub-albums (194 rows),
 2. joins theses albums with photos, and then
 3. orders those photos by `taken_at`

#### Further remarks

- The problem is not a missing index; all indices exist otherwise `USE INDEX` would not work either
- The index statistics is correct; previously we encountered similar errors when MySQL assumed a wrong cardinality for an index, but `SHOW INDICES` is accurate and `ANALYZE TABLE` did not change anything

### PR DESCRIPTION
**Pull request by nagmat84**
Some query optimization for MySQL as discussed in issue #1254.

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
LGTM.

File: app/Actions/Album/PositionData.php [hunk 1]
```diff
@@ -22,7 +25,25 @@ public function get(string $albumID, array $data): array
...
+					$b->without(['cover', 'thumb']);
+				},
+				'size_variants' => function (HasMany $r) {
+					// The web GUI only uses the small and thumb size
+					// variants to show photos on a map; so we can save
+					// hydrating the larger size variants
+					// this really helps, if you want to show thousands
+					// of photos on a map, as there are up to 7 size
+					// variants per photo
+					$r->whereBetween('type', [SizeVariant::SMALL2X, SizeVariant::THUMB]);
```
Comment (kamil4) [inline app/Actions/Album/PositionData.php:43]: Sorry for being late on this, but I'm surprised by the choice of sizes here. If `SMALL2X`, then why not also `SMALL`? If `THUMB`, then why `SMALL` sizes at all? And why not `THUMB2X`?

From a quick experiment, it seems that the map overview just uses `THUMB`/`THUMB2X`?

Comment (nagmat84) [reply app/Actions/Album/PositionData.php:43]: The array is not an enumeration, but a range. The first value is the lower bound, the second value the upper bound. So it is SMALL2X (3), SMALL (4), THUMB2X (5) and THUMB (6). 

And I thought that I saw an imageset which used the small variants.

Comment (nagmat84) [reply app/Actions/Album/PositionData.php:43]: Yep, here it is: https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/mapview.js#L186-L197

Comment (kamil4) [reply app/Actions/Album/PositionData.php:43]: Right, I failed to notice that it was a range...

So that overview map will only use the THUMBs I believe, but we still need to fetch all the SMALLs in case the user clicks on any of the thumbs...
