### PR TITLE
Fix import of video files and thumbnail generation

### LINKED ISSUE #1218: Video imports fail
### Detailed description of the problem [REQUIRED]
I'm using the import from server function to import my photo collection previously hosted on Synology PhotoStation. First import of the whole collection failed, but after splitting it up into yearly batches photo import works just fine. My problem is that a lot of these folders include video files. Most of these videos are of supported file formats, but they fail import.
I see a couple of previous references to the issue here: https://www.giters.com/LycheeOrg/Lychee-v3/issues/326 and here: https://github.com/LycheeOrg/Lychee-v3/issues/156 but they are both reported for Lychee v3
Looks like the import function is trying to treat the video files as images.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. import folders containing videos
2. See videos failing to import
3. Log file says: Photo type not supported: ..MP4

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Warning: '/opt/lychee/public/dist/user.css' does not exist or has insufficient read/write privileges.
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

    System Information
    --------------
    Lychee Version (git):            master (8c6b200) - Data not in Cache
    DB Version:                      4.5.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        UTC
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   8.0.28-0ubuntu0.20.04.3
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040500
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            nb-no
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Lene Noteng
    landing_title:                   Lene Noteng
    landing_subtitle:                Bilder
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2004
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1

### Browser and system

Server: Ubuntu 20.04 with packported PHP8.1
Storage: Synology NAS mounted via NFS
Browser: Google Chomre

### PR DESCRIPTION
**Pull request by kamil4**
Fixes #1218

There were two separate bugs:
- Extra dot being added to file extensions on import
- Leftover invocation of `Helpers::createTemporaryFile` which doesn't exist as of #1203 

I also noticed that we were attempting to generate medium/medium2x variants for video files. They are not necessary because the front end can't use them (it displays the video file using the `video` tag, rather than displaying a medium image like it does for photos). Or was this change intentional? I'm guessing it dates back to #1055.

### CODE REVIEW

**Review by nagmat84 — APPROVED** [review]
LGTM. Identical to my bug fix, except for the additional removal of the medium size variants for videos.

**Comment by nagmat84** [comment]
> also noticed that we were attempting to generate medium/medium2x variants for video files. They are not necessary because the front end can't use them [...]. Or was this change intentional? I'm guessing it dates back to #1055.

No, the change wasn't intentional. Actually it was a pure oversight. One could argue that for sake of clearness and traceability it might be worth not to add any extra code paths for this particular front-end. Probably, in some years other programmers will ask the question, what is so special about videos to not generate the size variants. Saying that, we should at least add a comment. But I am fine with removing the size variants.

File: app/Image/SizeVariantDefaultFactory.php [hunk 1]
```diff
@@ -239,6 +236,9 @@ public function createSizeVariantCond(int $sizeVariant): ?SizeVariant
 		if (!$this->isEnabledByConfiguration($sizeVariant)) {
 			return null;
 		}
+		if ($this->photo->isVideo() && ($sizeVariant === SizeVariant::MEDIUM || $sizeVariant === SizeVariant::MEDIUM2X)) {
```
Comment (nagmat84) [inline app/Image/SizeVariantDefaultFactory.php:240]:
```suggestion
		// Don't generate medium size variants for videos, because the current web front-end has no use for it. Let's save some storage space.
		if ($this->photo->isVideo() && ($sizeVariant === SizeVariant::MEDIUM || $sizeVariant === SizeVariant::MEDIUM2X)) {
```
