### PR TITLE
fixes #633

### LINKED ISSUE #633: [Regression] Missing album thumbnails when moving pictures.
### Detailed description of the problem [REQUIRED]

Use current master. Try to move an album -> the generated list is missing thumbnails.
This is due to the new recursion process only doing one stage and not a full recursion.

### LINKED ISSUE #643: [regression] Error 500 on albums::get() when album are shared between users (when logging on said user).
### Detailed description of the problem

If I make an album as the primary user everything works fine, but if I create a secondary user and give it access to the album, then when I try logging in as that account, I see a 'Server error or API not found' red banner and errors in the console:

```
/api/Albums::get:1 Failed to load resource: the server responded with a status of 500 ()
main.js?1593291479:4039

Objectdescription: "Server error or API not found."params: function: "Albums::get"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()response: ""__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
lychee.error @ main.js?1593291479:4039
```

However, I can't figure out what the error might be - I tried seeing what the nginx and php logs contained in ``/var/log`` but couldn't see any more information.

### Steps to reproduce the issue

**Steps to reproduce the behavior:**

1. Create an album as primary user
2. Create a new user
3. Give access to the album to the new user
4. Log in as new user

A black screen appears and there is an error in the console (given above)

I'm using the ``dev`` tag of the docker container for lychee.

### Output of the diagnostics 

```
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    Max uploaded file size:     20M
    Max post size:              100M
    SQLite Version:             3.27.2
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    ------------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              0
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              Thomas Robitaille
    landing_title:              Photos
    landing_subtitle:           
    landing_facebook:           https://www.facebook.com/astrofrog
    landing_flickr:             https://www.flickr.com/thomasrobitaille
    landing_twitter:            https://www.twitter.com/astrofrog
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1
```

### Browser and system

Any browser, MacOS X 10.15.6

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

File: app/Http/Controllers/AlbumController.php [hunk 1]
```diff
@@ -122,20 +122,17 @@ public function get(Request $request)
 				break;
 		}
 
-		$return = AlbumCast::toArray($album);
-		$return['owner'] = $album->owner->username;
-
 		if ($smart) {
+			$return = AlbumCast::toArray($album);
```
Comment (d7415) [inline app/Http/Controllers/AlbumController.php:126]: Do we need `$return['owner']`?

Comment (ildyria) [reply app/Http/Controllers/AlbumController.php:126]: Only in the case of a "normal" album.
