### PR TITLE
fix migration when photo do not have an album

### LINKED ISSUE #1695: error when migrating to latest 4.x
### Detailed description of the problem [REQUIRED]
when running php artisan migrate i am getting the following error:
```
   INFO  Running migrations.

  2018_08_15_103716_move_photos ............................................................................ 12ms FAIL

In Connection.php line 760:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fa
  ils (`lychee`.`photos`, CONSTRAINT `photos_album_id_foreign` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`) ON
   DELETE CASCADE) (SQL: insert into `photos` (`id`, `album_id`, `title`, `description`, `url`, `tags`, `public`, `ty
  pe`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `lens`, `model`, `shutter`, `focal`, `takestamp`, `star`
  , `thumbUrl`, `thumb2x`, `checksum`, `medium`, `small`, `license`, `updated_at`, `created_at`) values (150757936724
  12, 15075791937499, Schweiz Oktober 2017 395, , f74c006a3e61ff4061260f3075698683.JPG, , 1, image/jpeg, 640, 480, 47
  2.7 KB, 32, f/2.2, Apple, , iPhone 5s, 1/1786 s, 4.2 mm, 2017-10-05 14:55:09, 0, f74c006a3e61ff4061260f3075698683.j
  peg, 1, ec7ebc99bfc2bc58514b216f13771af7a4c8135f, , , none, 2023-01-07 17:29:38, 2023-01-07 17:29:38))


In Connection.php line 545:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fa
  ils (`lychee`.`photos`, CONSTRAINT `photos_album_id_foreign` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`) ON
   DELETE CASCADE)
```

### PR DESCRIPTION
**Pull request by ildyria**
Fixes #1695 

If a Lychee DB is corrupted (because some album have been removed but the photos are still there) then the first migration fails.

This small patch makes sure that all photos are transferred, those with no longer existing albums will be moved to `unsorted`.

### CODE REVIEW

File: database/migrations/2018_08_15_103716_move_photos.php [hunk 1]
```diff
@@ -35,7 +35,9 @@ public function up()
 				if ($result->album === 0) {
 					$photoAttributes['album_id'] = null;
 				} else {
-					$photoAttributes['album_id'] = Helpers::trancateIf32($result->album, 0);
+					$albumID = Helpers::trancateIf32($result->album, 0);
+					$exists = DB::table('albums')->select('*')->where('id', '=', $albumID)->count() !== 0;
```
Comment (d7415) [inline database/migrations/2018_08_15_103716_move_photos.php]: My gut tells me that
```suggestion
					$exists = DB::table('albums')->select('id')->where('id', '=', $albumID)->count() > 0;
```
would be better, but any difference would be negligible and is probably optimised away anyway.

**Review by d7415 — APPROVED** [review]
LGTM
