### PR TITLE
Fixes #1323.

### LINKED ISSUE #1323: install errors
**Steps to reproduce the issue**

download zip
Run composer install --no-dev to install dependencies
Copy .env.example as .env and edit it to match your parameters
Generate your secret key with php artisan key:generate
Go to web http://server/Lychee/public/install
First screen shows Lychee-installer -> click on Next button
Second screen shows error: "Please fix the errors before going to the next step." But all the checks are 'green'
Clicking Re-check button does not help

**Diagnostics**

php artisan lychee:diagnostics

In Connection.php line 712:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee.users' do
  esn't exist (SQL: select * from `users` where `users`.`id` = 0 limit 1)

In Connection.php line 368:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee.users' do
  esn't exist

System Information
Lychee Version (git): master  Default

composer install: --no-dev
APP_ENV: production
APP_DEBUG: false

System: win
PHP Version: 8.1

Browser and system
Server: Fedora 35/Apache
Client: Windows 10
Browser: any

[](https://sunos.top:1098/2022/05/14/c0c3ca1b41640.png)
Where did I go wrong?

I tried to php artisan migrate 
then I could not open the page 
[](https://sunos.top:1098/2022/05/14/d5a3a4080bac6.png)

and nginx REWRITE :

    if (!-e $request_filename)
    {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }

[](https://sunos.top:1098/2022/05/14/04077a3ab1000.png)

Diagnostics
-----------
Warning: 'D:\phpEnv\www\Lychee\public\dist\user.css' does not exist or has insufficient read/write privileges.
Warning: Dropbox import not working. dropbox_key is empty.
Warning: zend.assertions is enabled although Lychee is not in debug mode. Outside of debugging, code generation for assertions is recommended to be disabled for efficiency reasons

System Information
------------------
Lychee Version (release):        4.5.1
DB Version:                      4.5.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          WINNT
PHP Version:                     8.1
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        Asia/Shanghai
Max uploaded file size:          200M
Max post size:                   256M
Max execution time:              0
MySQL Version:                   5.7.28

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1808
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040501
check_for_updates:               0
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1

### PR DESCRIPTION
**Pull request by nagmat84**
Fixes a type-mangling error which caused #1323 and probably some similar reports.

### CODE REVIEW

**Review by qwerty287 — APPROVED** [review]

File: app/Actions/Install/RequirementsChecker.php [hunk 1]
```diff
@@ -27,7 +27,10 @@ public function check(array $requirements): array
 					foreach ($requirement_ as $requirement) {
 						$hasExtension = extension_loaded($requirement);
 						$results['requirements'][$type][$requirement] = $hasExtension;
-						$results['errors'] |= !$hasExtension;
+						// Note: Don't use the short-cut assignment `|=`;
+						// it silently converts the type to integer, because
+						// `|` is not the logical OR, but the bitwise OR.
```
Comment (ildyria) [inline app/Actions/Install/RequirementsChecker.php:32]: FFS.

**Review by ildyria — APPROVED** [review]

File: app/Actions/Install/RequirementsChecker.php (hunk 1 above)
Comment (nagmat84) [reply app/Actions/Install/RequirementsChecker.php:32]: Yes. Actually, my IDE told me about that. But it was categorized as a "notice". ("The result of this operation might potentially not be what you expect") Haha! Hence, it was basically flying below my radar in the noise of the remaining 400 warnings and errors.
