### PR TITLE
Fixes locale not working (#1754)

### LINKED ISSUE #1754: Language support stopped working
### Detailed description of the problem

Frontend languages stopped working

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Change Lychee language to something other than "en"
2. Open Lychee
3. Lychee is still english

I think this might got broken with https://github.com/LycheeOrg/Lychee/pull/1668 but I am not sure. It has worked some versions ago, but I cannot really tell when.

### PR DESCRIPTION
**Pull request by ildyria**
Fixes #1754 

When moving to Resources, this was done at the same time as migrating the locale to `lang/`, this induced a small bug.
Should now be resolved.

### CODE REVIEW

File: app/Http/Resources/InitResource.php [hunk 1]
```diff
@@ -34,12 +34,16 @@ public function toArray($request): array
 			$gitHubVersion->hydrate();
 		}
 
+		// we also return the local
```
Comment (qwerty287) [inline app/Http/Resources/InitResource.php]:
```suggestion
		// we also return the locale
```

**Review by qwerty287 — APPROVED** [review]
